In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import ase
import os
import ase.io
from tqdm.notebook import tqdm
tqdm.pandas()

In [2]:
def get_a2f(file_name,num_atoms):
    cm_to_eV = 13.605693122994
    
    with open(file_name,"r") as fp:
        lines = fp.readlines()
        
    freq = []
    tot_phdos = []
    site_proj_phdos = [[] for i in range(num_atoms*3)]
    for i in range(5,len(lines)-1):
        line = lines[i].split()
        freq.append(float(line[0])*cm_to_eV*1000)
        tot_phdos.append(float(line[1]))#/(cm_to_eV*1000))
        for j in range(0,num_atoms*3):
            site_proj_phdos[j].append(float(line[2+j])/(cm_to_eV*1000))
        
    return freq, tot_phdos, site_proj_phdos

def cal_lamb(freq_w,alpha_F):
    lambdaF = 0
    # try:
    for i in range(1,len(freq_w)):
        if freq_w[i]>0:
            dw = freq_w[i] - freq_w[i-1]
            w = freq_w[i]
            alpha_F_w = alpha_F[i]
            lambdaF = lambdaF + ((alpha_F_w/w)*dw)
    return 2*lambdaF

def cal_w_log(freq_w,alpha_F,lamb):
    w_logF = 0
    try:
        i = 1
        for i in range(1,len(freq_w)):
            if freq_w[i]>0:            
                dw = freq_w[i] - freq_w[i-1]
                w_logF = w_logF + (alpha_F[i]*np.log(freq_w[i])*dw/freq_w[i])
        return np.exp(2*w_logF/lamb)/0.08617
    except: 
        return np.nan          

def cal_w_sq(freq_w,alpha_F,lamb):
    w_sqF = 0
    try:
        for i in range(1,len(freq_w)):
            if freq_w[i]>0:
                dw = freq_w[i] - freq_w[i-1]
                w_sqF = w_sqF + (alpha_F[i]*freq_w[i]*dw)
        return ((2*w_sqF/lamb)**.5)/0.08617
    except:
        return np.nan

def cal_tc(lamb, omega_log,mu=0.1):
    frac = -1.04*(1+lamb)/(lamb-mu*(1+0.62*lamb))
    return (omega_log/1.2)*np.exp(frac)    

def cal_tc_ad(lamb,wlog,w2,tc,mu=0.1):
    f1 = (1+(lamb/(2.46*(1+3.8*mu)))**1.5)**(1/3)
    f2 = 1+((lamb**2)*((w2/wlog)-1))/(lamb**2+(1.82*(1+6.3*mu)*(w2/wlog))**2)
    return f1*f2*tc

In [3]:
from scipy.signal import savgol_filter

In [4]:
def get_tot_a2F(df):
    jobdir = f'{root}{df.name}/'
    # if os.path.isdir(jobdir+'run_2'):
    #     jobdir = jobdir + 'run_2/'
    filename = jobdir+"/relax.out"
    atom_obj = ase.io.read(filename)
    if os.path.isfile(jobdir+'/a2F.dos20'):
        filename = jobdir+"/relax.out"
        atom_obj = ase.io.read(filename)
        freq, phdos, site_proj_phdos = get_freq_phonon_2x2x2_interpolated_DOS(jobdir +"/a2F.dos20", atom_obj.get_global_number_of_atoms())
    else:
        phdos = np.nan
    return phdos 
    
def get_freq(df):
    jobdir = f'{root}{df.name}/'
    if os.path.isdir(jobdir+'run_2'):
        jobdir = jobdir + 'run_2/'
    filename = jobdir+"/relax.out"
    atom_obj = ase.io.read(filename)
    if os.path.isfile(jobdir+'/a2F.dos20'):
        filename = jobdir+"/relax.out"
        atom_obj = ase.io.read(filename)
        freq, phdos, site_proj_phdos = get_freq_phonon_2x2x2_interpolated_DOS(jobdir +"/a2F.dos20", atom_obj.get_global_number_of_atoms())
    else:
        freq = np.nan
    return freq

def get_target(df):    
    x = df.freq_a2f
    y = df.a2f
    xl = np.arange(0.25,101,0.1)
    y =  np.interp(xl,x,y) 
    Y = savgol_filter(y,101,3, mode='interp')
    #xll = np.arange(0.25,101,2.)
    Y = np.interp(Freq_final,xl,Y)     
    Y = np.asarray([y if y >0.0 else 0. for y in Y])
    return Y#/max(Y)

def get_freq_smooth(df):
    return Freq_final
Freq_final =np.arange(0.25,101,2)

In [5]:
par_el = 'run_full'
root = '/blue/hennig/jasongibson/diff_model'
root = f'{root}/materials/{par_el}/mp_relaxed/'
df = pd.read_pickle(f'pkl_files/df_cpd_{par_el}_strict.pkl')
df = df.loc[df.tcad_cpd >= 5]

In [6]:
def get_a2f_properties(df):
    jobdir = f'{root}{df.name}/'
    # if df.name == 1601:
    #     jobdir = jobdir + 'high/'  
    #     print('here')
    # elif os.path.isdir(jobdir+'run_2'):
    #     jobdir = jobdir + 'run_2/'    
    filename = jobdir + "/relax.out"
    
    try:
        atom_obj = ase.io.read(filename)
    except:
        return pd.Series([np.nan, np.nan], index=['freq_a2f', 'a2f'])
    
    if os.path.isfile(jobdir + 'a2F.dos20'):
        filename = jobdir + "/relax.out"
        atom_obj = ase.io.read(filename)
        freq, a2f, site_proj_a2f = get_a2f(jobdir +"a2F.dos20", atom_obj.get_global_number_of_atoms())
    else:
        freq, a2f, site_proj_a2f = np.nan, np.nan, np.nan
    
    return pd.Series([freq, a2f], index=['freq_a2f', 'a2f'])

df[['freq_a2f', 'a2f']] = df.apply(get_a2f_properties, axis=1)
# df[['freq_a2f_2', 'a2f_2']] = df.progress_apply(get_a2f_properties, axis=1)

/scratch/local/65299106/ipykernel_564693/990544361.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['freq_a2f', 'a2f']] = df.apply(get_a2f_properties, axis=1)
/scratch/local/65299106/ipykernel_564693/990544361.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['freq_a2f', 'a2f']] = df.apply(get_a2f_properties, axis=1)

In [7]:
print(df.shape)
df.dropna(axis=0,inplace=True)
print(df.shape)
# df['a2f'] = df.apply(get_target,axis=1)
# df['freq_a2f'] = df.apply(get_freq_smooth,axis=1)

def get_size(df):
    return len(df.structure)
df['natoms'] = df.apply(get_size, axis = 1)

(1363, 139)
(682, 139)

In [8]:
mu = 0.1
def get_lamb(df):
    try:
        return cal_lamb(df.freq_a2f,df.a2f)
    except:
        return np.nan

def get_w2(df):
    try:
        return cal_w_sq(df.freq_a2f,df.a2f,df.lamb_final)
    except:
        return np.nan

def get_wlog(df):
    try:
        return cal_w_log(df.freq_a2f,df.a2f,df.lamb_final)
    except:
        return np.nan

def get_tc(df):
    try:
        return cal_tc(df.lamb_final,df.wlog_final,mu)
    except:
        return np.nan

def get_tcad(df):
    try:
        return cal_tc_ad(df.lamb_final,df.wlog_final,df.w2_final,df.tc_final,mu)
    except:
        return np.nan

In [9]:
df['lamb_final'] = df.apply(get_lamb,axis=1)
df['w2_final'] = df.apply(get_w2,axis=1)
df['wlog_final'] = df.apply(get_wlog,axis=1)
df['tc_final'] = df.apply(get_tc,axis=1)
df['tcad_final'] = df.apply(get_tcad,axis=1)
df.sort_values('tcad_final', ascending = False,inplace=True)

/scratch/local/65299106/ipykernel_564693/1893784244.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lamb_final'] = df.apply(get_lamb,axis=1)
/scratch/local/65299106/ipykernel_564693/1893784244.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['w2_final'] = df.apply(get_w2,axis=1)
/scratch/local/65299106/ipykernel_564693/1893784244.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['wlog_final'] = df.apply(get_wlog,axis=1)
/scratch/local/65299106/ipykernel_564693/1893784244.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['tc_final'] = df.apply(get_tc,axis=1)
/scratch/local/65299106/ipykernel_564693/1893784244.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['tcad_final'] = df.apply(get_tcad,axis=1)

In [10]:
def get_nelements(df):
    return len(set(df.structure.get_chemical_symbols()))
df['nelements'] = df.apply(get_nelements,axis=1)

/scratch/local/65299106/ipykernel_564693/900407074.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['nelements'] = df.apply(get_nelements,axis=1)

In [12]:
df = df.loc[df.tcad_final>=5]#.loc[df.mp_eah <0.05][['formula','sgn','tcad_final','mp_eah']]#.head(20)
len(df)

612

In [18]:
df[['formula','tcad_final','sgn','mp_eah']]

         formula  tcad_final  sgn    mp_eah
872      GaNb6Si   36.424072  200  0.092368
7807      Re2Ru2   31.754612  123  0.139794
101256   Nb5Si2V   29.341672    1  0.121486
56153   HNNb6Sn2   28.157370  225  0.195628
5378     GaNb6Zn   28.148405  200  0.107763
...          ...         ...  ...       ...
133470    CMo2Tc    5.149593    8  0.061254
49806    Hf2HgNb    5.147089  123  0.066593
85339    Nb4ReTi    5.120639    1  0.030215
146616    Ir2Nb2    5.079045   11  0.024972
28533     Cr2Ir2    5.042043    2  0.036495

[612 rows x 4 columns]

In [18]:
from mp_api.client import MPRester

from pymatgen.core import Structure, Element, Composition
from pymatgen.analysis.phase_diagram import PhaseDiagram, PDEntry,PDPlotter
from pymatgen.ext.matproj import MPRester
from pymatgen.io.vasp import Vasprun
import os
from tqdm.notebook import tqdm
import pandas as pd

from pymatgen.io.vasp.outputs import Vasprun, Outcar, Potcar
from pymatgen.entries.computed_entries import ComputedEntry, ComputedStructureEntry
from pymatgen.entries.compatibility import MaterialsProject2020Compatibility

import re

from matplotlib import pyplot as plt

In [19]:
def sort_elements(formula):    # Extract elements using a regular expression
    elements = re.findall(r'[A-Z][a-z]*', formula)
    # Sort the elements alphabetically
    sorted_elements = ''.join(sorted(elements))
    return sorted_elements

In [20]:
api_org = '7JGUQgNZyOTTp8Tc'
api = '5nXBXhf4OGFQDbCo6BAyywL7yEp5RuQX'
compat = MaterialsProject2020Compatibility()
df['Sorted_Elements'] = df['formula'].apply(sort_elements)

# Sort the dataframe by the sorted elements
df.sort_values(by='Sorted_Elements',inplace=True)

In [21]:
root_relaxed = f'/blue/hennig/jasongibson/diff_model/materials/run_full/mp_relaxed'#/{par_el}/mp_relaxed/'

In [22]:
inds = []
eahs = []
cur_elements = {}

with MPRester(api) as mpr:
    for d, row in tqdm(df.iterrows(),total=len(df)):
        vr = Vasprun(f'{root_relaxed}/{d}/vasprun.xml') 
        struct = vr.final_structure
        species =list(set([spec.name for spec in struct.species]))            
        elements = struct.symbol_set
          
        if cur_elements != elements:
            entries = mpr.get_entries_in_chemsys(elements)
            cur_elements = elements
            phasediagram = PhaseDiagram(entries)    
        else:
            print('same?')
        
        potcar = Potcar.from_file(f'{root_relaxed}/{d}/POTCAR')
        potcar_symbols = [f'PBE {p.symbol}' for p in potcar]
        pde = ComputedStructureEntry(vr.final_structure,vr.final_energy)
        pde.parameters = {'run_type': 'GGA', 'potcar_symbols': potcar_symbols}  
        compat.process_entry(pde)
        
        eah = phasediagram.get_e_above_hull(pde,allow_negative=True)
        print(f'{row.formula}\t {eah:.4f}')
        inds.append(int(d))
        eahs.append(eah)

  0%|          | 0/612 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/io/vasp/outputs.py:310: EncodingWarning: We strongly encourage explicit `encoding`, and we would use UTF-8 by default as per PEP 686
  with zopen(filename, mode="rt") as file:
/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/io/vasp/inputs.py:2664: EncodingWarning: We strongly encourage explicit `encoding`, and we would use UTF-8 by default as per PEP 686
  with zopen(filename, mode="rt") as file:

Retrieving ThermoDoc documents:   0%|          | 0/67 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2AlH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HAlHfNb2	 0.1028

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6AlIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AlIrNb6	 -0.0068

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (AlTcMo6). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AlMo6Tc	 0.0175

Retrieving ThermoDoc documents:   0%|          | 0/51 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6AlP). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AlNb6P	 0.1446

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6AlRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AlNb6Rh	 0.0495

Retrieving ThermoDoc documents:   0%|          | 0/81 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr6AlSn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AlSnZr6	 0.0795

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6InAs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AsInNb6	 0.0936

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo6AsOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AsMo6Os	 -0.0071

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo6AsPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AsMo6Pt	 -0.0219

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo6As). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AsMo6Tc	 0.0295

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2HAu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HAuHfNb2	 0.1652

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6PtAu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AuNb6Pt	 -0.0007

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb2Au). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

AuNb2Ti	 0.0998
same?
AuNb2Ti	 0.1000

Retrieving ThermoDoc documents:   0%|          | 0/14 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Be2Nb3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Be4Nb6	 -0.0055

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2BeNb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

BeNbTi2	 0.1453

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2BeNb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

BeNbZr2	 0.1691

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaBe4Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Be4RhTa	 0.0352

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti4Be). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

BeTi4	 0.1446

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTi2Be). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

BeTi2Zr	 0.1333

Retrieving ThermoDoc documents:   0%|          | 0/14 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr5Be). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

BeZr5	 0.0767

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6GeBi). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

BiGeNb6	 0.0831

Retrieving ThermoDoc documents:   0%|          | 0/109 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo2IrC). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CIrMo2	 0.0659

Retrieving ThermoDoc documents:   0%|          | 0/91 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo2C). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CMo2Tc	 0.0613

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CoTc2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CoMoTc2	 0.0895

Retrieving ThermoDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbCo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CoNbTi2	 0.1067

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CoReTcRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CoReRuTc	 0.1443

Retrieving ThermoDoc documents:   0%|          | 0/13 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CoTc3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CoTc3	 0.1102
same?
CoTc3	 0.1101

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CrMoH2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H2CrMo	 0.0329

Retrieving ThermoDoc documents:   0%|          | 0/74 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VCrTcHPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HCrPtTcV	 0.1520

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Cr2HRuRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HCr2RhRu	 0.1642

Retrieving ThermoDoc documents:   0%|          | 0/15 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CrIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Cr2Ir2	 0.0365

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CrRe2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrIrRe2	 0.1368
same?
Cr2IrRe	 0.1693

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Cr2ReIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CrIrRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrIrRu2	 0.0993
same?
Cr2IrRu	 0.1169

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Cr2IrRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CrTc2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrIrTc2	 0.1887

Retrieving ThermoDoc documents:   0%|          | 0/17 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MnCrTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrMnTc2	 0.1620

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VCrMoRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrMoRuV	 0.1992

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

CrMoTcW	 0.0553

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2CrMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrMoTi2	 0.1538

Retrieving ThermoDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiVCrMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrMoTiV	 0.1610

Retrieving ThermoDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2CrMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrMoZr2	 0.1803

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbCrTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrNbTc2	 0.0747

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Cr2OsRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Cr2OsRh	 0.1700

Retrieving ThermoDoc documents:   0%|          | 0/64 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (CrSiTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrSiTc2	 0.1275

Retrieving ThermoDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

CrTc2W	 0.1255
same?
CrTcW	 0.1142

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

CrTi2W	 0.1663

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTi2Cr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CrTi2Zr	 0.1794

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2Nb3Cu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

CuNb3Zr2	 0.1049

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb6Ga). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaHfNb6	 0.1034
same?
GaHf2Nb	 0.1090

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2NbGa). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6GaIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaIrNb6	 0.0217

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (GaTcMo5Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaMo5OsTc	 0.0075

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (GaReMo6). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaMo6Re	 0.0095

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb7Ga). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaNb7	 0.0478

Retrieving ThermoDoc documents:   0%|          | 0/82 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6GaSi). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaNb6Si	 0.1013

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6ZnGa). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaNb6Zn	 0.1093

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrNb6Ga). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaNb6Zr	 0.1334
same?
GaNbZr2	 0.1165

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2NbGa). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr6GaPb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaPbZr6	 0.1018

Retrieving ThermoDoc documents:   0%|          | 0/77 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr6GaSn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GaSnZr6	 0.0967

Retrieving ThermoDoc documents:   0%|          | 0/64 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6Ge2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HGe2Nb6	 0.0787

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb6Ge). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GeHfNb6	 0.0992

Retrieving ThermoDoc documents:   0%|          | 0/74 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2GeMo4Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GeIrMo4Nb2	 0.0499

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6GeIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GeIrNb6	 0.0505

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6GePb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GeNb6Pb	 0.1418

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6ZnGe). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GeNb6Zn	 0.1115

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr6GePb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

GePbZr6	 0.1490

Retrieving ThermoDoc documents:   0%|          | 0/60 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2HgH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfHgNb2	 0.1396
same?
HHfHgNb2	 0.1403

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNbH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfNb	 0.1253
same?
HHfNb3	 0.1352

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb3H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HHf2Nb	 0.1395

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2NbH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HHfNb	 0.1249
same?
H2Hf4Nb4	 0.1455

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2Nb2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HHfNb3	 0.1352

Retrieving ThermoDoc documents:   0%|          | 0/62 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2SnH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfNb2Sn	 0.1117

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTaNb2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfNb2Ta	 0.1261

Retrieving ThermoDoc documents:   0%|          | 0/64 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiNb2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfNb2Ti	 0.1214

Retrieving ThermoDoc documents:   0%|          | 0/57 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZr2ScH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfScZr2	 0.1418

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf3SnH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHf3Sn	 0.0946

Retrieving ThermoDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTi3H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfTi3	 0.1397
same?
HHfTi3	 0.1555
same?
HHf2Ti	 0.1549

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2TiH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HHf2Ti2	 0.1581

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2Ti2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HHfTi	 0.1194

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/68 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTi2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHfTi2Zr	 0.1617
same?
HHf2TiZr	 0.1590

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2ZrTiH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HHfTi2Zr	 0.1617
same?
HHfTi2Zr	 0.1617
same?
HHf2TiZr	 0.1615
same?
HHfTi2Zr	 0.1617
same?
HHfTiZr2	 0.1468

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZr2TiH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf3ZrH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHf3Zr	 0.1418

Retrieving ThermoDoc documents:   0%|          | 0/65 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrNb2HgH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HHgNb2Zr	 0.1558

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3InH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HInNb3	 0.0299

Retrieving ThermoDoc documents:   0%|          | 0/71 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTcMoHIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HIrMoNbTc	 0.1328

Retrieving ThermoDoc documents:   0%|          | 0/37 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2HIr2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HIr2Nb2	 0.0721

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La6H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HLa6	 0.0938
same?
HLa4	 0.0589

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La4H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HLa5	 0.0956

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La5H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HLa3	 0.1096

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HLa4	 0.0589

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3ScH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HLa3Sc	 0.1306

Retrieving ThermoDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3SnH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HLa3Sn	 0.1148

Retrieving ThermoDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3YH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HLa3Y	 0.0931

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MoH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H2Mo2	 -0.0833
same?
H2Mo2	 -0.0835
same?
H4Mo4	 -0.0838
same?
H2Mo2	 -0.0838

Retrieving ThermoDoc documents:   0%|          | 0/70 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo4HN). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HMo4N	 0.0157

Retrieving ThermoDoc documents:   0%|          | 0/106 [00:00<?, ?it/s]

HMoNNb	 -0.0091

Retrieving ThermoDoc documents:   0%|          | 0/89 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2Mo2HN). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HMo2NTc2	 0.0052

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3MoH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H2Mo2Nb6	 0.0725

Retrieving ThermoDoc documents:   0%|          | 0/62 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoHPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HMoNb2Pt	 0.1192
same?
HMoNb2Pt	 0.1189

Retrieving ThermoDoc documents:   0%|          | 0/90 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNbMoHPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HMoNbPtTa	 0.1264

Retrieving ThermoDoc documents:   0%|          | 0/71 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb2MoH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HMoNb2Ti	 0.1104
same?
HMoNbTi2	 0.1051

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbMoH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo2H3Pd2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H3Mo2Pd2	 -0.0054

Retrieving ThermoDoc documents:   0%|          | 0/95 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6Sn2HN). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNNb6Sn2	 0.1595

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb4H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H2Nb8	 0.0014
same?
HNb8	 0.0051

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb8H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
H2Nb8	 -0.0019

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbHRu3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNbRu3	 0.0858

Retrieving ThermoDoc documents:   0%|          | 0/88 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6Si2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNb6Si2	 0.1014

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNb5H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNb5Ta	 0.0155
same?
HNb3Ta	 0.0220

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNb3H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/74 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaTiNb2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNb2TaTi	 0.1230

Retrieving ThermoDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTaNb2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNb2TaZr	 0.1516

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2TcH2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H2Nb2Tc	 0.0036

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNb2Ti	 0.1248
same?
HNb3Ti	 0.1107

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb3H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HNbTi3	 0.1307

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti3NbH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HNbTi2	 0.0999

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HNbTi2	 0.0944

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3ZnH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HNb3Zn	 0.1372

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr7HPb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HPbZr7	 0.0581

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VTc2HRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HRhTc2V	 0.1985

Retrieving ThermoDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2Sc2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HSc2Zr2	 0.1240

Retrieving ThermoDoc documents:   0%|          | 0/58 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ta3TiH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HTa3Ti	 0.1290
same?
HTa2Ti2	 0.1535

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ta2Ti2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

HTc2W2	 0.1927

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti4H3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

H3Ti4	 0.1101
same?
H2Ti4	 0.1038

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTi3H). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HTi3Zr	 0.1547
same?
HTiZr3	 0.1321

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr3TiH). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HTiZr3	 0.1334

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2NbHg). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2HgNb	 0.0666

Retrieving ThermoDoc documents:   0%|          | 0/54 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2Ir2Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfIr2Nb2Rh	 0.1007

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2Ir2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfIr2Nb2Ru	 0.1228

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiNbIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfIrNbTi	 0.1134

Retrieving ThermoDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrNb3Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfIrNb3Zr	 0.0766

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (LaHfOs4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfLaOs4	 0.2021

Retrieving ThermoDoc documents:   0%|          | 0/133 [00:00<?, ?it/s]

HfLiMo3N6Nb	 -0.0329

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2MnNb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2MnNb	 0.1330

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTi2Mn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMnTi2	 0.1255
same?
HfMnTi2	 0.1253
same?
HfMnTi2	 0.1255
same?
HfMnTi2	 0.1253
same?
HfMnTi2	 0.1252
same?
HfMnTi2	 0.1254
same?
HfMnTi2	 0.1255

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZr2Mn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMnZr2	 0.1329
same?
Hf2MnZr	 0.1152

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2ZrMn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2Mo2	 0.1343
same?
Hf2Mo2	 0.1350
same?
Hf3Mo	 0.0498

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf3Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2NbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2MoNb	 0.0546
same?
HfMoNb	 0.1158

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTaNbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoNbTa	 0.0433

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTa2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTa2	 0.1152

Retrieving ThermoDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTaTiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTaTi	 0.0965

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTaVMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTaV	 0.1413

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZr2TaMo2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMo2TaZr2	 0.1038

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTc4Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTc4	 0.1461
same?
Hf2MoTc	 0.1040

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2TcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/50 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiTcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTcTi	 0.1116

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTcZr	 0.1251

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoTi	 0.0831
same?
Hf2MoTi2	 0.0401

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2Ti2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HfMo2Ti	 0.1118

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiMo2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Hf2MoTi	 0.1052

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2TiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/37 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (YHfZrMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfMoYZr	 0.1395

Retrieving ThermoDoc documents:   0%|          | 0/51 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrNbPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNbPtZr	 0.0627

Retrieving ThermoDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2Re). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNb2Re	 0.0995
same?
Hf2NbRe	 0.1987

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2NbRe). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HfNb2Re	 0.1658

Retrieving ThermoDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiNbRe). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNbReTi	 0.1390

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrNbRe). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNbReZr	 0.1707

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2NbRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2NbRh	 0.0570

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2Nb3Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2Nb3Ru	 0.0472

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2Sb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNb2Sb	 0.1273

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfScTaNb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNbScTa	 0.1480

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb6Sn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNb6Sn	 0.0461

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTaNbTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNbTaTc	 0.1942

Retrieving ThermoDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNb2Tc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfNb2Tc	 0.1975
same?
HfNbTc4	 0.1142

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfNbTc4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
HfNb2Tc	 0.1763

Retrieving ThermoDoc documents:   0%|          | 0/54 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTaOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfOsRuTa	 0.0653

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrOs4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfOs4Zr	 0.0967

Retrieving ThermoDoc documents:   0%|          | 0/12 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfRe2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2Re4	 0.0941
same?
Hf2Re4	 0.0942
same?
Hf2Re4	 0.0939

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTi2Re). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfReTi2	 0.1260

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTiRe). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfReTiZr	 0.0884

Retrieving ThermoDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTiRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfRhTiZr	 0.1928

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZr2Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfRhZr2	 0.0788

Retrieving ThermoDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (YHfRu4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfRu4Y	 0.1761

Retrieving ThermoDoc documents:   0%|          | 0/17 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfSc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfSc	 0.1407
same?
Hf3Sc	 0.1235

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf3Sc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfScTc4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfScTc4	 0.0642

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrSc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfScZr	 0.1230
same?
HfScZr	 0.1253
same?
HfSc2Zr	 0.1139

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrSc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2TaV). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2TaV	 0.1825

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTaV). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTaVZr	 0.1751

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

HfTaWZr	 0.1454

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTa4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTa4Zr	 0.1151

Retrieving ThermoDoc documents:   0%|          | 0/9 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Hf2Tc4	 0.0565

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTi2Tc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTcTi2	 0.0717
same?
Hf2TcTi	 0.1470

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Hf2TiTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Hf2TcTi	 0.0692

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZrTiTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTcTiZr	 0.0508

Retrieving ThermoDoc documents:   0%|          | 0/14 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (YHfTc4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTc4Y	 0.0849
same?
HfTc4Y	 0.0848
same?
HfTc4Y	 0.0848

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfTiV). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTiV	 0.1778

Retrieving ThermoDoc documents:   0%|          | 0/68 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (HfZr2Ti2Zn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HfTi2ZnZr2	 0.1446

Retrieving ThermoDoc documents:   0%|          | 0/24 [00:00<?, ?it/s]

HfV2W	 0.1961

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbHg). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

HgNbTi2	 0.0739

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6InP). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

InNb6P	 0.1914

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6InSb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

InNb6Sb	 0.0424

Retrieving ThermoDoc documents:   0%|          | 0/71 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr6InSn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

InSnZr6	 0.0846

Retrieving ThermoDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr7In). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

InZr7	 0.1156

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (LaPIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrLaP	 0.0704

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MnMo2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMnMo2	 0.1391

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoIr3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir3MoNb2	 0.0103
same?
Ir2Mo2Nb2	 0.1318

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMoIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Ir3MoNb2	 0.0092
same?
IrMoNb2	 0.1378

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Ir2MoNb3	 0.0705

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3MoIr2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoIr2Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir2MoNb2Os	 0.0802
same?
IrMo2NbOs2	 0.0459

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo2IrOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2ReMoIr2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir2MoNb2Re	 0.1022

Retrieving ThermoDoc documents:   0%|          | 0/80 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2ReMoIrRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMoNb2ReRu	 0.1551

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTcMoIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMoNbTc	 0.1632

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2ZnMo4Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMo4Nb2Zn	 0.0713

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo4IrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMo4Os	 0.0720
same?
IrMoOs2	 0.0998

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MoIrOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Ir2Mo3Os	 0.0377

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo3Ir2Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Ir2Mo3Os	 -0.0275

Retrieving ThermoDoc documents:   0%|          | 0/50 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMo2IrOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMo2Os2Re	 0.0604

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MoIrOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMoOsRu	 0.1365
same?
IrMoOsRu	 0.0855
same?
IrMo2Os2Ru	 0.0825

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo2IrOs2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
IrMo3OsRu	 0.0643

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo3IrOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMoIrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMoOsTc	 0.0682

Retrieving ThermoDoc documents:   0%|          | 0/63 [00:00<?, ?it/s]

IrMo2OsTcW	 0.1114

Retrieving ThermoDoc documents:   0%|          | 0/58 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrMo2IrOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMo2Os2Zr	 0.1833

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMo2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMo2Re	 0.0626

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMoIrRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMoRuTc	 0.1515
same?
Ir2Mo2RuTc	 0.0518

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo2Ir2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/47 [00:00<?, ?it/s]

IrMo2Ru2W	 0.0531

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrMo2Tc	 0.1001

Retrieving ThermoDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

IrMoTcW	 0.1958

Retrieving ThermoDoc documents:   0%|          | 0/15 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir3Nb3	 0.0227
same?
Ir2Nb2	 0.0250
same?
Ir3Nb3	 0.0049
same?
IrNb7	 0.0428

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb7Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2IrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrNb2Os	 0.0886

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2Ir2OsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir2Nb2OsRu	 0.0946

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6IrPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrNb6Pt	 -0.0098
same?
IrNb4Pt	 0.1865

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb4IrPt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3IrRh2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrNb3Rh2	 0.0726

Retrieving ThermoDoc documents:   0%|          | 0/59 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2VIr2Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir2Nb2RhV	 0.1026

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3IrRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrNb3Ru2	 0.0483

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

Ir2Nb2RuW	 0.0770

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6SnIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrNb6Sn	 0.0571

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6TcIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrNb6Tc	 -0.0191

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2VIr3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir3Nb2V	 0.0739

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2IrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrOsRe2	 0.0990

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReIrOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrOsReRu	 0.0984

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcIrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrOsReTc	 0.1584
same?
IrOsReTc	 0.1053
same?
IrOsReTc	 0.1226

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcIrOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrOsRuTc	 0.1219
same?
IrOsRuTc	 0.0871

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2IrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrOsTc2	 0.1422
same?
IrOs2Tc	 0.0869

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcIrOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
IrOsTc2	 0.0899
same?
IrOsTc2	 0.1583

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VTcIrOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrOsTcV	 0.1270

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2IrRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrRe2Ru	 0.0817
same?
IrRe2Ru	 0.1016
same?
IrReRu2	 0.0891

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReIrRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
IrRe2Ru	 0.1298
same?
IrReRu2	 0.1205

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2TcIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrRe2Tc	 0.0975
same?
IrReTc	 0.1504

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

IrRe2W	 0.1091

Retrieving ThermoDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcIrRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrRu2Tc	 0.0832
same?
IrRuTc2	 0.1068

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2IrRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VIrRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrRu2V	 0.0595

Retrieving ThermoDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir3Ta3	 0.0372

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaVIr2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir2TaV	 0.0956

Retrieving ThermoDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrTc2	 0.1263
same?
IrTc3	 0.1753

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc3Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/24 [00:00<?, ?it/s]

IrTc4W	 0.1162
same?
IrTc2W	 0.0703

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTcIr). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ir2Tc2Zr2	 0.0448

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTi2Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrTi2Zr	 0.1789

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr3Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

IrZr3	 0.0892
same?
IrZr3	 0.0880
same?
IrZr4	 0.0536

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr4Ir). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/54 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La2Mg). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

La4Mg2	 0.1109
same?
La4Mg2	 0.1356
same?
La3Mg	 0.0892

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3Mg). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
La3Mg	 0.0893

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

La3N	 0.0697

Retrieving ThermoDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3Pb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

La3Pb	 0.1019

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (LaZrRu4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

LaRu4Zr	 0.1942

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (La3Sb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

La3Sb	 0.1038

Retrieving ThermoDoc documents:   0%|          | 0/64 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mn3MoN). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mn3MoN	 0.1221

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MnNb2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MnNb2Ru	 0.1070

Retrieving ThermoDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MnTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mn2Tc2	 0.1819

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiMnV2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MnTiV2	 0.1756

Retrieving ThermoDoc documents:   0%|          | 0/59 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTiMnV). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MnTiVZr	 0.1913

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTi2Mn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MnTi2Zr	 0.1061
same?
MnTi2Zr	 0.1059

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo2N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2N	 -0.0657

Retrieving ThermoDoc documents:   0%|          | 0/65 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo2OsN). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NOs	 -0.0304

Retrieving ThermoDoc documents:   0%|          | 0/62 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo2PtN). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NPt	 0.0726

Retrieving ThermoDoc documents:   0%|          | 0/81 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMo2N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NRe	 -0.0322
same?
Mo2NRe	 -0.0317

Retrieving ThermoDoc documents:   0%|          | 0/84 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaMo3N2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3N2Ta	 0.0410

Retrieving ThermoDoc documents:   0%|          | 0/60 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo3N2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3N2Tc	 0.0030
same?
Mo3NTc	 0.0411

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo3N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo2NTc2	 0.0254

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2Mo2N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoOs3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNb2Os3	 0.1387
same?
MoNb2Os3	 0.0952
same?
MoNbOs2	 0.1468

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMoOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo5NbOs2	 -0.0376

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo5Os2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo3NbOs2	 0.0989

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo3Os2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo2NbOs	 0.0918

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo2Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNb2Os3	 0.1386
same?
Mo4Nb2Os2	 -0.0099
same?
Mo3NbOs2	 0.1570

Retrieving ThermoDoc documents:   0%|          | 0/50 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo2OsRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NbOsRu2	 0.1042
same?
Mo2NbOs2Ru	 0.0677

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo2Os2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo2NbOs2Ru	 0.0893
same?
MoNb2OsRu2	 0.0900

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoOsRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNb2Os2Ru	 0.0912

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2MoOs2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo5NbOsRu	 0.0038

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo5OsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbOsRu	 0.1473

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMoOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNb2Os2Ru	 0.0858
same?
MoNb2OsRu2	 0.0872
same?
MoNb2OsRu2	 0.0902
same?
MoNb2OsRu2	 0.0902

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3SbMo3Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3Nb3OsSb	 0.1273

Retrieving ThermoDoc documents:   0%|          | 0/53 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNb(MoOs)2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NbOs2Ta	 0.1709

Retrieving ThermoDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbReMo5Pt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo5NbPtRe	 0.0107

Retrieving ThermoDoc documents:   0%|          | 0/51 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTcMo5Pt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo5NbPtTc	 0.0252

Retrieving ThermoDoc documents:   0%|          | 0/50 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbReTcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNbReTc	 0.0978
same?
MoNbReTc	 0.1229
same?
MoNbReTc	 0.1042

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3MoRh2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNb3Rh2	 0.1364
same?
MoNb6Rh	 0.0438

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6MoRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNb3Rh2	 0.1086
same?
MoNb3Rh2	 0.0781

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc2Mo2Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NbRhTc2	 0.1437

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo6Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo6NbRu	 0.0777
same?
Mo3NbRu2	 0.1351

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMo3Ru2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbRu2	 0.1403

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbMoRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbRu2	 0.1404

Retrieving ThermoDoc documents:   0%|          | 0/67 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb2SbMo4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo4Nb2SbTi	 0.1295

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrScNbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNbScZr	 0.1090

Retrieving ThermoDoc documents:   0%|          | 0/96 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbSiTcMo5). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo5NbSiTc	 0.0329
same?
Mo4Nb2SiTc	 0.0459

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2SiTcMo4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/116 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2Nb2SiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNb2SiTi2	 0.1958

Retrieving ThermoDoc documents:   0%|          | 0/96 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb5ZnSiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNb5SiZn	 0.1280

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb5Sn2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNb5Sn2	 0.0190

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNb2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNb2Ta	 -0.0024
same?
MoNbTa2	 -0.0122

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ta2NbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/58 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaTiNbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNbTaTi	 0.0483
same?
MoNbTaTi	 0.0582

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc3Mo2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2NbTc3	 -0.0082
same?
MoNbTc	 0.0282

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo2NbTc3	 -0.0116
same?
MoNbTc2	 0.0422

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbTc4	 0.0999

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc4Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbTc2	 0.0398
same?
Mo3NbTc2	 -0.0064

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc2Mo3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbTc2	 0.0255
same?
Mo4NbTc	 -0.0172

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTcMo4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbTc3	 0.0524

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc3Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbMo3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3NbTi2	 0.0306
same?
Mo2NbTi2	 -0.0009

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbMo2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2NbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNbZr2	 0.1012
same?
MoNbZr	 0.1020

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrNbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoNbZr3	 0.0330

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr3NbMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2NiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoNiTc2	 0.1160

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo6POs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo6OsP	 0.0278

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMoOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoOsRe	 0.1869
same?
Mo2Os3Re	 0.0521

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMo2Os3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo2Os3Re	 0.0497
same?
MoOs3Re2	 0.1110

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2MoOs3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoOsRe	 0.1872

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMoOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoOsReRu	 0.1933
same?
MoOsReRu	 0.0893
same?
MoOsReRu	 0.1100

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

Mo5OsRhW	 0.0206

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo3OsRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3OsRu2	 0.0705
same?
Mo4OsRu	 0.0684

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo4OsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Mo6OsRu	 -0.0293

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Mo6OsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoOsRu2	 0.0736

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (MoOsRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
MoOsRu2	 0.1012

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

Mo2OsRu2W	 0.0886

Retrieving ThermoDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaMo3Os2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3Os2Ta	 0.1358

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMoRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoReRu2	 0.0566
same?
Mo6ReRu	 -0.0188

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReMo6Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReSbMo6). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo6ReSb	 0.0609

Retrieving ThermoDoc documents:   0%|          | 0/97 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReSiTcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoReSiTc	 0.1616
same?
MoReSiTc	 0.1812
same?
Mo5ReSiTc	 -0.0018

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReSiTcMo5). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2ReMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoReTi2	 0.1006

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2MoRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoRhTc2	 0.0890

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2MoRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoRuTc2	 0.1623

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaTi2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoTaTi2	 0.0621
same?
MoTa2Ti	 0.0697

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ta2TiMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2TaMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoTaZr2	 0.0491
same?
MoTa2Zr	 0.1124

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTa2Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/15 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcMo2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo4Tc2	 0.0087
same?
MoTc3	 0.1201

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc3Mo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2TcMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

MoTcTi2	 0.0725

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTiTcMo3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo3TcTiZr	 0.1935

Retrieving ThermoDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrMo). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Mo2Zr2	 0.1426

Retrieving ThermoDoc documents:   0%|          | 0/61 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTc2N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NReTc2	 0.0830

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr3N). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NZr3	 0.0756
same?
NZr3	 0.0634

Retrieving ThermoDoc documents:   0%|          | 0/24 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbReOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbOs2Re	 0.1465

Retrieving ThermoDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNbOs4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbOs4Ta	 0.1648
same?
NbOs4Ta	 0.1656

Retrieving ThermoDoc documents:   0%|          | 0/24 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc2Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbOsTc2	 0.1845

Retrieving ThermoDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb7Pt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb7Pt	 0.0217
same?
Nb6Pt2	 -0.0111

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3Pt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbReRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbReRu2	 0.1554

Retrieving ThermoDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

Nb2ReRu2W	 0.1053

Retrieving ThermoDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

NbReTcW	 0.1559

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb4Re). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb4ReTi	 0.0302
same?
NbReTi2	 0.1197

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbRe). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb2Rh2	 0.0710
same?
Nb3Rh	 0.0846

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb3Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/31 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2VRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb2RhV	 0.1180

Retrieving ThermoDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6ZnRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb6RhZn	 0.0463

Retrieving ThermoDoc documents:   0%|          | 0/15 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb2Ru4	 0.1060
same?
Nb4Ru2	 0.1522

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
NbRu3	 0.0604

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbRu3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbVTcRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbRuTcV	 0.0870

Retrieving ThermoDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

Nb2Ru2TcW	 0.1067

Retrieving ThermoDoc documents:   0%|          | 0/82 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb6SiSb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb6SbSi	 0.0673

Retrieving ThermoDoc documents:   0%|          | 0/59 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb7Si). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb7Si	 0.1517

Retrieving ThermoDoc documents:   0%|          | 0/79 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Nb5VSi2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb5Si2V	 0.1392

Retrieving ThermoDoc documents:   0%|          | 0/78 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2Nb3Si). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb6Si2Zr4	 0.1631

Retrieving ThermoDoc documents:   0%|          | 0/61 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2NbSn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb2Sn2Zr4	 0.1717

Retrieving ThermoDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb3Ta3	 0.0254
same?
Nb4Ta2	 0.0206

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaNb2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
NbTa2	 0.0319

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ta2Nb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTa2Nb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTa2Zr	 0.1079
same?
Nb2TaZr	 0.0991

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTaNb2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
NbTa2Zr	 0.1522
same?
Nb2TaZr	 0.1214

Retrieving ThermoDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc6). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTc6	 0.1557
same?
Nb2Tc4	 0.0257

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
NbTc6	 0.1555
same?
NbTc4	 0.1059

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (NbTc4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/27 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti3NbTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTc2Ti3	 0.0557
same?
NbTcTi2	 0.1201

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
NbTcTi2	 0.0613

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNbVTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTcTiV	 0.1077

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrNbVTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTcVZr	 0.1921

Retrieving ThermoDoc documents:   0%|          | 0/24 [00:00<?, ?it/s]

NbTc2W	 0.0637

Retrieving ThermoDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrNb2Tc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb2TcZr	 0.0902
same?
Nb4TcZr	 0.0515

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrNb4Tc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Nb2TcZr	 0.1369
same?
Nb2TcZr	 0.1589
same?
Nb2TcZr	 0.0844

Retrieving ThermoDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiNb3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Nb3Ti	 0.0542

Retrieving ThermoDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTiNbV). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTiVZr	 0.1335

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti2NbZn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTi2Zn	 0.1054

Retrieving ThermoDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2NbTl). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbTlZr2	 0.1261

Retrieving ThermoDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2NbZn). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

NbZnZr2	 0.1658

Retrieving ThermoDoc documents:   0%|          | 0/13 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re3Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsRe3	 0.1565

Retrieving ThermoDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaReOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsReRuTa	 0.1696

Retrieving ThermoDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsReRuTc	 0.1264
same?
OsReRuTc	 0.1723
same?
OsReRuTc	 0.1573

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2Tc3Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsRe2Tc3	 0.1073
same?
OsReTc2	 0.0097

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTc2Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
OsReTc	 0.1443

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
OsReTc2	 0.1375
same?
Os2ReTc	 0.1228

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
OsRe2Tc	 0.1365

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2TcOs). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

OsReTcW	 0.1444

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

OsRe4W	 0.1074
same?
Os2ReW	 0.1041

Retrieving ThermoDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaOs2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Os2RuTa	 0.0227
same?
Os2RuTa	 0.0795
same?
OsRu2Ta	 0.0437

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaOsRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaTcOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsRuTaTc	 0.1780

Retrieving ThermoDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTaOsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsRuTaZr	 0.0508

Retrieving ThermoDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc4OsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsRuTc4	 0.1213
same?
Os2RuTc	 0.1485

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcOs2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
OsRuTc2	 0.1376

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2OsRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
OsRu2Tc	 0.1564

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcOsRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
OsRu2Tc	 0.1557

Retrieving ThermoDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

OsRuTcW	 0.1011
same?
OsRuTcW	 0.0561

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VOs2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Os2RuV	 0.0903

Retrieving ThermoDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

OsRuVW	 0.1318

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

OsRuW2	 0.1157
same?
OsRuW2	 0.1150
same?
OsRuW2	 0.1136

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ScOs2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Os4Sc2	 0.0869

Retrieving ThermoDoc documents:   0%|          | 0/11 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc3Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsTc3	 0.1419

Retrieving ThermoDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr5Os). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

OsZr5	 0.0393

Retrieving ThermoDoc documents:   0%|          | 0/48 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr6SbPb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

PbSbZr6	 0.0894

Retrieving ThermoDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr3Pb). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Pb2Zr6	 0.0310

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VTc2Pt). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

PtTc2V	 0.1338

Retrieving ThermoDoc documents:   0%|          | 0/13 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re3Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re3Rh	 0.1688

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2TcRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re2RhTc	 0.1552

Retrieving ThermoDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re3Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re3Ru	 0.1657
same?
Re3Ru	 0.1434
same?
Re2Ru2	 0.1398

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Re2Ru	 0.1908

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Re3Ru	 0.1813
same?
Re2Ru	 0.1733
same?
Re2Ru	 0.1684
same?
ReRu3	 0.1822

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReRu3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaReRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReRu2Ta	 0.1751

Retrieving ThermoDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTc2Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReRuTc2	 0.0248
same?
ReRuTc2	 0.1159
same?
ReRuTc2	 0.1181
same?
ReRuTc2	 0.0310
same?
Re2RuTc	 0.1268

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2TcRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
ReRu2Tc	 0.1295

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Re2RuTc	 0.1561
same?
Re2RuTc	 0.0450
same?
Re2RuTc	 0.0488
same?
ReRuTc4	 0.0221

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTc4Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Re2RuTc	 0.0597
same?
ReRu2Tc	 0.1670
same?
ReRuTc	 0.1539

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTcRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
ReRuTc2	 0.0386
same?
ReRuTc2	 0.1363
same?
Re2RuTc	 0.1285
same?
Re2RuTc3	 0.1165

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Re2Tc3Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
Re2RuTc	 0.1279
same?
ReRu2Tc	 0.1626

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

ReRuTcW	 0.0974

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

ReRu2W	 0.1127
same?
ReRu2W	 0.1337

Retrieving ThermoDoc documents:   0%|          | 0/67 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReSiTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReSiTc2	 0.0264

Retrieving ThermoDoc documents:   0%|          | 0/17 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaRe2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re4Ta2	 0.0918

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaTi2Re). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReTaTi2	 0.1351
same?
ReTaTi2	 0.0953

Retrieving ThermoDoc documents:   0%|          | 0/30 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTaRe4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re4TaZr	 0.1091
same?
Re4TaZr	 0.1091

Retrieving ThermoDoc documents:   0%|          | 0/11 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ReTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re2Tc2	 0.0357
same?
ReTc	 0.0926
same?
Re2Tc2	 0.0359

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiReTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReTc2Ti	 0.0488
same?
ReTc2Ti	 0.1103

Retrieving ThermoDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VReTc2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReTc2V	 0.1865
same?
ReTc2V	 0.1855

Retrieving ThermoDoc documents:   0%|          | 0/42 [00:00<?, ?it/s]

ReTcVW	 0.1614

Retrieving ThermoDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

ReTcW2	 0.1202
same?
ReTcW2	 0.1266
same?
ReTcW2	 0.0951

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrReTc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re2Tc2Zr2	 0.0501
same?
Re2Tc2Zr2	 0.0501
same?
ReTc3Zr2	 0.0432

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2ReTc3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Ti3Re). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

ReTi3	 0.0670

Retrieving ThermoDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (YTiRe4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re4TiY	 0.1768

Retrieving ThermoDoc documents:   0%|          | 0/34 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrTiRe4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re4TiZr	 0.1457

Retrieving ThermoDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (VRe3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re3V	 0.1558

Retrieving ThermoDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

ReW	 0.1454

Retrieving ThermoDoc documents:   0%|          | 0/15 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (ZrRe2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Re4Zr2	 0.0687

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc2RuRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

RhRuTc2	 0.1696

Retrieving ThermoDoc documents:   0%|          | 0/38 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr2ScRh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

RhScZr2	 0.1418

Retrieving ThermoDoc documents:   0%|          | 0/11 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc3Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

RhTc3	 0.1730

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr7Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

RhZr7	 0.0895
same?
RhZr5	 0.0509

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr5Rh). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/69 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (SiTcRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ru2SiTc	 0.0436

Retrieving ThermoDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaRu3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ru3Ta	 0.0683

Retrieving ThermoDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TaTiRu2). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ru2TaTi	 0.0722

Retrieving ThermoDoc documents:   0%|          | 0/8 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Tc3Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

RuTc3	 0.1466
same?
Ru2Tc2	 0.1368

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TcRu). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

same?
RuTc3	 0.0154
same?
RuTc3	 0.0739

Retrieving ThermoDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (YZrRu4). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Ru4YZr	 0.1151

Retrieving ThermoDoc documents:   0%|          | 0/12 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (Zr5Ru). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

RuZr5	 0.0573

Retrieving ThermoDoc documents:   0%|          | 0/14 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiTc5). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Tc5Ti	 0.1110
same?
Tc5Ti	 0.1111
same?
Tc3Ti	 0.1214

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiTc3). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

Retrieving ThermoDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/pymatgen/entries/compatibility.py:1156: UserWarning: Failed to guess oxidation states for Entry None (TiV2Tc). Assigning anion correction to only the most electronegative atom.
  warnings.warn(

TcTiV2	 0.1710
same?
TcTiV2	 0.1628

Retrieving ThermoDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

TiV2W	 0.1455

Retrieving ThermoDoc documents:   0%|          | 0/13 [00:00<?, ?it/s]

V3W	 0.0967

In [23]:
df_mp = pd.DataFrame(eahs)
df_mp.index = inds
df_mp.columns = ['mp_eah']
df['mp_eah_cor']=df_mp.mp_eah

In [33]:
a = d.structure_dict.values[0]

In [34]:
a

{'numbers': array([41, 41, 41, 41, 41, 41, 31, 77]),
 'positions': array([[2.78686766, 0.48026596, 4.37493329],
        [4.08682716, 3.03741986, 3.11765864],
        [2.78688406, 0.48027487, 1.86033163],
        [0.22995534, 4.33722139, 0.56054841],
        [0.22994301, 1.7375565 , 0.56054002],
        [1.48718837, 3.03742626, 3.11765009],
        [2.78734748, 3.03758075, 0.56059279],
        [0.22965109, 0.48031164, 3.11769476]]),
 'cell': array([[ 5.11424138e+00, -1.41722832e-05,  2.35496279e-05],
        [ 2.86866917e-05,  5.11425861e+00,  2.24299449e-05],
        [-3.06616880e-05, -2.98893142e-05,  5.11428021e+00]]),
 'pbc': array([ True,  True,  True])}

In [30]:
def to_dict(df):
    return df.structure.todict()
df['structure_dict'] = df.apply(to_dict,axis = 1)

In [ ]:
d = df.loc[df.tcad_final>20].loc[df.mp_eah_cor<=.08].loc[~df.formula.str.contains('Tc')].loc[~df.formula.str.contains('Cr')].loc[~df.formula.str.contains('Be')]
# d = d.loc[~df.formula.str.contains('Mn')].loc[~df.formula.str.contains('Fe')].loc[~df.formula.str.contains('Co')].loc[~df.formula.str.contains('Ni')]
# d = d.loc[~df.formula.str.contains('Ni')].loc[~df.formula.str.contains('Cu')].loc[~df.formula.str.contains('Zn')].loc[~df.formula.str.contains('O')]
# d = d.loc[d.par_el!='mp_data'].loc[d.par_el!='alex']

In [40]:
df.sort_values('tcad_final',inplace=True,ascending=False)

In [44]:
df[['formula','tcad_final','mp_eah_cor','sgn','structure_dict']].to_csv('diff_model.csv')#.loc[df.mp_eah_cor<=.08]

In [28]:
df.loc[df.mp_eah_cor<0.05].loc[df.tcad_final>15][['formula','sgn','lamb_final','tcad_final','mp_eah','mp_eah_cor','a2f']]

,formula,sgn,lamb_final,tcad_final,mp_eah,mp_eah_cor,a2f
82587,AlNb6Rh,200,1.281002,19.078750,0.049440,0.049495,"[1.07518e-08, 2.92828e-07, 1.35804e-06, 3.7292..."
51254,AuNb6Pt,200,1.438564,15.863476,-0.000736,-0.000736,"[1.30576e-07, 3.52763e-06, 1.63335e-05, 4.4821..."
122437,Be4RhTa,216,0.943644,20.496278,0.035234,0.035249,"[1.94779e-09, 5.29475e-08, 2.4546e-07, 6.73934..."
11718,GaIrNb6,200,1.420186,24.785654,0.021650,0.021724,"[5.8044e-09, 1.57871e-07, 7.31958e-07, 2.00975..."
173836,GaMo6Re,200,1.002289,17.712669,0.008487,0.009526,"[5.96666e-09, 1.62e-07, 7.50838e-07, 2.06129e-..."
168623,GeIrMo4Nb2,6,1.203312,17.795314,0.048025,0.049932,"[1.31645e-08, 3.58503e-07, 1.66261e-06, 4.5655..."
72557,H2Mo2,4,0.914978,16.703584,0.006163,-0.083324,"[1.83722e-09, 4.96086e-08, 2.29673e-07, 6.3022..."
167606,H4Mo4,59,0.921236,16.783657,0.005719,-0.083768,"[1.54106e-09, 4.16872e-08, 1.93069e-07, 5.2986..."
580,H2Mo2,71,0.935820,17.241033,0.005679,-0.083808,"[1.38945e-09, 3.83173e-08, 1.78154e-07, 4.8975..."
53971,H2Mo2,11,0.928837,17.066853,0.005988,-0.083499,"[1.47609e-09, 3.98628e-08, 1.84558e-07, 5.0643..."
49038,HMoNNb,6,0.825882,15.491172,0.125916,-0.009069,"[7.42831e-10, 2.0649e-08, 9.61611e-08, 2.64534..."
11140,Mo2NOs,160,0.994948,18.176342,0.059860,-0.030378,"[3.43826e-09, 9.33681e-08, 4.32759e-07, 1.1880..."
9894,Mo3N2Tc,6,1.030516,19.921671,0.123370,0.003043,"[3.18467e-09, 8.65245e-08, 4.0108e-07, 1.10116..."
149313,Mo5NbOsRu,25,1.250162,19.290484,0.003758,0.003768,"[1.02386e-08, 2.76976e-07, 1.28279e-06, 3.5205..."
42188,MoNbTaTi,99,1.795266,16.831730,0.048182,0.048298,"[6.84726e-06, 0.000186511, 0.000865001, 0.0023..."
122857,MoNbTc2,10,0.983763,15.272179,0.039365,0.039803,"[2.19669e-09, 5.9385e-08, 2.75e-07, 7.5468e-07..."
13944,Mo2NbTc3,65,1.307707,19.933211,-0.011938,-0.011640,"[1.49713e-08, 4.06602e-07, 1.88464e-06, 5.1740..."
20657,Mo2NbTc3,164,1.417800,21.872874,-0.008514,-0.008216,"[4.71607e-09, 1.29729e-07, 6.02842e-07, 1.6568..."
37068,Mo5OsRhW,1,1.471705,18.077076,0.018439,0.020636,"[4.37408e-08, 1.20632e-06, 5.60887e-06, 1.5419..."
82253,Mo4Tc2,12,0.937468,15.111540,0.008656,0.008672,"[2.24299e-09, 6.27297e-08, 2.92484e-07, 8.0502..."
1695,Nb6Pt2,223,1.316275,16.347734,-0.011117,-0.011117,"[3.40964e-08, 9.29866e-07, 4.3136e-06, 1.18467..."
538,Nb2Tc4,227,1.383863,19.076493,0.025132,0.025711,"[1.78575e-08, 4.82686e-07, 2.23515e-06, 6.1338..."
146872,ReTc3Zr2,166,1.355299,19.143124,0.043219,0.043221,"[2.31442e-08, 6.29152e-07, 2.91671e-06, 8.0081..."

In [28]:
df.loc[df.mp_eah<0.05].loc[df.tcad_final>15][['formula','sgn','lamb_final','tcad_final','mp_eah','a2f']]

,formula,sgn,lamb_final,tcad_final,mp_eah,a2f
11718,GaIrNb6,200,1.420186,23.942819,0.021650,"[5.8044e-09, 1.57871e-07, 7.31958e-07, 2.00975..."
20657,Mo2NbTc3,164,1.417800,21.121194,-0.008514,"[4.71607e-09, 1.29729e-07, 6.02842e-07, 1.6568..."
122437,Be4RhTa,216,0.943644,19.411302,0.035234,"[1.94779e-09, 5.29475e-08, 2.4546e-07, 6.73934..."
13944,Mo2NbTc3,65,1.307707,19.196684,-0.011938,"[1.49713e-08, 4.06602e-07, 1.88464e-06, 5.1740..."
149313,Mo5NbOsRu,25,1.250162,18.546723,0.003758,"[1.02386e-08, 2.76976e-07, 1.28279e-06, 3.5205..."
146872,ReTc3Zr2,166,1.355299,18.454703,0.043219,"[2.31442e-08, 6.29152e-07, 2.91671e-06, 8.0081..."
538,Nb2Tc4,227,1.383863,18.397585,0.025132,"[1.78575e-08, 4.82686e-07, 2.23515e-06, 6.1338..."
82587,AlNb6Rh,200,1.281002,18.360329,0.049440,"[1.07518e-08, 2.92828e-07, 1.35804e-06, 3.7292..."
37068,Mo5OsRhW,1,1.471705,17.453285,0.018439,"[4.37408e-08, 1.20632e-06, 5.60887e-06, 1.5419..."
168623,GeIrMo4Nb2,6,1.203312,17.081529,0.048025,"[1.31645e-08, 3.58503e-07, 1.66261e-06, 4.5655..."
173836,GaMo6Re,200,1.002289,16.852418,0.008487,"[5.96666e-09, 1.62e-07, 7.50838e-07, 2.06129e-..."
580,H2Mo2,71,0.935820,16.317380,0.005679,"[1.38945e-09, 3.83173e-08, 1.78154e-07, 4.8975..."
42188,MoNbTaTi,99,1.795266,16.282781,0.048182,"[6.84726e-06, 0.000186511, 0.000865001, 0.0023..."
53971,H2Mo2,11,0.928837,16.144511,0.005988,"[1.47609e-09, 3.98628e-08, 1.84558e-07, 5.0643..."
167606,H4Mo4,59,0.921236,15.867632,0.005719,"[1.54106e-09, 4.16872e-08, 1.93069e-07, 5.2986..."
72557,H2Mo2,4,0.914978,15.784445,0.006163,"[1.83722e-09, 4.96086e-08, 2.29673e-07, 6.3022..."
1695,Nb6Pt2,223,1.316275,15.735062,-0.011117,"[3.40964e-08, 9.29866e-07, 4.3136e-06, 1.18467..."
51254,AuNb6Pt,200,1.438564,15.300722,-0.000736,"[1.30576e-07, 3.52763e-06, 1.63335e-05, 4.4821..."

In [12]:
df[['formula','sgn','lamb_final','tcad_final','mp_eah','a2f']]

,formula,sgn,lamb_final,tcad_final,mp_eah,a2f
872,GaNb6Si,200,2.409011,36.424072,0.092368,"[7.81282e-08, 2.15002e-06, 9.99368e-06, 2.7470..."
7807,Re2Ru2,123,2.639579,31.754612,0.139794,"[2.83639e-09, 7.66565e-08, 3.5496e-07, 9.7409e..."
101256,Nb5Si2V,1,1.703267,29.341672,0.121486,"[9.60667e-09, 2.76836e-07, 1.29858e-06, 3.5834..."
56153,HNNb6Sn2,225,2.587249,28.157370,0.195628,"[1.17567e-07, 3.25363e-06, 1.51378e-05, 4.1626..."
5378,GaNb6Zn,200,6.720966,28.148405,0.107763,"[0.000143483, 0.00387421, 0.0179363, 0.0492174..."
...,...,...,...,...,...,...
78354,IrReRuW,47,0.447737,1.602397,0.059836,"[1.24174e-09, 3.35369e-08, 1.55273e-07, 4.2607..."
112615,Nb5Ru,123,0.434899,1.435584,0.017927,"[5.62511e-09, 1.57604e-07, 7.35157e-07, 2.0238..."
19670,Ir3Nb2W,10,0.443354,1.415766,0.022179,"[3.44841e-09, 9.51358e-08, 4.42411e-07, 1.2163..."
199225,HfIrTa2,25,0.430950,1.027123,0.112113,"[3.81501e-09, 1.03135e-07, 4.77597e-07, 1.3106..."
856,HfIrMoNb,216,0.398888,0.630369,0.009088,"[8.8122e-09, 2.38842e-07, 1.10661e-06, 3.03755..."

In [13]:
len(d)/len(df)

0.9078694817658349

In [15]:

df.dropna(axis=0,inplace=True)
df.to_pickle(f'pkl_files/df_a2f_{par_el}.pkl')

In [16]:
df

,dirs,Structure,final_E,PBE,GLLB-SC,HSE,SCAN,E_form,is_metal,formula,...,tc_cpd,tcad_cpd,freq_a2f,a2f,lamb_final,w2_final,wlog_final,tc_final,tcad_final,nelements
872,tc10_w2,"[[2.90378492 0.77667463 1.34814213] Nb, [0.365...",-71.214394,-0.009433,0.423296,-0.009309,0.081636,-0.234222,True,GaNb6Si,...,13.782114,14.760680,"[0.04513729510632628, 0.1451387313895385, 0.24...","[7.81282e-08, 2.15002e-06, 9.99368e-06, 2.7470...",2.409011,217.437125,181.816830,29.342537,36.424072,3
7807,tc10_w2,"[[0.34196889 2.16212195 2.87507346] Re, [2.252...",-43.804409,-0.008724,0.627173,-0.007106,0.133005,-0.066947,True,Re2Ru2,...,8.203227,8.506391,"[0.049924322174720495, 0.14992521423020777, 0....","[2.83639e-09, 7.66565e-08, 3.5496e-07, 9.7409e...",2.639579,162.815345,153.753357,26.046834,31.754612,2
101256,tc15_w2,"[[4.12043419 4.81051645 0.07742249] Nb, [1.591...",-72.877380,-0.008744,0.298951,-0.008966,0.106423,-0.319320,True,Nb5Si2V,...,10.375791,10.897899,"[0.04428517054603317, 0.14428565443072677, 0.2...","[9.60667e-09, 2.76836e-07, 1.29858e-06, 3.5834...",1.703267,231.156650,202.067375,25.766918,29.341672,3
56153,tc10_w2,"[[3.29710942 0.96038914 4.64531168] Nb, [3.250...",-84.459213,-0.009798,0.771711,-0.007947,0.218538,-0.521153,True,HNNb6Sn2,...,11.454735,12.364384,"[0.0443680292171522, 0.14436864915877703, 0.24...","[1.17567e-07, 3.25363e-06, 1.51378e-05, 4.1626...",2.587249,185.006843,126.302315,21.178923,28.157370,4
5378,tc10_w2,"[[1.71599546 0.41171237 1.47503818] Nb, [1.702...",-65.616768,-0.008630,0.427390,-0.009135,0.201362,-0.133445,True,GaNb6Zn,...,17.198797,19.163834,"[0.04799544306067363, 0.14799592694536726, 0.2...","[0.000143483, 0.00387421, 0.0179363, 0.0492174...",6.720966,98.711696,51.560445,11.777536,28.148405,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133470,tc15_w2,"[[1.31210972 1.33144627 4.77798832] Tc, [3.252...",-41.443390,-0.007350,0.484258,-0.007372,0.545039,-0.069232,True,CMo2Tc,...,9.942675,10.492609,"[0.049713161817451626, 0.14971432598680137, 0....","[3.27177e-09, 8.85729e-08, 4.10278e-07, 1.1260...",0.587454,312.075116,233.043580,4.995394,5.149593,3
49806,tc10_w2,"[[1.53723404 0.59014326 3.17280728] Hf, [1.538...",-30.636829,-0.007102,0.568606,-0.007532,0.059646,-0.120390,True,Hf2HgNb,...,5.077127,5.285684,"[0.04828007416080667, 0.1482802859316378, 0.24...","[2.05465e-08, 5.5997e-07, 2.59735e-06, 7.13289...",0.719315,161.981893,133.323412,4.949118,5.147089,3
85339,tc10_w2,"[[3.56034587 0.84134195 5.1662875 ] Ti, [1.314...",-61.209442,-0.010392,0.349277,-0.009530,0.033407,-0.031504,True,Nb4ReTi,...,5.334860,5.492028,"[0.04740413963754831, 0.14740543986382929, 0.2...","[3.90422e-09, 1.06414e-07, 4.93597e-07, 1.3555...",0.600064,245.877130,217.645211,4.979670,5.120639,3
146616,tc15_w2,"[[0.77557202 0.86734 2.84897693] Nb, [0.303...",-40.064507,0.073553,0.525314,0.052077,0.385574,-0.506016,True,Ir2Nb2,...,7.189223,7.494024,"[0.04990949196921643, 0.1499102479677725, 0.24...","[8.09089e-09, 2.18561e-07, 1.01196e-06, 2.7769...",0.644118,200.805972,175.451884,4.921661,5.079045,2
28533,tc10_w2,"[[1.27559311 3.53917363 3.19965609] Cr, [0.926...",-37.431728,-0.007361,0.282325,-0.006581,0.130370,-0.150567,True,Cr2Ir2,...,6.664773,6.904562,"[0.04988677046170103, 0.1498871182894634, 0.24...","[5.29872e-09, 1.43145e-07, 6.62781e-07, 1.8187...",0.615239,250.410116,198.239714,4.884926,5.042043,2

In [26]:
df.loc[[1608,1664,1601]][['formula','tcad_final','mp_eah']].head()

KeyError: "None of [Index([1608, 1664, 1601], dtype='int64')] are in the [index]"

In [ ]:
# df['tcad_final'] = df.tcad_final.values.real.astype(np.longdouble)

In [ ]:
# ind = 176565
# plt.plot(df.loc[ind].freq_a2f,np.asarray(df.loc[ind].a2f),'--',label='a2F')
# # plt.plot(df.loc[ind].freq_a2f_2,np.asarray(df.loc[ind].a2f_2),'--',label='a2F_2')

# plt.plot(df.loc[ind].freq,np.asarray(df.loc[ind].phdos)/max(df.loc[ind].phdos),':',label='PhDOS')
# plt.plot(Freq_final,np.asarray(df.loc[ind].pred_avg)/max(df.loc[ind].pred_avg),'-',label='pred a2f')

# plt.xlabel('Freq (meV)')
# plt.ylabel('Normalized')
# plt.title(df.loc[ind].formula)
# # plt.xlim(0,26)
# plt.legend()

In [ ]:
# ind = 1643
# plt.plot(df.loc[ind].freq_a2f,np.asarray(df.loc[ind].a2f)/max(df.loc[ind].a2f),'--',label='a2F')

# plt.plot(df.loc[ind].freq,np.asarray(df.loc[ind].phdos)/max(df.loc[ind].phdos),':',label='PhDOS')
# plt.plot(Freq_final,np.asarray(df.loc[ind].pred_avg)/max(df.loc[ind].pred_avg),'-',label='pred a2f')

# plt.xlabel('Freq (meV)')
# plt.ylabel('Normalized')
# plt.title(df.loc[ind].formula)
# # plt.ylim(0,0.12)
# plt.legend()

In [ ]:
# plt.plot(df.loc[ind].freq_a2f,np.asarray(df.loc[ind].a2f),'--',label='a2F')

# plt.plot(Freq_final,np.asarray(df.loc[ind].pred_avg),'-',label='pred a2f')

# plt.xlabel('Freq (meV)')
# plt.ylabel('Normalized')
# plt.title(df.loc[ind].formula)
# # plt.ylim(0,0.12)
# plt.legend()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
# d.set_index('formula')

In [ ]:
d = df[['sgn','formula','eah','tcad','tcad_cpd','tcad_final']]
d = d.set_index('formula')
d.sort_values('tcad_final', ascending = False,inplace=True)

In [ ]:
d.loc[d.sgn==194]

In [ ]:
d.head(20)#.loc[d.eah<=0.1]

In [ ]:
# d = df[['mp_id', 'parent_formula', 'sgn', 'formula','dyn_stable','m3gnet_eah','mp_eah','tcad_m3gnet','tcad_mp','tcad_cpd','tcad_final','natoms']]
# df.sort_values('tcad_final', ascending = False)

In [ ]:
# df['mp_eah'] = df.eah

In [ ]:
df.shape

In [ ]:
df.loc[df.tcad_final > 5][['formula','tcad_final']]#.shape

In [ ]:
df.head(7)

In [ ]:
# ### plt.plot(d.tcad_final.values,d.tcad_cpd.values,'.')
# plt.ylim([5,20])
# plt.xlim([5,20])
# plt.plot([5,20],[5,20])

In [26]:
plt.plot(d.tcad_final.values,d.tcad_cpd.values,'.')
plt.ylim([5,20])
plt.xlim([5,20])
plt.plot([5,20],[5,20])

NameError: name 'd' is not defined

In [43]:
ind = 1655
# plt.plot(df.loc[ind].freq_a2f,np.asarray(df.loc[ind].a2f)/max(df.loc[ind].a2f),'--',label='a2F')
plt.plot(df.loc[ind].freq_a2f,np.asarray(df.loc[ind].a2f),'--',label='a2F')

plt.plot(df.loc[ind].freq,np.asarray(df.loc[ind].phdos)/max(df.loc[ind].phdos),':',label='PhDOS')
# plt.plot(df.loc[ind].freq_a2f,np.asarray(df.loc[ind].pred_avg)/max(df.loc[ind].pred_avg),'-',label='pred a2f')

plt.xlabel('Freq (meV)')
plt.ylabel('a2F')
plt.title(df.loc[ind].formula)
plt.legend()

KeyError: 1655