In [3]:
# from pymatgen.ext.matproj import MPRester
from mp_api.client import MPRester
import pandas as pd
from pymatgen.core import Structure, Element, PeriodicSite
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from tqdm import tqdm
# import matgl
# from matgl.ext.ase import PESCalculator, MolecularDynamics, Relaxer
from collections import defaultdict

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/paramiko/transport.py:253: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,

In [4]:
elements = [
     'H','Li', 'Be', 'B','C','N','O','F', 'Na', 'Mg', 'Al', 'Si','P','S','Cl', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 
    'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As','Se','Br','Rb', 'Sr', 'Y', 'Zr', 
    'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te','I', 'Cs', 
    'Ba', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At']

# nin = ['B','Be','C','Ge','Li','Mg','Si','Na','N']

In [5]:
par_el = 'Li'

In [23]:
mpr = MPRester(API_KEY)

In [24]:
mpr.summary.search?

Signature:
mpr.summary.search(
    band_gap: 'tuple[float, float] | None' = None,
    chemsys: 'str | list[str] | None' = None,
    crystal_system: 'CrystalSystem | None' = None,
    density: 'tuple[float, float] | None' = None,
    deprecated: 'bool | None' = None,
    e_electronic: 'tuple[float, float] | None' = None,
    e_ionic: 'tuple[float, float] | None' = None,
    e_total: 'tuple[float, float] | None' = None,
    efermi: 'tuple[float, float] | None' = None,
    elastic_anisotropy: 'tuple[float, float] | None' = None,
    elements: 'list[str] | None' = None,
    energy_above_hull: 'tuple[float, float] | None' = None,
    equilibrium_reaction_energy: 'tuple[float, float] | None' = None,
    exclude_elements: 'list[str] | None' = None,
    formation_energy: 'tuple[float, float] | None' = None,
    formula: 'str | list[str] | None' = None,
    g_reuss: 'tuple[float, float] | None' = None,
    g_voigt: 'tuple[float, float] | None' = None,
    g_vrh: 'tuple[float, float] | None' = None,
    has_props: 'list[HasProps] | list[str] | None' = None,
    has_reconstructed: 'bool | None' = None,
    is_gap_direct: 'bool | None' = None,
    is_metal: 'bool | None' = None,
    is_stable: 'bool | None' = None,
    k_reuss: 'tuple[float, float] | None' = None,
    k_voigt: 'tuple[float, float] | None' = None,
    k_vrh: 'tuple[float, float] | None' = None,
    magnetic_ordering: 'Ordering | None' = None,
    material_ids: 'str | list[str] | None' = None,
    n: 'tuple[float, float] | None' = None,
    num_elements: 'tuple[int, int] | None' = None,
    num_sites: 'tuple[int, int] | None' = None,
    num_magnetic_sites: 'tuple[int, int] | None' = None,
    num_unique_magnetic_sites: 'tuple[int, int] | None' = None,
    piezoelectric_modulus: 'tuple[float, float] | None' = None,
    poisson_ratio: 'tuple[float, float] | None' = None,
    possible_species: 'list[str] | None' = None,
    shape_factor: 'tuple[float, float] | None' = None,
    spacegroup_number: 'int | None' = None,
    spacegroup_symbol: 'str | None' = None,
    surface_energy_anisotropy: 'tuple[float, float] | None' = None,
    theoretical: 'bool | None' = None,
    total_energy: 'tuple[float, float] | None' = None,
    total_magnetization: 'tuple[float, float] | None' = None,
    total_magnetization_normalized_formula_units: 'tuple[float, float] | None' = None,
    total_magnetization_normalized_vol: 'tuple[float, float] | None' = None,
    uncorrected_energy: 'tuple[float, float] | None' = None,
    volume: 'tuple[float, float] | None' = None,
    weighted_surface_energy: 'tuple[float, float] | None' = None,
    weighted_work_function: 'tuple[float, float] | None' = None,
    include_gnome: 'bool' = True,
    num_chunks: 'int | None' = None,
    chunk_size: 'int' = 1000,
    all_fields: 'bool' = True,
    fields: 'list[str] | None' = None,
) -> 'list[SummaryDoc] | list[dict]'
Docstring:
Query core data using a variety of search criteria.

Arguments:
    band_gap (Tuple[float,float]): Minimum and maximum band gap in eV to consider.
    chemsys (str, List[str]): A chemical system or list of chemical systems
        (e.g., Li-Fe-O, Si-*, [Si-O, Li-Fe-P]).
    crystal_system (CrystalSystem): Crystal system of material.
    density (Tuple[float,float]): Minimum and maximum density to consider.
    deprecated (bool): Whether the material is tagged as deprecated.
    e_electronic (Tuple[float,float]): Minimum and maximum electronic dielectric constant to consider.
    e_ionic (Tuple[float,float]): Minimum and maximum ionic dielectric constant to consider.
    e_total (Tuple[float,float]): Minimum and maximum total dielectric constant to consider.
    efermi (Tuple[float,float]): Minimum and maximum fermi energy in eV to consider.
    elastic_anisotropy (Tuple[float,float]): Minimum and maximum value to consider for the elastic anisotropy.
    elements (List[str]): A list of elements.
    energy_above_hull (Tuple[int,int]): Minimum and maximum energy above the hull in eV/atom to consider.
    equilibrium_reaction_energy (Tuple[float,float]): Minimum and maximum equilibrium reaction energy in
        eV/atom to consider.
    exclude_elements (List(str)): List of elements to exclude.
    formation_energy (Tuple[int,int]): Minimum and maximum formation energy in eV/atom to consider.
    formula (str, List[str]): A formula including anonymized formula
        or wild cards (e.g., Fe2O3, ABO3, Si*). A list of chemical formulas can also be passed
        (e.g., [Fe2O3, ABO3]).
    g_reuss (Tuple[float,float]): Minimum and maximum value in GPa to consider for the Reuss average
        of the shear modulus.
    g_voigt (Tuple[float,float]): Minimum and maximum value in GPa to consider for the Voigt average
        of the shear modulus.
    g_vrh (Tuple[float,float]): Minimum and maximum value in GPa to consider for the Voigt-Reuss-Hill
        average of the shear modulus.
    has_props: (List[HasProps], List[str]): The calculated properties available for the material.
    has_reconstructed (bool): Whether the entry has any reconstructed surfaces.
    is_gap_direct (bool): Whether the material has a direct band gap.
    is_metal (bool): Whether the material is considered a metal.
    is_stable (bool): Whether the material lies on the convex energy hull.
    k_reuss (Tuple[float,float]): Minimum and maximum value in GPa to consider for the Reuss average
        of the bulk modulus.
    k_voigt (Tuple[float,float]): Minimum and maximum value in GPa to consider for the Voigt average
        of the bulk modulus.
    k_vrh (Tuple[float,float]): Minimum and maximum value in GPa to consider for the Voigt-Reuss-Hill
        average of the bulk modulus.
    magnetic_ordering (Ordering): Magnetic ordering of the material.
    material_ids (str, List[str]): A single Material ID string or list of strings
        (e.g., mp-149, [mp-149, mp-13]).
    n (Tuple[float,float]): Minimum and maximum refractive index to consider.
    num_elements (Tuple[int,int]): Minimum and maximum number of elements to consider.
    num_sites (Tuple[int,int]): Minimum and maximum number of sites to consider.
    num_magnetic_sites (Tuple[int,int]): Minimum and maximum number of magnetic sites to consider.
    num_unique_magnetic_sites (Tuple[int,int]): Minimum and maximum number of unique magnetic sites to consider.
    piezoelectric_modulus (Tuple[float,float]): Minimum and maximum piezoelectric modulus to consider.
    poisson_ratio (Tuple[float,float]): Minimum and maximum value to consider for Poisson's ratio.
    possible_species (List(str)): List of element symbols appended with oxidation states. (e.g. Cr2+,O2-)
    shape_factor (Tuple[float,float]): Minimum and maximum shape factor values to consider.
    spacegroup_number (int): Space group number of material.
    spacegroup_symbol (str): Space group symbol of the material in international short symbol notation.
    surface_energy_anisotropy (Tuple[float,float]): Minimum and maximum surface energy anisotropy values
        to consider.
    theoretical: (bool): Whether the material is theoretical.
    total_energy (Tuple[int,int]): Minimum and maximum corrected total energy in eV/atom to consider.
    total_magnetization (Tuple[float,float]): Minimum and maximum total magnetization values to consider.
    total_magnetization_normalized_formula_units (Tuple[float,float]): Minimum and maximum total magnetization
        values normalized by formula units to consider.
    total_magnetization_normalized_vol (Tuple[float,float]): Minimum and maximum total magnetization values
        normalized by volume to consider.
    uncorrected_energy (Tuple[int,int]): Minimum and maximum uncorrected total energy in eV/atom to consider.
    volume (Tuple[float,float]): Minimum and maximum volume to consider.
    weighted_surface_energy (Tuple[float,float]): Minimum and maximum weighted surface energy
        in J/m² to consider.
    weighted_work_function (Tuple[float,float]): Minimum and maximum weighted work function in eV to consider.
    include_gnome (bool): whether to include materials from GNoMe dataset
    num_chunks (int): Maximum number of chunks of data to yield. None will yield all possible.
    chunk_size (int): Number of data entries per chunk.
    all_fields (bool): Whether to return all fields in the document. Defaults to True.
    fields (List[str]): List of fields in SummaryDoc to return data for.
        Default is material_id if all_fields is False.

Returns:
    ([SummaryDoc], [dict]) List of SummaryDoc documents or dictionaries.
File:      /blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/mp_api/client/routes/materials/summary.py
Type:      method

In [29]:
from pymatgen.io.ase import AseAtomsAdaptor

In [36]:
API_KEY = '1QQt0BLqboJqxKBPocZ53qVRLn1MxBnc'
data = []

with MPRester(API_KEY) as mpr:
    results = mpr.summary.search(
        elements=["Li"],
        energy_above_hull=(-10, 0.1),
        is_metal=True,
        theoretical=False,
        num_elements=(2, 40),
        fields=[
            "material_id", "formula_pretty", "energy_above_hull",
            "formation_energy_per_atom", "band_gap", "density",
            "nsites", "is_magnetic", "structure"
        ],
        deprecated=False,
        chunk_size=100
    )

    for doc in results:
        # Convert pymatgen Structure to ASE Atoms
        ase_atoms = AseAtomsAdaptor.get_atoms(doc.structure)

        data.append({
            "material_id": doc.material_id,
            "formula": doc.formula_pretty,
            "energy_above_hull": doc.energy_above_hull,
            "formation_energy_per_atom": doc.formation_energy_per_atom,
            "band_gap": doc.band_gap,
            "density": doc.density,
            "nsites": doc.nsites,
            "is_magnetic": doc.is_magnetic,
            "ase_atoms": ase_atoms,
            "structure": doc.structure
        })

# Create and save the DataFrame
df = pd.DataFrame(data)

/scratch/local/66163397/ipykernel_3277739/1703154573.py:5: DeprecationWarning: Accessing summary data through MPRester.summary is deprecated. Please use MPRester.materials.summary instead.
  results = mpr.summary.search(

Retrieving SummaryDoc documents:   0%|          | 0/464 [00:00<?, ?it/s]

In [37]:
df.to_pickle('test.pkl')

In [38]:
# with MPRester('7Hz5tMiUiiCuu6Jvp5K') as mpr:
#     # d= mpr.query(material_ids=["mp-11557"])
#     # data = mpr.query(criteria={"elements": {"$in": elements,"$nin":nin},"theoretical":False,"nsites":{"$lte":12}}, properties=["original_task_id","e_above_hull", "pretty_formula", 'structure','spacegroup.number','theoretical','nsites','band_gap','nelements'])
#     # data = mpr.query(criteria={"elements": {"$in": elements},"theoretical":False,"nsites":{"$lte":12}}, properties=["original_task_id","e_above_hull", "pretty_formula", 'structure','spacegroup.number','theoretical','nsites','band_gap','nelements'])

In [39]:
# df = pd.DataFrame(data)
# df = df.set_index(keys='original_task_id')
df = df.sort_values('energy_above_hull')

In [40]:
df.head()

,material_id,formula,energy_above_hull,formation_energy_per_atom,band_gap,density,nsites,is_magnetic,ase_atoms,structure
0,mp-569073,LiSn,0.0,-0.325867,0.0,5.092957,6,False,"(Atom('Li', [1.56926692, 3.6093226238413156, 4...","[[1.56926692 3.60932262 4.30354952] Li, [ 1.56..."
273,mp-1078460,Li2CuSn2,0.0,-0.310138,0.0,5.568733,10,False,"(Atom('Li', [0.0, 0.0, 15.977317291287308], ma...","[[ 0. 0. 15.97731729] Li, [0...."
271,mp-644389,Li2H2Pd,0.0,-0.477492,0.0,4.185945,5,False,"(Atom('Li', [0.0, 0.0, 6.604963247987355], mag...","[[0. 0. 6.60496325] Li, [0. ..."
270,mp-7661,Li2RhF6,0.0,-2.415817,0.0,4.045317,18,True,"(Atom('Li', [0.0, 0.0, 5.999554909710947], mag...","[[0. 0. 5.99955491] Li, [2.293..."
269,mp-555112,Li2CrF6,0.0,-2.946233,0.0,3.308625,18,True,"(Atom('Li', [-0.0011880286579049, 0.0416569935...",[[-1.18802866e-03 4.16569935e-02 2.93561748e...

## new criteria

In [41]:
def get_elements(df):
    elements = df.structure.composition.elements
    elements = [ele.symbol for ele in elements]
    return elements
df['elements'] = df.apply(get_elements,axis=1)

In [42]:
lanthanides = [
    "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", 
    "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu"
]
nin = ['B','Be','C','Ge','Li','Mg','Si','Na','N']

actinides = [
    "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", 
    "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr"
]

In [43]:
# df = df[~df['elements'].apply(lambda x: any(elem in nin for elem in x))]
df = df[~df['elements'].apply(lambda x: any(elem in lanthanides for elem in x))]
df = df[~df['elements'].apply(lambda x: any(elem in actinides for elem in x))]

df.shape

(359, 11)

In [44]:
df

,material_id,formula,energy_above_hull,formation_energy_per_atom,band_gap,density,nsites,is_magnetic,ase_atoms,structure,elements
0,mp-569073,LiSn,0.000000,-0.325867,0.0,5.092957,6,False,"(Atom('Li', [1.56926692, 3.6093226238413156, 4...","[[1.56926692 3.60932262 4.30354952] Li, [ 1.56...","[Li, Sn]"
273,mp-1078460,Li2CuSn2,0.000000,-0.310138,0.0,5.568733,10,False,"(Atom('Li', [0.0, 0.0, 15.977317291287308], ma...","[[ 0. 0. 15.97731729] Li, [0....","[Li, Cu, Sn]"
271,mp-644389,Li2H2Pd,0.000000,-0.477492,0.0,4.185945,5,False,"(Atom('Li', [0.0, 0.0, 6.604963247987355], mag...","[[0. 0. 6.60496325] Li, [0. ...","[Li, H, Pd]"
270,mp-7661,Li2RhF6,0.000000,-2.415817,0.0,4.045317,18,True,"(Atom('Li', [0.0, 0.0, 5.999554909710947], mag...","[[0. 0. 5.99955491] Li, [2.293...","[Li, Rh, F]"
269,mp-555112,Li2CrF6,0.000000,-2.946233,0.0,3.308625,18,True,"(Atom('Li', [-0.0011880286579049, 0.0416569935...",[[-1.18802866e-03 4.16569935e-02 2.93561748e...,"[Li, Cr, F]"
...,...,...,...,...,...,...,...,...,...,...,...
32,mp-1191883,LiTl,0.090757,-0.164843,0.0,7.627105,24,False,"(Atom('Li', [-3.174752500000006, 3.70010579093...","[[-3.1747525 3.70010579 6.09974025] Li, [-3...","[Li, Tl]"
266,mp-555660,Li2V6O13,0.091119,-2.427299,0.0,3.561613,21,True,"(Atom('Li', [0.0005692254239999058, 1.08788709...",[[5.69225424e-04 1.08788710e+00 1.31250321e+00...,"[Li, V, O]"
248,mp-21013,Cs2LiFe(CN)6,0.096898,-0.260311,0.0,2.670388,16,True,"(Atom('Cs', [2.660784, 2.660784, 2.660784], ma...","[[2.660784 2.660784 2.660784] Cs, [7.982352 7....","[Cs, Li, Fe, C, N]"
337,mp-504760,Li10Pb3,0.098659,-0.221232,0.0,4.441533,52,False,"(Atom('Li', [1.1269172805749998, 1.12691728057...","[[1.12691728 1.12691728 1.12691728] Li, [8.983...","[Li, Pb]"
74,mp-27683,LiSnS2,0.099763,-0.922163,0.0,3.928458,4,False,"(Atom('Li', [0.0, 0.0, 3.2541605000000002], ma...","[[0. 0. 3.2541605] Li, [0. 0. 0....","[Li, Sn, S]"

## Old Criteria

In [45]:
# # df_metal = df.loc[df.nsites<=64]
# df_metal = df.loc[df.nsites<=20]
# df_metal = df_metal.loc[df_metal.nelements>1]

In [46]:
# df_metal = df_metal.loc[df_metal.e_above_hull <= 0.2]
# print(df_metal.shape)

In [47]:
elements = [
     'H','Li', 'Be', 'B','C','N','O','F', 'Na', 'Mg', 'Al', 'Si','P','S','Cl', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 
    'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As','Se','Br','Rb', 'Sr', 'Y', 'Zr', 
    'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te','I', 'Cs', 
    'Ba', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At']
elements = [Element(el) for el in elements]
len(elements)

65

In [48]:
periodic_table = [
    ['H'], 
    ['Li', 'Be', 'B','C','N','O','F'], 
    ['Na', 'Mg', 'Al', 'Si','P','S','Cl'], 
    ['K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As','Se','Br'],
    ['Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te','I'], 
    ['Cs', 'Ba', 'La', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi','Po','At']
]

# Create a dictionary to store the neighbors of each element
element_neighbors = {}

In [49]:
# Iterate through the periodic table to populate the dictionary
for i, row in tqdm(enumerate(periodic_table)):
    for j, element in enumerate(row):
        # Initialize list of neighbors for the current element
        neighbors = []
        neighbors.append(periodic_table[i][j])
        # Add the elements to the left and right
        if j > 0:
            neighbors.append(row[j - 1])  # Add the element to the left
        if j < len(row) - 1:
            neighbors.append(row[j + 1])  # Add the element to the right
        
        # Add the elements above (if applicable)
        if i > 0:
            if len(periodic_table[i - 1])>j:
                neighbors.append(periodic_table[i - 1][j])  # Add the element above
                if j>0:
                    neighbors.append(periodic_table[i - 1][j-1])   
                if j<len(periodic_table[i - 1])-1:
                    neighbors.append(periodic_table[i - 1][j+1])                      
        
        # Add the elements below (if applicable)
        if i < len(periodic_table) - 1:
            neighbors.append(periodic_table[i + 1][j])  # Add the element below
            if j>0:
                neighbors.append(periodic_table[i + 1][j-1])   
            if j<len(periodic_table[i + 1])-1:
                neighbors.append(periodic_table[i + 1][j+1])               
        
        # Store the list of neighbors in the dictionary
        element_neighbors[element] = neighbors

6it [00:00, 31457.28it/s]

In [50]:
element_neighbors['B'] =  ['B', 'Al', 'Mg', 'Si']
element_neighbors['Mg'] =  ['Mg', 'Na', 'Be', 'Li', 'Ca', 'K', 'Sc']
element_neighbors['Al'] =  ['Al', 'Si', 'B','C','Zn','Ga','Ge' ]
element_neighbors['Si'] =  ['Si', 'Al', 'P', 'B', 'C','N', 'Ga', 'Ge', 'As']
element_neighbors['P'] = ['P', 'Si', 'S', 'N', 'C', 'O', 'Ge', 'As', 'Se']
element_neighbors['S'] = ['S', 'P', 'Cl', 'O', 'N', 'F', 'As', 'Se', 'Br']
element_neighbors['Cl'] = ['Cl', 'S', 'F', 'O', 'Se', 'Br']
element_neighbors['Ca'] =  ['Ca', 'K', 'Sc', 'Mg', 'Na', 'Sr', 'Rb', 'Y']
element_neighbors['Ga'] =  ['Ga', 'Zn', 'Ge', 'In', 'Cd', 'Sn','Al','Si']
element_neighbors['Ge'] =  ['Ge', 'Ga', 'As', 'Sn', 'In', 'Sb','Al','Si','P']
element_neighbors['As'] =  ['As', 'Ge','Se', 'Sb', 'Sn', 'Te','Si','P','S']
element_neighbors['Se'] = ['Se', 'As', 'Br', 'Te', 'Sb', 'I', 'P', 'S', 'Cl']

In [51]:
element_neighbors['Sc']= ['Sc', 'Ca', 'Ti', 'Mg', 'Y', 'Sr', 'Zr']

In [52]:
element_neighbors['Re']

['Re', 'W', 'Os', 'Tc', 'Mo', 'Ru']

In [53]:
import numpy as np

In [54]:
from collections import defaultdict
from pymatgen.core import Element, PeriodicSite
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from itertools import product
from tqdm.notebook import tqdm
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.core import Structure

In [55]:
# Helper function to replace elements in a structure
def replace_elements(structure, wyckoff_sites, replacements):
    new_structure = structure.copy()
    for site_idx, site in enumerate(structure):
        if wyckoff_sites[site_idx] in replacements:
            new_element = Element(replacements[wyckoff_sites[site_idx]])
            new_site = PeriodicSite(new_element, site.frac_coords, site.lattice)
            new_structure[site_idx] = new_site
    return new_structure

i = 0
j = 0
new_structures = []
mp_ids = []
formulas = []
parent_formulas = []
sgn = []

# structure = Structure.from_file('POSCAR')
for index, row in df.iterrows():
    structure = row.structure
    if all(elem in elements for elem in structure.species):
    
        formula = structure.composition.reduced_formula
        analyzer = SpacegroupAnalyzer(structure)
        sym_data = analyzer.get_symmetry_dataset()
        wyckoff_sites = sym_data["wyckoffs"]
        wyckoff_species = defaultdict(list)
        
        for site, wyckoff in zip(structure, wyckoff_sites):
            wyckoff_species[wyckoff].append(site.species_string)
    
        sub_sites = [(species_list[0], wyckoff) for wyckoff, species_list in wyckoff_species.items()]
        sub_sites_len = len(sub_sites)
        
        if 1 <= sub_sites_len<=5:
            if sub_sites_len >4:
                print(len(mp_ids))
            wyckoff_positions = [sub_sites[k][1] for k in range(sub_sites_len)]
            elements_list = [element_neighbors[sub_sites[k][0]] for k in range(sub_sites_len)]
            
            for replacement_combination in product(*elements_list):
                replacements = {wyckoff_positions[idx]: replacement_combination[idx] for idx in range(sub_sites_len)}
                new_structure = replace_elements(structure, wyckoff_sites, replacements)
                new_structures.append(new_structure)
                mp_ids.append(1)
                parent_formulas.append(formula)
                atoms = AseAtomsAdaptor.get_atoms(new_structure)
                formulas.append(atoms.get_chemical_formula())
                
                # formulas.append(new_structure.composition.to_pretty_string())
                # sgn.append(row['spacegroup.number'])
                i += 1
    
    
    print(j)
    print(i)

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['wyckoffs']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(

0
2025
0
2055
0
2100
0
2820
0
2865
0
6510
0
6510
0
6555
0
6560
0
6565
0
6765
0
6810
0
6840
0
7020
0
7500
0
7509
0
7514
0
7544
0
7704
0
7749
0
7830
0
9180
0
11205
0
12555
0
13905
0
15930
0
17955
17955
0
21555
0
21675
0
21945
0
22215
22215
0
30315
30315
0
38415
0
38445
0
38475
0
39555
0
40635
0
41195
0
41315
0
41720
0
41725
0
41730
0
41739
0
41745
0
41751
0
41976
0
43866
43866
0
50346
50346
0
56826
56826
0
63306
0
64926
0
65196
0
66276
0
67236
0
67281
0
67497
0
67522
0
67672
0
67822
0
67972
0
67997
0
68022
0
68047
0
68077
0
68257
0
68287
0
68317
68317
0
82897
82897
0
89377
0
90277
0
91897
0
92647
92647
0
104797
0
105877
0
106957
0
107002
0
107902
0
108127
0
108352
0
108622
0
109027
0
109432
0
109582
0
109807
0
110032
0
111032
0
111157
0
111157
0
111182
0
111212
0
111217
0
111217
0
111342
0
112782
0
113862
0
113862
0
113862
0
114087
0
114112
114112
0
117237
0
117862
0
118177
0
118447
0
120472
0
121672
0
123022
0
124822
0
126397
0
128422
0
129622
0
131197
0
132247
0
133597
0
135397
0
136747
0
138097
0
139297
0
140647
140647
0
143772
0
146607
0
146652
0
146657
0
147062
0
150707
0
151112
0
151142
0
151342
0
151522
0
151642
0
151682
0
154562
0
154742
0
155012
0
155012
155012
0
176882
0
176882
0
177002
0
177482
0
179102
0
179102
0
179507
0
179542
0
179722
0
180127
0
180157
0
180202
0
180232
0
180262
0
180292
0
180322
0
180342
0
180372
0
180417
0
180462
0
180492
0
180522
0
180562
0
180607
0
180637
0
180682
0
181087
0
181357
0
181762
0
182032
0
182302
0
182572
0
182602
0
182872
0
182902
0
183307
0
183442
0
183447
0
183477
0
183882
0
183912
0
184317
184317
0
198897
0
199167
0
199482
0
199487
0
199892
0
200162
0
200402
0
200762
0
200972
0
200977
0
201187
0
201592
0
201997
0
202312
0
202717
0
202987
0
203257
0
203527
0
203767
0
204172
0
204487
0
204757
0
205162
0
205432
0
205702
0
205972
0
206242
0
206602
0
207007
0
207412
0
207457
0
207482
0
207512
0
207517
0
207667
0
207847
0
207877
0
207877
0
208117
0
208267
0
208276
0
208321
0
208501
0
208681
0
208706
0
209111
0
210236
0
210266
0
210291
0
211191
0
211231
0
211636
0
211641
0
211911
0
211916
0
212321
0
212326
0
212476
0
212836
0
213961
0
217606
0
217886
0
218966
0
220991
220991
0
227471
0
227696
0
228416
0
228461
0
229901
0
229906
0
230086
0
230086
0
230086
0
230401
0
231751
0
231751
0
231876
0
234306
0
234336
0
234371
0
234401
0
234401
0
234407
0
234412
0
235492
0
235517
0
236517
0
236697
0
237657
0
237687
0
237732
0
237732
0
237912
0
238317
0
238342
0
238747
0
238747
0
240097
0
240997
0
241402
241402
0
246402
0
246582
0
246852
0
250497
0
250502
0
250547
0
251897
0
252107
0
252107
0
253187
0
253397
0
253577
0
253847
0
253862
0
254487
0
255387
0
255597
0
256677
0
257157
0
257337
0
258687
0
259767
0
259767
0
260037
0
260042
0
260267
0
260312
0
260582
0
260987
260987
0
266387
0
266792
0
267197
267197
0
281777
0
283127
283127
0
291767
0
291797
0
291822
0
292227
0
292252
0
292257
292257
0
301977
0
301982
0
302012
0
302417
0
302422
0
302462
302462

spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.

0
308942
0
309212
0
309242
0
309452
0
309458
0
309863
0
309868
0
310138
0
310543
0
312118
0
312124
312124
0
321844
0
321849
0
322254
0
324144
0
324159
0
324159
0
326589
0
326994
0
326999
0
327404
0
329429
329429
0
335554
0
335584
0
335614
0
336364
0
336370
0
336615
0
336615
0
336621
0
339456
0
339771
0
340521
0
340551
0
341271
0
341896
0
342301

In [52]:
with open("Fromulas.txt", "w") as file:
    for item in formulas:
        file.write(f"{item}\n")

In [25]:
# Helper function to replace elements in a structure
def replace_elements(structure, wyckoff_sites, replacements):
    new_structure = structure.copy()
    for site_idx, site in enumerate(structure):
        if wyckoff_sites[site_idx] in replacements:
            new_element = Element(replacements[wyckoff_sites[site_idx]])
            new_site = PeriodicSite(new_element, site.frac_coords, site.lattice)
            new_structure[site_idx] = new_site
    return new_structure

i = 0
j = 0
new_structures = []
mp_ids = []
formulas = []
parent_formulas = []
sgn = []

for index, row in tqdm(df.iterrows(),total = df.shape[0]):
    structure = row.structure 
    j += 1    
    if all(elem in elements for elem in structure.species):

        formula = row.pretty_formula
        analyzer = SpacegroupAnalyzer(structure)
        sym_data = analyzer.get_symmetry_dataset()
        wyckoff_sites = sym_data["wyckoffs"]
        wyckoff_species = defaultdict(list)
        
        for site, wyckoff in zip(structure, wyckoff_sites):
            wyckoff_species[wyckoff].append(site.species_string)

        sub_sites = [(species_list[0], wyckoff) for wyckoff, species_list in wyckoff_species.items()]
        sub_sites_len = len(sub_sites)
        
        if 1 <= sub_sites_len<=5:
            if sub_sites_len >4:
                print(len(mp_ids))
            wyckoff_positions = [sub_sites[k][1] for k in range(sub_sites_len)]
            elements_list = [element_neighbors[sub_sites[k][0]] for k in range(sub_sites_len)]
            
            for replacement_combination in product(*elements_list):
                replacements = {wyckoff_positions[idx]: replacement_combination[idx] for idx in range(sub_sites_len)}
                new_structure = replace_elements(structure, wyckoff_sites, replacements)
                new_structures.append(new_structure)
                mp_ids.append(index)
                parent_formulas.append(formula)
                formulas.append(new_structure.composition.reduced_formula)
                sgn.append(row['spacegroup.number'])
                i += 1


    print(j)
    print(i)

  0%|          | 0/225 [00:00<?, ?it/s]

1
486
2
972
3
2916
2916
4
10692
5
12636
6
13932
7
15228
8
15714
9
16038
10
16362
11
16542
12
16812
13
17244
14
17622
15
18054
16
18306
17
18630
18
18846
19
19062
20
19386
21
19872
22
20088
23
20304
24
20592
25
20916
26
22860
27
22914
28
22968
29
23184
30
23220
31
23544
32
23580
33
23904
34
24120
35
25416
36
25740
37
25746
38
25962
39
25998
40
26052
41
27996
42
28320
43
28374
44
28806
45
29130
46
29130
47
29130
48
30426
49
30750
50
32694
51
34206
52
34494
53
36006
54
37950
55
39894
56
41838
57
43782
58
45726
59
45906
60
46230
61
46554
62
46770
63
46986
64
47202
65
47490
66
47814
67
48138
68
48462
69
48678
70
49002
71
49326
72
49812
73
50136
74
50460
75
50784
76
51000
77
51324
78
51648
79
51864
80
52188
81
52512
82
52764
83
52818
84
53142
85
53466
86
53790
87
54078
88
54366
89
54690
90
54906
91
55230
92
55482
93
55806
94
56292
95
56778
96
56783
97
56819
56819
98
64595
99
64919
100
65135
101
65459
102
65495
103
65747
104
65801
105
66017
106
66071
107
66557
108
66845
109
68573
110
70517
111
70841
112
72137
113
72173
114
74117
115
74285
116
74465
117
74501
118
74825
119
75041
120
75257
121
75293
122
75329
123
76625
124
76625
125
76877
126
77363
127
77687
77687
128
85463
129
86759
130
88055
131
89351
132
91295
133
92591
134
92591
135
93887
136
94103
137
94589
138
94841
139
96785
140
98729
141
98729
142
98765
143
100061
144
101357
145
101537
146
101537
147
101573
148
101897
149
102113
150
105029
151
105353
152
105407
153
105785
154
106109
155
106325
156
107621
157
109565
158
109889
159
109943
160
110279
161
110531
162
110819
163
111251
164
111299
165
111335
166
111551
167
112037
168
112253
169
112577
112577
170
120353
171
120731
172
120947
120947
173
132611
174
134555
175
137471
176
137525
177
137957
178
138389
179
138443
180
138929
181
139253
182
139307
183
139316
184
139352
185
139838
186
139910
187
140126
188
141422
189
141800
190
142184
191
144128
192
144192
193
144624
194
145920
195
146244
196
146676
197
146928
198
146952
199
146988
200
147474
201
147480
202
147696
203
148020
204
149316
205
149802
206
150126
207
150612
208
150936
209
150990
210
151566
211
151782
212
153294
213
153330
214
153654
215
155598
216
155604
217
155820
155820
218
167484
219
167484
220
167532
221
167856
222
168199
223
168199
224
168523
225
168847

In [57]:
len(mp_ids)

342301

In [58]:
len(new_structures)

342301

In [60]:
len(new_structures)

342301

In [61]:
len(sgn)

0

In [62]:
df = pd.DataFrame({'structure':new_structures,'mp_id': mp_ids,'parent_formula':parent_formulas,'formula':formulas})

In [68]:
tqdm.pandas()
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.ase import AseAtomsAdaptor as aaa
def get_sgn(df):
    analyzer = SpacegroupAnalyzer(df.structure)
    sym_data = analyzer.get_symmetry_dataset()
    return sym_data['number']
df['sgn'] = df.progress_apply(get_sgn,axis=1)

  0%|          | 0/342301 [00:00<?, ?it/s]

/blue/hennig/jasongibson/envs/e3nn/lib/python3.9/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.

In [69]:
df_cleaned = df.drop_duplicates(subset=['sgn', 'formula'], keep='first')
# df_og = pd.read_pickle(f'pickle_files/{par_el}_sub.pkl')

In [70]:
df_cleaned.reset_index(inplace=True)

In [31]:
par_el = 'temp'

In [74]:
df = df_cleaned.loc[df_cleaned.formula.str.contains('Li')]

In [75]:
df.to_pickle(f'Li.pkl')

In [76]:
df

,index,structure,mp_id,parent_formula,formula,sgn
0,0,"[[1.56926692 3.60932262 4.30354952] Li, [ 1.56...",1,LiSn,Li3Sn3,10
1,1,"[[1.56926692 3.60932262 4.30354952] Li, [ 1.56...",1,LiSn,InLi3Sn2,10
2,2,"[[1.56926692 3.60932262 4.30354952] Li, [ 1.56...",1,LiSn,Li3SbSn2,10
3,3,"[[1.56926692 3.60932262 4.30354952] Li, [ 1.56...",1,LiSn,GeLi3Sn2,10
4,4,"[[1.56926692 3.60932262 4.30354952] Li, [ 1.56...",1,LiSn,GaLi3Sn2,10
...,...,...,...,...,...,...
170261,341972,"[[0. 0. 3.2541605] Li, [0. 0. 0....",1,LiSnS2,BiLiN2,164
170262,341973,"[[0. 0. 3.2541605] Li, [0. 0. 0....",1,LiSnS2,BiF2Li,164
170263,341974,"[[0. 0. 3.2541605] Li, [0. 0. 0....",1,LiSnS2,As2BiLi,164
170264,341975,"[[0. 0. 3.2541605] Li, [0. 0. 0....",1,LiSnS2,BiLiSe2,164
170265,341976,"[[0. 0. 3.2541605] Li, [0. 0. 0....",1,LiSnS2,BiBr2Li,164

In [33]:
df_cleaned.shape[0]/1000

56.368

In [34]:
from tqdm.notebook import tqdm

In [35]:
root = f'/blue/hennig/jasongibson/elemental_sub/materials/{par_el}/unrelaxed/'
for index, row in tqdm(df_cleaned.iterrows(),total=len(df_cleaned)):
    row.structure.to(root + f'POSCAR_{index}')

  0%|          | 0/56368 [00:00<?, ?it/s]

In [233]:
for struct in tqdm(new_structures):
    relax_results = relaxer.relax(struct, fmax=0.001)
    # extract results
    final_structure = relax_results["final_structure"]
    final_energy = relax_results["trajectory"].energies[-1]
    # print out the final relaxed structure and energy

    print(f"The final energy is {float(final_energy):.3f} eV.")

    # For multi-fidelity models, we need to define graph label ("0": PBE, "1": GLLB-SC, "2": HSE, "3": SCAN)
    for i, method in ((0, "PBE"), (1, "GLLB-SC"), (2, "HSE"), (3, "SCAN")):
        graph_attrs = torch.tensor([i])
        bandgap = model_bg.predict_structure(structure=final_structure, state_attr=graph_attrs)
        print(f"The predicted {method} band gap for {final_structure.composition.reduced_formula} is {float(bandgap):.3f} eV.")

    eform = model_form.predict_structure(final_structure)
    print(f"The predicted formation energy for {final_structure.composition.reduced_formula} is {float(eform):.3f} eV/atom.")

  0%|                                                                                                                                                               | 0/9610 [00:00<?, ?it/s]
  0%|                                                                                                                                                     | 1/9610 [00:02<6:48:52,  2.55s/it]

The final energy is -33.480 eV.
The predicted PBE band gap for BeNbRu2 is -0.008 eV.
The predicted GLLB-SC band gap for BeNbRu2 is 0.629 eV.
The predicted HSE band gap for BeNbRu2 is -0.008 eV.
The predicted SCAN band gap for BeNbRu2 is 0.146 eV.
The predicted formation energy for BeNbRu2 is -0.281 eV/atom.

  0%|                                                                                                                                                    | 2/9610 [00:07<10:01:41,  3.76s/it]

The final energy is -35.227 eV.
The predicted PBE band gap for BeNbTc2 is -0.008 eV.
The predicted GLLB-SC band gap for BeNbTc2 is 0.980 eV.
The predicted HSE band gap for BeNbTc2 is -0.008 eV.
The predicted SCAN band gap for BeNbTc2 is 0.497 eV.
The predicted formation energy for BeNbTc2 is -0.167 eV/atom.

  0%|                                                                                                                                                    | 3/9610 [00:15<15:06:27,  5.66s/it]

The final energy is -30.471 eV.
The predicted PBE band gap for BeNbRh2 is -0.009 eV.
The predicted GLLB-SC band gap for BeNbRh2 is 0.249 eV.
The predicted HSE band gap for BeNbRh2 is -0.010 eV.
The predicted SCAN band gap for BeNbRh2 is 0.086 eV.
The predicted formation energy for BeNbRh2 is -0.470 eV/atom.

  0%|                                                                                                                                                    | 4/9610 [00:21<15:36:46,  5.85s/it]

The final energy is -30.999 eV.
The predicted PBE band gap for BeNbFe2 is -0.008 eV.
The predicted GLLB-SC band gap for BeNbFe2 is 0.513 eV.
The predicted HSE band gap for BeNbFe2 is -0.007 eV.
The predicted SCAN band gap for BeNbFe2 is 0.181 eV.
The predicted formation energy for BeNbFe2 is -0.166 eV/atom.

  0%|                                                                                                                                                    | 5/9610 [00:35<24:04:50,  9.03s/it]

The final energy is -32.143 eV.
The predicted PBE band gap for Mn2BeNb is -0.008 eV.
The predicted GLLB-SC band gap for Mn2BeNb is 0.528 eV.
The predicted HSE band gap for Mn2BeNb is 0.562 eV.
The predicted SCAN band gap for Mn2BeNb is 0.332 eV.
The predicted formation energy for Mn2BeNb is -0.106 eV/atom.

  0%|                                                                                                                                                    | 6/9610 [00:43<23:04:31,  8.65s/it]

The final energy is -28.746 eV.
The predicted PBE band gap for BeNbCo2 is -0.007 eV.
The predicted GLLB-SC band gap for BeNbCo2 is 0.734 eV.
The predicted HSE band gap for BeNbCo2 is -0.008 eV.
The predicted SCAN band gap for BeNbCo2 is 0.302 eV.
The predicted formation energy for BeNbCo2 is -0.206 eV/atom.

  0%|                                                                                                                                                    | 7/9610 [00:55<25:21:08,  9.50s/it]

The final energy is -36.854 eV.
The predicted PBE band gap for BeNbOs2 is -0.008 eV.
The predicted GLLB-SC band gap for BeNbOs2 is 0.828 eV.
The predicted HSE band gap for BeNbOs2 is -0.008 eV.
The predicted SCAN band gap for BeNbOs2 is 0.057 eV.
The predicted formation energy for BeNbOs2 is -0.174 eV/atom.

  0%|                                                                                                                                                    | 8/9610 [01:02<23:34:35,  8.84s/it]

The final energy is -38.937 eV.
The predicted PBE band gap for BeNbRe2 is -0.010 eV.
The predicted GLLB-SC band gap for BeNbRe2 is 0.012 eV.
The predicted HSE band gap for BeNbRe2 is -0.009 eV.
The predicted SCAN band gap for BeNbRe2 is -0.008 eV.
The predicted formation energy for BeNbRe2 is 0.053 eV/atom.

  0%|▏                                                                                                                                                   | 9/9610 [01:10<23:02:42,  8.64s/it]

The final energy is -33.574 eV.
The predicted PBE band gap for BeNbIr2 is -0.008 eV.
The predicted GLLB-SC band gap for BeNbIr2 is 0.408 eV.
The predicted HSE band gap for BeNbIr2 is -0.009 eV.
The predicted SCAN band gap for BeNbIr2 is 0.404 eV.
The predicted formation energy for BeNbIr2 is -0.326 eV/atom.

  0%|▏                                                                                                                                                  | 10/9610 [01:14<18:59:50,  7.12s/it]

The final energy is -32.035 eV.
The predicted PBE band gap for ZrBeRu2 is -0.007 eV.
The predicted GLLB-SC band gap for ZrBeRu2 is 0.669 eV.
The predicted HSE band gap for ZrBeRu2 is -0.007 eV.
The predicted SCAN band gap for ZrBeRu2 is 0.433 eV.
The predicted formation energy for ZrBeRu2 is -0.366 eV/atom.

  0%|▏                                                                                                                                                  | 11/9610 [01:26<23:26:12,  8.79s/it]

The final energy is -33.289 eV.
The predicted PBE band gap for ZrBeTc2 is -0.007 eV.
The predicted GLLB-SC band gap for ZrBeTc2 is 0.380 eV.
The predicted HSE band gap for ZrBeTc2 is -0.010 eV.
The predicted SCAN band gap for ZrBeTc2 is -0.007 eV.
The predicted formation energy for ZrBeTc2 is -0.131 eV/atom.

  0%|▏                                                                                                                                                  | 12/9610 [01:31<20:15:07,  7.60s/it]

The final energy is -29.832 eV.
The predicted PBE band gap for ZrBeRh2 is -0.008 eV.
The predicted GLLB-SC band gap for ZrBeRh2 is 0.013 eV.
The predicted HSE band gap for ZrBeRh2 is -0.008 eV.
The predicted SCAN band gap for ZrBeRh2 is 0.023 eV.
The predicted formation energy for ZrBeRh2 is -0.649 eV/atom.

  0%|▏                                                                                                                                                  | 13/9610 [01:43<23:28:03,  8.80s/it]

The final energy is -29.191 eV.
The predicted PBE band gap for ZrBeFe2 is -0.010 eV.
The predicted GLLB-SC band gap for ZrBeFe2 is 0.121 eV.
The predicted HSE band gap for ZrBeFe2 is -0.010 eV.
The predicted SCAN band gap for ZrBeFe2 is 0.039 eV.
The predicted formation energy for ZrBeFe2 is -0.122 eV/atom.

  0%|▏                                                                                                                                                  | 14/9610 [01:54<25:29:29,  9.56s/it]

The final energy is -30.211 eV.
The predicted PBE band gap for ZrMn2Be is -0.009 eV.
The predicted GLLB-SC band gap for ZrMn2Be is 0.131 eV.
The predicted HSE band gap for ZrMn2Be is -0.008 eV.
The predicted SCAN band gap for ZrMn2Be is 0.009 eV.
The predicted formation energy for ZrMn2Be is -0.111 eV/atom.

  0%|▏                                                                                                                                                  | 15/9610 [02:05<26:06:56,  9.80s/it]

The final energy is -27.245 eV.
The predicted PBE band gap for ZrBeCo2 is -0.007 eV.
The predicted GLLB-SC band gap for ZrBeCo2 is 0.055 eV.
The predicted HSE band gap for ZrBeCo2 is -0.008 eV.
The predicted SCAN band gap for ZrBeCo2 is 0.023 eV.
The predicted formation energy for ZrBeCo2 is -0.350 eV/atom.

  0%|▏                                                                                                                                                  | 16/9610 [02:17<27:55:14, 10.48s/it]

The final energy is -34.923 eV.
The predicted PBE band gap for ZrBeOs2 is -0.007 eV.
The predicted GLLB-SC band gap for ZrBeOs2 is 0.598 eV.
The predicted HSE band gap for ZrBeOs2 is -0.008 eV.
The predicted SCAN band gap for ZrBeOs2 is 0.114 eV.
The predicted formation energy for ZrBeOs2 is -0.172 eV/atom.

  0%|▎                                                                                                                                                  | 17/9610 [02:32<31:46:43, 11.93s/it]

The final energy is -35.961 eV.
The predicted PBE band gap for ZrBeRe2 is -0.014 eV.
The predicted GLLB-SC band gap for ZrBeRe2 is 0.229 eV.
The predicted HSE band gap for ZrBeRe2 is -0.010 eV.
The predicted SCAN band gap for ZrBeRe2 is 0.018 eV.
The predicted formation energy for ZrBeRe2 is 0.171 eV/atom.

  0%|▎                                                                                                                                                  | 18/9610 [02:40<28:27:47, 10.68s/it]

The final energy is -32.610 eV.
The predicted PBE band gap for ZrBeIr2 is -0.007 eV.
The predicted GLLB-SC band gap for ZrBeIr2 is 0.319 eV.
The predicted HSE band gap for ZrBeIr2 is -0.007 eV.
The predicted SCAN band gap for ZrBeIr2 is 0.366 eV.
The predicted formation energy for ZrBeIr2 is -0.559 eV/atom.

  0%|▎                                                                                                                                                  | 19/9610 [02:54<31:13:49, 11.72s/it]

The final energy is -33.631 eV.
The predicted PBE band gap for BeMoRu2 is -0.007 eV.
The predicted GLLB-SC band gap for BeMoRu2 is 0.148 eV.
The predicted HSE band gap for BeMoRu2 is -0.007 eV.
The predicted SCAN band gap for BeMoRu2 is -0.008 eV.
The predicted formation energy for BeMoRu2 is -0.139 eV/atom.

  0%|▎                                                                                                                                                  | 20/9610 [03:05<30:45:04, 11.54s/it]

The final energy is -35.604 eV.
The predicted PBE band gap for BeTc2Mo is -0.012 eV.
The predicted GLLB-SC band gap for BeTc2Mo is 0.715 eV.
The predicted HSE band gap for BeTc2Mo is -0.012 eV.
The predicted SCAN band gap for BeTc2Mo is -0.014 eV.
The predicted formation energy for BeTc2Mo is -0.151 eV/atom.

  0%|▎                                                                                                                                                  | 21/9610 [03:19<32:54:23, 12.35s/it]

The final energy is -30.503 eV.
The predicted PBE band gap for BeMoRh2 is -0.009 eV.
The predicted GLLB-SC band gap for BeMoRh2 is 0.109 eV.
The predicted HSE band gap for BeMoRh2 is -0.010 eV.
The predicted SCAN band gap for BeMoRh2 is -0.012 eV.
The predicted formation energy for BeMoRh2 is -0.278 eV/atom.

  0%|▎                                                                                                                                                  | 22/9610 [03:29<30:34:25, 11.48s/it]

The final energy is -31.260 eV.
The predicted PBE band gap for BeFe2Mo is -0.005 eV.
The predicted GLLB-SC band gap for BeFe2Mo is 0.911 eV.
The predicted HSE band gap for BeFe2Mo is -0.008 eV.
The predicted SCAN band gap for BeFe2Mo is 0.151 eV.
The predicted formation energy for BeFe2Mo is -0.053 eV/atom.

  0%|▎                                                                                                                                                  | 23/9610 [03:43<33:05:25, 12.43s/it]

The final energy is -32.699 eV.
The predicted PBE band gap for Mn2BeMo is -0.008 eV.
The predicted GLLB-SC band gap for Mn2BeMo is 0.622 eV.
The predicted HSE band gap for Mn2BeMo is -0.006 eV.
The predicted SCAN band gap for Mn2BeMo is 0.317 eV.
The predicted formation energy for Mn2BeMo is 0.012 eV/atom.

  0%|▎                                                                                                                                                  | 24/9610 [04:00<36:08:02, 13.57s/it]

The final energy is -29.040 eV.
The predicted PBE band gap for BeCo2Mo is -0.007 eV.
The predicted GLLB-SC band gap for BeCo2Mo is 0.693 eV.
The predicted HSE band gap for BeCo2Mo is -0.009 eV.
The predicted SCAN band gap for BeCo2Mo is 0.249 eV.
The predicted formation energy for BeCo2Mo is -0.180 eV/atom.

  0%|▍                                                                                                                                                  | 25/9610 [04:09<32:35:38, 12.24s/it]

The final energy is -36.960 eV.
The predicted PBE band gap for BeMoOs2 is -0.007 eV.
The predicted GLLB-SC band gap for BeMoOs2 is 0.623 eV.
The predicted HSE band gap for BeMoOs2 is -0.007 eV.
The predicted SCAN band gap for BeMoOs2 is 0.082 eV.
The predicted formation energy for BeMoOs2 is -0.102 eV/atom.

  0%|▍                                                                                                                                                  | 26/9610 [04:17<29:06:58, 10.94s/it]

The final energy is -39.262 eV.
The predicted PBE band gap for BeRe2Mo is -0.009 eV.
The predicted GLLB-SC band gap for BeRe2Mo is 0.407 eV.
The predicted HSE band gap for BeRe2Mo is -0.009 eV.
The predicted SCAN band gap for BeRe2Mo is 0.029 eV.
The predicted formation energy for BeRe2Mo is 0.083 eV/atom.

  0%|▍                                                                                                                                                  | 27/9610 [04:25<27:04:55, 10.17s/it]

The final energy is -33.375 eV.
The predicted PBE band gap for BeMoIr2 is -0.008 eV.
The predicted GLLB-SC band gap for BeMoIr2 is 0.509 eV.
The predicted HSE band gap for BeMoIr2 is -0.008 eV.
The predicted SCAN band gap for BeMoIr2 is -0.003 eV.
The predicted formation energy for BeMoIr2 is -0.173 eV/atom.

  0%|▍                                                                                                                                                  | 28/9610 [04:36<27:46:34, 10.44s/it]

The final energy is -32.819 eV.
The predicted PBE band gap for BeVRu2 is -0.007 eV.
The predicted GLLB-SC band gap for BeVRu2 is 0.273 eV.
The predicted HSE band gap for BeVRu2 is -0.007 eV.
The predicted SCAN band gap for BeVRu2 is -0.006 eV.
The predicted formation energy for BeVRu2 is -0.357 eV/atom.

  0%|▍                                                                                                                                                  | 29/9610 [04:39<21:35:53,  8.12s/it]

The final energy is -34.669 eV.
The predicted PBE band gap for BeVTc2 is -0.011 eV.
The predicted GLLB-SC band gap for BeVTc2 is 0.356 eV.
The predicted HSE band gap for BeVTc2 is -0.009 eV.
The predicted SCAN band gap for BeVTc2 is -0.008 eV.
The predicted formation energy for BeVTc2 is -0.360 eV/atom.

The final energy is -29.699 eV.
The predicted PBE band gap for BeVRh2 is -0.009 eV.
The predicted GLLB-SC band gap for BeVRh2 is 0.523 eV.
The predicted HSE band gap for BeVRh2 is -0.010 eV.
The predicted SCAN band gap for BeVRh2 is -0.012 eV.
The predicted formation energy for BeVRh2 is -0.549 eV/atom.

  0%|▍                                                                                                                                                  | 30/9610 [04:48<22:46:01,  8.56s/it]
  0%|▍                                                                                                                                                  | 31/9610 [05:00<25:32:49,  9.60s/it]

The final energy is -30.619 eV.
The predicted PBE band gap for BeVFe2 is -0.006 eV.
The predicted GLLB-SC band gap for BeVFe2 is 0.991 eV.
The predicted HSE band gap for BeVFe2 is 0.011 eV.
The predicted SCAN band gap for BeVFe2 is 0.108 eV.
The predicted formation energy for BeVFe2 is -0.210 eV/atom.

  0%|▍                                                                                                                                                  | 32/9610 [05:02<19:11:52,  7.22s/it]

The final energy is -31.945 eV.
The predicted PBE band gap for Mn2BeV is -0.009 eV.
The predicted GLLB-SC band gap for Mn2BeV is 0.626 eV.
The predicted HSE band gap for Mn2BeV is 0.001 eV.
The predicted SCAN band gap for Mn2BeV is 0.410 eV.
The predicted formation energy for Mn2BeV is -0.037 eV/atom.

  0%|▌                                                                                                                                                  | 33/9610 [05:09<18:51:27,  7.09s/it]

The final energy is -28.124 eV.
The predicted PBE band gap for BeVCo2 is -0.007 eV.
The predicted GLLB-SC band gap for BeVCo2 is 0.987 eV.
The predicted HSE band gap for BeVCo2 is -0.010 eV.
The predicted SCAN band gap for BeVCo2 is 0.186 eV.
The predicted formation energy for BeVCo2 is -0.268 eV/atom.

  0%|▌                                                                                                                                                  | 34/9610 [05:22<24:01:47,  9.03s/it]

The final energy is -36.253 eV.
The predicted PBE band gap for BeVOs2 is -0.008 eV.
The predicted GLLB-SC band gap for BeVOs2 is 0.395 eV.
The predicted HSE band gap for BeVOs2 is -0.008 eV.
The predicted SCAN band gap for BeVOs2 is 0.013 eV.
The predicted formation energy for BeVOs2 is -0.337 eV/atom.

  0%|▌                                                                                                                                                  | 35/9610 [05:36<27:22:52, 10.29s/it]

The final energy is -38.694 eV.
The predicted PBE band gap for BeVRe2 is -0.011 eV.
The predicted GLLB-SC band gap for BeVRe2 is 0.469 eV.
The predicted HSE band gap for BeVRe2 is 0.012 eV.
The predicted SCAN band gap for BeVRe2 is 0.031 eV.
The predicted formation energy for BeVRe2 is -0.267 eV/atom.

  0%|▌                                                                                                                                                  | 36/9610 [05:50<30:24:32, 11.43s/it]

The final energy is -32.767 eV.
The predicted PBE band gap for BeVIr2 is -0.008 eV.
The predicted GLLB-SC band gap for BeVIr2 is 0.812 eV.
The predicted HSE band gap for BeVIr2 is -0.008 eV.
The predicted SCAN band gap for BeVIr2 is 0.067 eV.
The predicted formation energy for BeVIr2 is -0.511 eV/atom.

  0%|▌                                                                                                                                                  | 37/9610 [06:04<32:32:52, 12.24s/it]

The final energy is -32.027 eV.
The predicted PBE band gap for TiBeRu2 is -0.008 eV.
The predicted GLLB-SC band gap for TiBeRu2 is 0.701 eV.
The predicted HSE band gap for TiBeRu2 is -0.007 eV.
The predicted SCAN band gap for TiBeRu2 is 0.036 eV.
The predicted formation energy for TiBeRu2 is -0.498 eV/atom.

  0%|▌                                                                                                                                                  | 38/9610 [06:14<31:15:27, 11.76s/it]

The final energy is -33.485 eV.
The predicted PBE band gap for TiBeTc2 is 0.002 eV.
The predicted GLLB-SC band gap for TiBeTc2 is 0.495 eV.
The predicted HSE band gap for TiBeTc2 is 0.010 eV.
The predicted SCAN band gap for TiBeTc2 is 0.279 eV.
The predicted formation energy for TiBeTc2 is -0.345 eV/atom.
The final energy is -29.517 eV.

  0%|▌                                                                                                                                                  | 39/9610 [06:25<29:58:37, 11.28s/it]

The predicted PBE band gap for TiBeRh2 is -0.010 eV.
The predicted GLLB-SC band gap for TiBeRh2 is 1.082 eV.
The predicted HSE band gap for TiBeRh2 is -0.010 eV.
The predicted SCAN band gap for TiBeRh2 is 0.299 eV.
The predicted formation energy for TiBeRh2 is -0.792 eV/atom.

  0%|▌                                                                                                                                                  | 40/9610 [06:37<31:04:57, 11.69s/it]

The final energy is -29.717 eV.
The predicted PBE band gap for TiBeFe2 is -0.007 eV.
The predicted GLLB-SC band gap for TiBeFe2 is 0.454 eV.
The predicted HSE band gap for TiBeFe2 is -0.008 eV.
The predicted SCAN band gap for TiBeFe2 is 0.118 eV.
The predicted formation energy for TiBeFe2 is -0.269 eV/atom.

  0%|▋                                                                                                                                                  | 41/9610 [06:44<27:21:50, 10.29s/it]

The final energy is -30.756 eV.
The predicted PBE band gap for TiMn2Be is -0.007 eV.
The predicted GLLB-SC band gap for TiMn2Be is 0.418 eV.
The predicted HSE band gap for TiMn2Be is 0.036 eV.
The predicted SCAN band gap for TiMn2Be is 0.112 eV.
The predicted formation energy for TiMn2Be is -0.141 eV/atom.

  0%|▋                                                                                                                                                  | 42/9610 [06:55<27:51:43, 10.48s/it]

The final energy is -27.551 eV.
The predicted PBE band gap for TiBeCo2 is -0.008 eV.
The predicted GLLB-SC band gap for TiBeCo2 is 0.721 eV.
The predicted HSE band gap for TiBeCo2 is -0.008 eV.
The predicted SCAN band gap for TiBeCo2 is 0.267 eV.
The predicted formation energy for TiBeCo2 is -0.440 eV/atom.

  0%|▋                                                                                                                                                  | 43/9610 [07:09<30:33:15, 11.50s/it]

The final energy is -35.235 eV.
The predicted PBE band gap for TiBeOs2 is -0.008 eV.
The predicted GLLB-SC band gap for TiBeOs2 is 0.649 eV.
The predicted HSE band gap for TiBeOs2 is -0.008 eV.
The predicted SCAN band gap for TiBeOs2 is 0.243 eV.
The predicted formation energy for TiBeOs2 is -0.393 eV/atom.

  0%|▋                                                                                                                                                  | 44/9610 [07:19<29:10:26, 10.98s/it]

The final energy is -36.729 eV.
The predicted PBE band gap for TiBeRe2 is -0.010 eV.
The predicted GLLB-SC band gap for TiBeRe2 is 0.090 eV.
The predicted HSE band gap for TiBeRe2 is -0.009 eV.
The predicted SCAN band gap for TiBeRe2 is 0.025 eV.
The predicted formation energy for TiBeRe2 is -0.095 eV/atom.

  0%|▋                                                                                                                                                  | 45/9610 [07:24<24:40:02,  9.28s/it]

The final energy is -32.485 eV.
The predicted PBE band gap for TiBeIr2 is -0.009 eV.
The predicted GLLB-SC band gap for TiBeIr2 is 0.787 eV.
The predicted HSE band gap for TiBeIr2 is 0.009 eV.
The predicted SCAN band gap for TiBeIr2 is 0.551 eV.
The predicted formation energy for TiBeIr2 is -0.781 eV/atom.

  0%|▋                                                                                                                                                  | 46/9610 [07:34<25:00:59,  9.42s/it]

The final energy is -32.410 eV.
The predicted PBE band gap for BeCrRu2 is -0.008 eV.
The predicted GLLB-SC band gap for BeCrRu2 is 0.623 eV.
The predicted HSE band gap for BeCrRu2 is -0.006 eV.
The predicted SCAN band gap for BeCrRu2 is 0.015 eV.
The predicted formation energy for BeCrRu2 is -0.144 eV/atom.

  0%|▋                                                                                                                                                  | 47/9610 [07:53<32:30:31, 12.24s/it]

The final energy is -34.456 eV.
The predicted PBE band gap for BeCrTc2 is -0.009 eV.
The predicted GLLB-SC band gap for BeCrTc2 is 0.582 eV.
The predicted HSE band gap for BeCrTc2 is -0.009 eV.
The predicted SCAN band gap for BeCrTc2 is 0.075 eV.
The predicted formation energy for BeCrTc2 is -0.178 eV/atom.

  0%|▋                                                                                                                                                  | 48/9610 [08:02<30:07:50, 11.34s/it]

The final energy is -29.329 eV.
The predicted PBE band gap for BeCrRh2 is -0.010 eV.
The predicted GLLB-SC band gap for BeCrRh2 is 0.040 eV.
The predicted HSE band gap for BeCrRh2 is -0.011 eV.
The predicted SCAN band gap for BeCrRh2 is -0.006 eV.
The predicted formation energy for BeCrRh2 is -0.354 eV/atom.

  1%|▋                                                                                                                                                  | 49/9610 [08:14<30:58:53, 11.67s/it]

The final energy is -30.509 eV.
The predicted PBE band gap for BeCrFe2 is -0.007 eV.
The predicted GLLB-SC band gap for BeCrFe2 is 0.903 eV.
The predicted HSE band gap for BeCrFe2 is -0.007 eV.
The predicted SCAN band gap for BeCrFe2 is 0.030 eV.
The predicted formation energy for BeCrFe2 is -0.005 eV/atom.

  1%|▊                                                                                                                                                  | 50/9610 [08:23<28:30:51, 10.74s/it]

The final energy is -32.162 eV.
The predicted PBE band gap for Mn2BeCr is -0.008 eV.
The predicted GLLB-SC band gap for Mn2BeCr is 0.575 eV.
The predicted HSE band gap for Mn2BeCr is -0.007 eV.
The predicted SCAN band gap for Mn2BeCr is 0.374 eV.
The predicted formation energy for Mn2BeCr is -0.002 eV/atom.

  1%|▊                                                                                                                                                  | 51/9610 [08:34<29:04:22, 10.95s/it]

The final energy is -27.991 eV.
The predicted PBE band gap for BeCrCo2 is -0.007 eV.
The predicted GLLB-SC band gap for BeCrCo2 is 0.403 eV.
The predicted HSE band gap for BeCrCo2 is -0.008 eV.
The predicted SCAN band gap for BeCrCo2 is 0.051 eV.
The predicted formation energy for BeCrCo2 is -0.154 eV/atom.

  1%|▊                                                                                                                                                  | 52/9610 [08:52<34:30:31, 13.00s/it]

The final energy is -36.226 eV.
The predicted PBE band gap for BeCrOs2 is -0.007 eV.
The predicted GLLB-SC band gap for BeCrOs2 is 0.979 eV.
The predicted HSE band gap for BeCrOs2 is -0.007 eV.
The predicted SCAN band gap for BeCrOs2 is 0.184 eV.
The predicted formation energy for BeCrOs2 is -0.117 eV/atom.

  1%|▊                                                                                                                                                  | 53/9610 [09:10<38:13:59, 14.40s/it]

The final energy is -38.514 eV.
The predicted PBE band gap for BeCrRe2 is -0.009 eV.
The predicted GLLB-SC band gap for BeCrRe2 is 0.331 eV.
The predicted HSE band gap for BeCrRe2 is -0.007 eV.
The predicted SCAN band gap for BeCrRe2 is 0.010 eV.
The predicted formation energy for BeCrRe2 is -0.088 eV/atom.

  1%|▊                                                                                                                                                  | 54/9610 [09:27<40:24:16, 15.22s/it]

The final energy is -32.517 eV.
The predicted PBE band gap for BeCrIr2 is -0.008 eV.
The predicted GLLB-SC band gap for BeCrIr2 is 0.301 eV.
The predicted HSE band gap for BeCrIr2 is -0.008 eV.
The predicted SCAN band gap for BeCrIr2 is 0.001 eV.
The predicted formation energy for BeCrIr2 is -0.311 eV/atom.

  1%|▊                                                                                                                                                  | 55/9610 [09:35<34:35:13, 13.03s/it]

The final energy is -35.611 eV.
The predicted PBE band gap for TaBeRu2 is -0.009 eV.
The predicted GLLB-SC band gap for TaBeRu2 is 0.656 eV.
The predicted HSE band gap for TaBeRu2 is -0.009 eV.
The predicted SCAN band gap for TaBeRu2 is 0.067 eV.
The predicted formation energy for TaBeRu2 is -0.367 eV/atom.

  1%|▊                                                                                                                                                  | 56/9610 [09:43<30:32:06, 11.51s/it]

The final energy is -37.352 eV.
The predicted PBE band gap for TaBeTc2 is -0.008 eV.
The predicted GLLB-SC band gap for TaBeTc2 is 0.857 eV.
The predicted HSE band gap for TaBeTc2 is -0.009 eV.
The predicted SCAN band gap for TaBeTc2 is 0.603 eV.
The predicted formation energy for TaBeTc2 is -0.219 eV/atom.

  1%|▊                                                                                                                                                  | 57/9610 [09:51<27:39:03, 10.42s/it]

The final energy is -32.566 eV.
The predicted PBE band gap for TaBeRh2 is -0.010 eV.
The predicted GLLB-SC band gap for TaBeRh2 is 0.142 eV.
The predicted HSE band gap for TaBeRh2 is -0.010 eV.
The predicted SCAN band gap for TaBeRh2 is 0.053 eV.
The predicted formation energy for TaBeRh2 is -0.526 eV/atom.

  1%|▉                                                                                                                                                  | 58/9610 [10:05<30:43:31, 11.58s/it]

The final energy is -33.230 eV.
The predicted PBE band gap for TaBeFe2 is -0.007 eV.
The predicted GLLB-SC band gap for TaBeFe2 is 0.549 eV.
The predicted HSE band gap for TaBeFe2 is -0.007 eV.
The predicted SCAN band gap for TaBeFe2 is 0.345 eV.
The predicted formation energy for TaBeFe2 is -0.218 eV/atom.

  1%|▉                                                                                                                                                  | 59/9610 [10:15<29:29:16, 11.11s/it]

The final energy is -34.360 eV.
The predicted PBE band gap for TaMn2Be is -0.008 eV.
The predicted GLLB-SC band gap for TaMn2Be is 0.618 eV.
The predicted HSE band gap for TaMn2Be is 0.009 eV.
The predicted SCAN band gap for TaMn2Be is 0.300 eV.
The predicted formation energy for TaMn2Be is -0.121 eV/atom.

  1%|▉                                                                                                                                                  | 60/9610 [10:26<29:30:06, 11.12s/it]

The final energy is -30.840 eV.
The predicted PBE band gap for TaBeCo2 is -0.011 eV.
The predicted GLLB-SC band gap for TaBeCo2 is 0.170 eV.
The predicted HSE band gap for TaBeCo2 is -0.011 eV.
The predicted SCAN band gap for TaBeCo2 is -0.010 eV.
The predicted formation energy for TaBeCo2 is -0.249 eV/atom.

  1%|▉                                                                                                                                                  | 61/9610 [10:34<27:00:44, 10.18s/it]

The final energy is -38.936 eV.
The predicted PBE band gap for TaBeOs2 is -0.009 eV.
The predicted GLLB-SC band gap for TaBeOs2 is 1.063 eV.
The predicted HSE band gap for TaBeOs2 is -0.008 eV.
The predicted SCAN band gap for TaBeOs2 is 0.132 eV.
The predicted formation energy for TaBeOs2 is -0.275 eV/atom.

  1%|▉                                                                                                                                                  | 62/9610 [10:42<24:44:48,  9.33s/it]

The final energy is -41.057 eV.
The predicted PBE band gap for TaBeRe2 is -0.010 eV.
The predicted GLLB-SC band gap for TaBeRe2 is -0.003 eV.
The predicted HSE band gap for TaBeRe2 is -0.011 eV.
The predicted SCAN band gap for TaBeRe2 is -0.009 eV.
The predicted formation energy for TaBeRe2 is 0.076 eV/atom.

  1%|▉                                                                                                                                                  | 63/9610 [10:53<26:37:30, 10.04s/it]

The final energy is -35.500 eV.
The predicted PBE band gap for TaBeIr2 is -0.009 eV.
The predicted GLLB-SC band gap for TaBeIr2 is 0.301 eV.
The predicted HSE band gap for TaBeIr2 is -0.010 eV.
The predicted SCAN band gap for TaBeIr2 is 0.299 eV.
The predicted formation energy for TaBeIr2 is -0.405 eV/atom.

  1%|▉                                                                                                                                                  | 64/9610 [11:05<28:22:22, 10.70s/it]

The final energy is -33.844 eV.
The predicted PBE band gap for HfBeRu2 is -0.007 eV.
The predicted GLLB-SC band gap for HfBeRu2 is 0.737 eV.
The predicted HSE band gap for HfBeRu2 is -0.007 eV.
The predicted SCAN band gap for HfBeRu2 is 0.424 eV.
The predicted formation energy for HfBeRu2 is -0.451 eV/atom.

  1%|▉                                                                                                                                                  | 65/9610 [11:14<26:27:10,  9.98s/it]

The final energy is -35.065 eV.
The predicted PBE band gap for HfBeTc2 is -0.008 eV.
The predicted GLLB-SC band gap for HfBeTc2 is 0.465 eV.
The predicted HSE band gap for HfBeTc2 is -0.010 eV.
The predicted SCAN band gap for HfBeTc2 is 0.033 eV.
The predicted formation energy for HfBeTc2 is -0.236 eV/atom.

  1%|█                                                                                                                                                  | 66/9610 [11:22<24:57:50,  9.42s/it]

The final energy is -31.515 eV.
The predicted PBE band gap for HfBeRh2 is -0.008 eV.
The predicted GLLB-SC band gap for HfBeRh2 is 0.027 eV.
The predicted HSE band gap for HfBeRh2 is -0.008 eV.
The predicted SCAN band gap for HfBeRh2 is -0.005 eV.
The predicted formation energy for HfBeRh2 is -0.768 eV/atom.

  1%|█                                                                                                                                                  | 67/9610 [11:33<26:24:16,  9.96s/it]

The final energy is -30.961 eV.
The predicted PBE band gap for HfBeFe2 is -0.007 eV.
The predicted GLLB-SC band gap for HfBeFe2 is 0.144 eV.
The predicted HSE band gap for HfBeFe2 is -0.008 eV.
The predicted SCAN band gap for HfBeFe2 is 0.134 eV.
The predicted formation energy for HfBeFe2 is -0.154 eV/atom.

  1%|█                                                                                                                                                  | 68/9610 [11:44<27:25:09, 10.34s/it]

The final energy is -31.868 eV.
The predicted PBE band gap for HfMn2Be is -0.009 eV.
The predicted GLLB-SC band gap for HfMn2Be is 0.106 eV.
The predicted HSE band gap for HfMn2Be is -0.008 eV.
The predicted SCAN band gap for HfMn2Be is 0.007 eV.
The predicted formation energy for HfMn2Be is -0.219 eV/atom.

  1%|█                                                                                                                                                  | 69/9610 [11:55<27:48:06, 10.49s/it]

The final energy is -28.943 eV.
The predicted PBE band gap for HfBeCo2 is -0.007 eV.
The predicted GLLB-SC band gap for HfBeCo2 is 0.053 eV.
The predicted HSE band gap for HfBeCo2 is -0.007 eV.
The predicted SCAN band gap for HfBeCo2 is 0.005 eV.
The predicted formation energy for HfBeCo2 is -0.431 eV/atom.

  1%|█                                                                                                                                                  | 70/9610 [12:03<25:58:23,  9.80s/it]

The final energy is -36.743 eV.
The predicted PBE band gap for HfBeOs2 is -0.007 eV.
The predicted GLLB-SC band gap for HfBeOs2 is 0.699 eV.
The predicted HSE band gap for HfBeOs2 is -0.008 eV.
The predicted SCAN band gap for HfBeOs2 is -0.012 eV.
The predicted formation energy for HfBeOs2 is -0.242 eV/atom.

  1%|█                                                                                                                                                  | 71/9610 [12:15<27:05:59, 10.23s/it]

The final energy is -38.062 eV.
The predicted PBE band gap for HfBeRe2 is -0.014 eV.
The predicted GLLB-SC band gap for HfBeRe2 is 0.504 eV.
The predicted HSE band gap for HfBeRe2 is -0.010 eV.
The predicted SCAN band gap for HfBeRe2 is 0.044 eV.
The predicted formation energy for HfBeRe2 is 0.107 eV/atom.

  1%|█                                                                                                                                                  | 72/9610 [12:30<31:29:45, 11.89s/it]

The final energy is -34.422 eV.
The predicted PBE band gap for HfBeIr2 is -0.007 eV.
The predicted GLLB-SC band gap for HfBeIr2 is 0.310 eV.
The predicted HSE band gap for HfBeIr2 is -0.008 eV.
The predicted SCAN band gap for HfBeIr2 is 0.413 eV.
The predicted formation energy for HfBeIr2 is -0.671 eV/atom.

  1%|█                                                                                                                                                  | 73/9610 [12:44<32:49:03, 12.39s/it]

The final energy is -36.001 eV.
The predicted PBE band gap for BeRu2W is -0.007 eV.
The predicted GLLB-SC band gap for BeRu2W is 0.431 eV.
The predicted HSE band gap for BeRu2W is -0.007 eV.
The predicted SCAN band gap for BeRu2W is -0.007 eV.
The predicted formation energy for BeRu2W is -0.206 eV/atom.

  1%|█▏                                                                                                                                                 | 74/9610 [12:52<29:22:27, 11.09s/it]

The final energy is -37.763 eV.
The predicted PBE band gap for BeTc2W is -0.008 eV.
The predicted GLLB-SC band gap for BeTc2W is 0.697 eV.
The predicted HSE band gap for BeTc2W is -0.009 eV.
The predicted SCAN band gap for BeTc2W is 0.575 eV.
The predicted formation energy for BeTc2W is -0.186 eV/atom.

  1%|█▏                                                                                                                                                 | 75/9610 [13:01<27:58:20, 10.56s/it]

The final energy is -32.658 eV.
The predicted PBE band gap for BeRh2W is -0.009 eV.
The predicted GLLB-SC band gap for BeRh2W is 0.137 eV.
The predicted HSE band gap for BeRh2W is -0.010 eV.
The predicted SCAN band gap for BeRh2W is -0.010 eV.
The predicted formation energy for BeRh2W is -0.239 eV/atom.
The final energy is -33.832 eV.

  1%|█▏                                                                                                                                                 | 76/9610 [13:08<25:11:22,  9.51s/it]

The predicted PBE band gap for BeFe2W is -0.007 eV.
The predicted GLLB-SC band gap for BeFe2W is 0.737 eV.
The predicted HSE band gap for BeFe2W is -0.008 eV.
The predicted SCAN band gap for BeFe2W is 0.127 eV.
The predicted formation energy for BeFe2W is -0.065 eV/atom.

  1%|█▏                                                                                                                                                 | 77/9610 [13:23<29:13:56, 11.04s/it]

The final energy is -35.070 eV.
The predicted PBE band gap for Mn2BeW is -0.008 eV.
The predicted GLLB-SC band gap for Mn2BeW is 0.547 eV.
The predicted HSE band gap for Mn2BeW is -0.004 eV.
The predicted SCAN band gap for Mn2BeW is 0.215 eV.
The predicted formation energy for Mn2BeW is -0.052 eV/atom.

  1%|█▏                                                                                                                                                 | 78/9610 [13:33<28:40:14, 10.83s/it]

The final energy is -31.392 eV.
The predicted PBE band gap for BeCo2W is -0.006 eV.
The predicted GLLB-SC band gap for BeCo2W is 0.792 eV.
The predicted HSE band gap for BeCo2W is -0.009 eV.
The predicted SCAN band gap for BeCo2W is 0.058 eV.
The predicted formation energy for BeCo2W is -0.149 eV/atom.

  1%|█▏                                                                                                                                                 | 78/9610 [13:39<27:48:17, 10.50s/it]

KeyboardInterrupt:

In [209]:
for s in new_structures:
    print(s.composition.reduced_formula)

BeNbRu2
BeNbTc2
BeNbRh2
BeNbFe2
Mn2BeNb
BeNbCo2
BeNbOs2
BeNbRe2
BeNbIr2
ZrBeRu2
ZrBeTc2
ZrBeRh2
ZrBeFe2
ZrMn2Be
ZrBeCo2
ZrBeOs2
ZrBeRe2
ZrBeIr2
BeMoRu2
BeTc2Mo
BeMoRh2
BeFe2Mo
Mn2BeMo
BeCo2Mo
BeMoOs2
BeRe2Mo
BeMoIr2
BeVRu2
BeVTc2
BeVRh2
BeVFe2
Mn2BeV
BeVCo2
BeVOs2
BeVRe2
BeVIr2
TiBeRu2
TiBeTc2
TiBeRh2
TiBeFe2
TiMn2Be
TiBeCo2
TiBeOs2
TiBeRe2
TiBeIr2
BeCrRu2
BeCrTc2
BeCrRh2
BeCrFe2
Mn2BeCr
BeCrCo2
BeCrOs2
BeCrRe2
BeCrIr2
TaBeRu2
TaBeTc2
TaBeRh2
TaBeFe2
TaMn2Be
TaBeCo2
TaBeOs2
TaBeRe2
TaBeIr2
HfBeRu2
HfBeTc2
HfBeRh2
HfBeFe2
HfMn2Be
HfBeCo2
HfBeOs2
HfBeRe2
HfBeIr2
BeRu2W
BeTc2W
BeRh2W
BeFe2W
Mn2BeW
BeCo2W
BeOs2W
BeRe2W
BeIr2W
BeSiRu2
BeSiTc2
BeSiRh2
BeFe2Si
Mn2BeSi
BeCo2Si
BeSiOs2
BeRe2Si
BeSiIr2
BeAlRu2
BeAlTc2
BeAlRh2
BeAlFe2
Mn2BeAl
BeAlCo2
BeAlOs2
BeAlRe2
BeAlIr2
TiBeRu2
TiBeTc2
TiBeRh2
TiBeFe2
TiMn2Be
TiBeCo2
TiBeOs2
TiBeRe2
TiBeIr2
ScBeRu2
ScBeTc2
ScBeRh2
ScBeFe2
ScMn2Be
ScBeCo2
ScBeOs2
ScBeRe2
ScBeIr2
BeVRu2
BeVTc2
BeVRh2
BeVFe2
Mn2BeV
BeVCo2
BeVOs2
BeVRe2
BeVIr2
Be12V
TiBe12
Be12Cr
Be12Nb
ZrBe12
Be12Mo
Be12Nb
ZrBe12
Be12Mo
Be12V
TiBe12
Be12Cr
TaBe12
HfBe12
Be12W
Be12W
TaBe12
Be12Re
Be12Mo
Be12Nb
Be12Tc
TaBe12
HfBe12
Be12W
Be12Nb
ZrBe12
Be12Mo
BeGeRu2
BeTc2Ge
BeGeRh2
BeFe2Ge
Mn2BeGe
BeCo2Ge
BeGeOs2
BeRe2Ge
BeGeIr2
BeGaRu2
BeGaTc2
BeGaRh2
BeGaFe2
Mn2BeGa
BeGaCo2
BeGaOs2
BeGaRe2
BeGaIr2
BeAsRu2
BeTc2As
BeAsRh2
BeFe2As
Mn2BeAs
BeCo2As
BeAsOs2
BeRe2As
BeAsIr2
BeSnRu2
BeTc2Sn
BeSnRh2
BeFe2Sn
Mn2BeSn
BeCo2Sn
BeSnOs2
BeRe2Sn
BeSnIr2
BeInRu2
BeInTc2
BeInRh2
BeInFe2
Mn2BeIn
BeInCo2
BeInOs2
BeInRe2
BeInIr2
BeSbRu2
BeTc2Sb
BeSbRh2
BeFe2Sb
Mn2BeSb
BeCo2Sb
BeSbOs2
BeRe2Sb
BeSbIr2
BeRu2W
TaBeRu2
BeReRu2
BeMoRu2
BeNbRu2
BeTcRu2
BeTc2W
TaBeTc2
BeReTc2
BeTc2Mo
BeNbTc2
BeTc3
BeRh2W
TaBeRh2
BeReRh2
BeMoRh2
BeNbRh2
BeTcRh2
BeFe2W
TaBeFe2
BeFe2Re
BeFe2Mo
BeNbFe2
BeFe2Tc
Mn2BeW
TaMn2Be
Mn2BeRe
Mn2BeMo
Mn2BeNb
Mn2BeTc
BeCo2W
TaBeCo2
BeCo2Re
BeCo2Mo
BeNbCo2
BeCo2Tc
BeOs2W
TaBeOs2
BeReOs2
BeMoOs2
BeNbOs2
BeTcOs2
BeRe2W
TaBeRe2
BeRe3
BeRe2Mo
BeNbRe2
BeRe2Tc
BeIr2W
TaBeIr2
BeReIr2
BeMoIr2
BeNbIr2
BeTcIr2
Be2PtRh
Be2RuPt
Be2PdPt
Be2CoPt
Be2FePt
Be2NiPt
Be2IrPt
Be2OsPt
BePt
Be2IrRh
Be2IrRu
Be2IrPd
Be2CoIr
Be2FeIr
Be2NiIr
BeIr
Be2IrOs
Be2IrPt
Be2RhAu
Be2RuAu
Be2PdAu
Be2CoAu
Be2FeAu
Be2NiAu
Be2IrAu
Be2OsAu
Be2PtAu
Be2PdRh
Be2PdRu
BePd
Be2CoPd
Be2FePd
Be2NiPd
Be2IrPd
Be2OsPd
Be2PdPt
BeRh
Be2RuRh
Be2PdRh
Be2CoRh
Be2FeRh
Be2NiRh
Be2IrRh
Be2OsRh
Be2PtRh
Be2AgRh
Be2AgRu
Be2AgPd
Be2CoAg
Be2FeAg
Be2NiAg
Be2AgIr
Be2AgOs
Be2AgPt
LiBe2Ir
LiBe2Os
LiBe2Pt
LiBe2Rh
LiBe2Ru
LiBe2Pd
Be3Ir
Be3Os
Be3Pt
Be3Rh
Be3Ru
Be3Pd
Be2HIr
Be2HOs
Be2HPt
Be2HRh
Be2HRu
Be2HPd
NaBe2Ir
NaBe2Os
NaBe2Pt
NaBe2Rh
NaBe2Ru
NaBe2Pd
MgBe2Ir
MgBe2Os
MgBe2Pt
MgBe2Rh
MgBe2Ru
MgBe2Pd
LiBePd2
LiBeRh2
LiBeAg2
LiBeNi2
LiBeCo2
LiBeCu2
LiBePt2
LiBeIr2
LiBeAu2
BePd
BeRh
BeAg
BeNi
BeCo
BeCu
BePt
BeIr
BeAu
BeHPd2
BeHRh2
BeAg2H
BeNi2H
BeCo2H
BeCu2H
BeHPt2
BeHIr2
BeHAu2
NaBePd2
NaBeRh2
NaBeAg2
NaBeNi2
NaBeCo2
NaBeCu2
NaBePt2
NaBeIr2
NaBeAu2
MgBePd2
MgBeRh2
MgBeAg2
MgBeNi2
MgBeCo2
MgBeCu2
MgBePt2
MgBeIr2
MgBeAu2
BeGaRh2
BeGaRu2
BeGaPd2
BeGaCo2
BeGaFe2
BeGaNi2
BeGaIr2
BeGaOs2
BeGaPt2
BeZnRh2
BeZnRu2
BeZnPd2
BeZnCo2
BeZnFe2
BeZnNi2
BeZnIr2
BeZnOs2
BeZnPt2
BeGeRh2
BeGeRu2
BeGePd2
BeCo2Ge
BeFe2Ge
BeNi2Ge
BeGeIr2
BeGeOs2
BeGePt2
BeInRh2
BeInRu2
BeInPd2
BeInCo2
BeInFe2
BeInNi2
BeInIr2
BeInOs2
BeInPt2
BeCdRh2
BeCdRu2
BeCdPd2
BeCdCo2
BeCdFe2
BeCdNi2
BeCdIr2
BeCdOs2
BeCdPt2
BeSnRh2
BeSnRu2
BeSnPd2
BeCo2Sn
BeFe2Sn
BeNi2Sn
BeSnIr2
BeSnOs2
BeSnPt2
BeAlRh2
BeAlRu2
BeAlPd2
BeAlCo2
BeAlFe2
BeAlNi2
BeAlIr2
BeAlOs2
BeAlPt2
MgBeRh2
MgBeRu2
MgBePd2
MgBeCo2
MgBeFe2
MgBeNi2
MgBeIr2
MgBeOs2
MgBePt2
BeSiRh2
BeSiRu2
BeSiPd2
BeCo2Si
BeFe2Si
BeSiNi2
BeSiIr2
BeSiOs2
BeSiPt2
BeBRh2
BeBRu2
BeBPd2
BeCo2B
BeFe2B
BeNi2B
BeBIr2
BeBOs2
BeBPt2
BeRh
BeRu
BePd
BeCo
BeFe
BeNi
BeIr
BeOs
BePt
ScBeRh2
ScBeRu2
ScBePd2
ScBeCo2
ScBeFe2
ScBeNi2
ScBeIr2
ScBeOs2
ScBePt2
CaBeRh2
CaBeRu2
CaBePd2
CaBeCo2
CaBeFe2
CaBeNi2
CaBeIr2
CaBeOs2
CaBePt2
TiBeRh2
TiBeRu2
TiBePd2
TiBeCo2
TiBeFe2
TiBeNi2
TiBeIr2
TiBeOs2
TiBePt2
Ti2MnBe
Ti2BeCr
Ti2BeFe
Ti2BeTc
Ti2BeMo
Ti2BeRu
Sc2MnBe
Sc2BeCr
Sc2BeFe
Sc2BeTc
Sc2BeMo
Sc2BeRu
MnBeV2
BeV2Cr
BeV2Fe
BeV2Tc
BeV2Mo
BeV2Ru
MnBeSi2
BeCrSi2
BeFeSi2
BeSi2Tc
BeSi2Mo
BeSi2Ru
MnBeAl2
BeAl2Cr
BeAl2Fe
BeAl2Tc
BeAl2Mo
BeAl2Ru
Zr2MnBe
Zr2BeCr
Zr2BeFe
Zr2BeTc
Zr2BeMo
Zr2BeRu
Y2MnBe
Y2BeCr
Y2BeFe
Y2BeTc
Y2BeMo
Y2BeRu
MnBeNb2
BeNb2Cr
BeNb2Fe
BeNb2Tc
BeNb2Mo
BeNb2Ru
Be5Pd
Be5Rh
Be5Ag
Be5Ni
Be5Co
Be5Cu
Be5Pt
Be5Ir
Be5Au
Be2CuIr
Be2CuOs
Be2CuPt
Be2CuRh
Be2CuRu
Be2CuPd
Be2NiIr
Be2NiOs
Be2NiPt
Be2NiRh
Be2NiRu
Be2NiPd
Be2ZnIr
Be2ZnOs
Be2ZnPt
Be2ZnRh
Be2ZnRu
Be2ZnPd
Be2AgIr
Be2AgOs
Be2AgPt
Be2AgRh
Be2AgRu
Be2AgPd
Be2IrPd
Be2OsPd
Be2PdPt
Be2PdRh
Be2PdRu
BePd
Be2CdIr
Be2CdOs
Be2CdPt
Be2CdRh
Be2CdRu
Be2CdPd
Be2IrPt
BeIr
Be2IrAu
Be2IrPd
Be2IrRh
Be2AgIr
Be2OsPt
Be2IrOs
Be2OsAu
Be2OsPd
Be2OsRh
Be2AgOs
BePt
Be2IrPt
Be2PtAu
Be2PdPt
Be2PtRh
Be2AgPt
Be2PtRh
Be2IrRh
Be2RhAu
Be2PdRh
BeRh
Be2AgRh
Be2RuPt
Be2IrRu
Be2RuAu
Be2PdRu
Be2RuRh
Be2AgRu
Be2PdPt
Be2IrPd
Be2PdAu
BePd
Be2PdRh
Be2AgPd
BeVFe2
Mn2BeV
BeVCo2
BeVRu2
BeVTc2
BeVRh2
TiBeFe2
TiMn2Be
TiBeCo2
TiBeRu2
TiBeTc2
TiBeRh2
BeCrFe2
Mn2BeCr
BeCrCo2
BeCrRu2
BeCrTc2
BeCrRh2
BeNbFe2
Mn2BeNb
BeNbCo2
BeNbRu2
BeNbTc2
BeNbRh2
ZrBeFe2
ZrMn2Be
ZrBeCo2
ZrBeRu2
ZrBeTc2
ZrBeRh2
BeFe2Mo
Mn2BeMo
BeCo2Mo
BeMoRu2
BeTc2Mo
BeMoRh2
BeSiRh2
BeSiRu2
BeSiPd2
BeCo2Si
BeFe2Si
BeSiNi2
BeSiIr2
BeSiOs2
BeSiPt2
BeAlRh2
BeAlRu2
BeAlPd2
BeAlCo2
BeAlFe2
BeAlNi2
BeAlIr2
BeAlOs2
BeAlPt2
TiBeRh2
TiBeRu2
TiBePd2
TiBeCo2
TiBeFe2
TiBeNi2
TiBeIr2
TiBeOs2
TiBePt2
ScBeRh2
ScBeRu2
ScBePd2
ScBeCo2
ScBeFe2
ScBeNi2
ScBeIr2
ScBeOs2
ScBePt2
BeVRh2
BeVRu2
BeVPd2
BeVCo2
BeVFe2
BeVNi2
BeVIr2
BeVOs2
BeVPt2
Be3Ir
Be3Os
Be3Pt
Be3Rh
Be3Ru
Be3Pd
Be2Mo
Be2Nb
Be2Tc
Be2Cr
Be2V
MnBe2
Be2W
TaBe2
Be2Re
Be12Mo
Be12Nb
Be12Tc
Be12Cr
Be12V
MnBe12
Be12W
TaBe12
Be12Re
BePd3
BePdRh2
BeAg2Pd
BeNi2Pd
BeCo2Pd
BeCu2Pd
BePdPt2
BeIr2Pd
BePdAu2
BePd2
BeRh2
BeAg2
BeNi2
BeCo2
BeCu2
BePt2
BeIr2
BeAu2
HfBe5
LaBe5
TaBe5
ZrBe5
YBe5
Be5Nb
BeAu2
BePt2
BeHg2
BeAg2
BePd2
BeCd2
HfBeSi
HfBeAl
HfTiBe
HfScBe
HfBeV
LaBeSi
LaBeAl
LaTiBe
LaScBe
LaBeV
TaBeSi
TaBeAl
TaTiBe
ScTaBe
TaBeV
ZrBeSi
ZrBeAl
ZrTiBe
ZrScBe
ZrBeV
YBeSi
YBeAl
YTiBe
YScBe
YBeV
BeNbSi
BeNbAl
TiBeNb
ScBeNb
BeNbV
Be2Cu
Be2Ni
Be2Zn
Be2Ag
Be2Pd
Be2Cd
Be2Fe
MnBe2
Be2Co
Be2Ru
Be2Tc
Be2Rh
Be2Cr
Be2V
MnBe2
Be2Mo
Be2Nb
Be2Tc
BeCo
BeFe
BeNi
BeRh
BeRu
BePd
TiBe2
ScBe2
Be2V
Be2Si
Be2Al
ZrBe2
YBe2
Be2Nb
Be3Rh
Be3Ru
Be3Pd
Be3Co
Be3Fe
Be3Ni
Be3Ir
Be3Os
Be3Pt
MnBe2Rh
MnBe2Ru
MnBe2Pd
MnBe2Co
MnBe2Fe
MnBe2Ni
MnBe2Ir
MnBe2Os
MnBe2Pt
Be2CrRh
Be2CrRu
Be2CrPd
Be2CrCo
Be2CrFe
Be2CrNi
Be2CrIr
Be2CrOs
Be2CrPt
Be2FeRh
Be2FeRu
Be2FePd
Be2FeCo
BeFe
Be2FeNi
Be2FeIr
Be2FeOs
Be2FePt
Be2TcRh
Be2TcRu
Be2TcPd
Be2CoTc
Be2FeTc
Be2TcNi
Be2TcIr
Be2TcOs
Be2TcPt
Be2MoRh
Be2MoRu
Be2MoPd
Be2CoMo
Be2FeMo
Be2NiMo
Be2MoIr
Be2MoOs
Be2MoPt
Be2RuRh
BeRu
Be2PdRu
Be2CoRu
Be2FeRu
Be2NiRu
Be2IrRu
Be2OsRu
Be2RuPt
Be2PdPt
Be2IrPd
Be2PdAu
BePd
Be2PdRh
Be2AgPd
Be2PtRh
Be2IrRh
Be2RhAu
Be2PdRh
BeRh
Be2AgRh
Be2AgPt
Be2AgIr
Be2AgAu
Be2AgPd
Be2AgRh
BeAg
Be2NiPt
Be2NiIr
Be2NiAu
Be2NiPd
Be2NiRh
Be2NiAg
Be2CoPt
Be2CoIr
Be2CoAu
Be2CoPd
Be2CoRh
Be2CoAg
Be2CuPt
Be2CuIr
Be2CuAu
Be2CuPd
Be2CuRh
Be2CuAg
BePt
Be2IrPt
Be2PtAu
Be2PdPt
Be2PtRh
Be2AgPt
Be2IrPt
BeIr
Be2IrAu
Be2IrPd
Be2IrRh
Be2AgIr
Be2PtAu
Be2IrAu
BeAu
Be2PdAu
Be2RhAu
Be2AgAu
Be2IrRu
Be2TcIr
Be2IrRh
Be2FeIr
MnBe2Ir
Be2CoIr
Be2IrOs
Be2ReIr
BeIr
Be2OsRu
Be2TcOs
Be2OsRh
Be2FeOs
MnBe2Os
Be2CoOs
BeOs
Be2ReOs
Be2IrOs
Be2RuPt
Be2TcPt
Be2PtRh
Be2FePt
MnBe2Pt
Be2CoPt
Be2OsPt
Be2RePt
Be2IrPt
Be2RuRh
Be2TcRh
BeRh
Be2FeRh
MnBe2Rh
Be2CoRh
Be2OsRh
Be2ReRh
Be2IrRh
BeRu
Be2TcRu
Be2RuRh
Be2FeRu
MnBe2Ru
Be2CoRu
Be2OsRu
Be2ReRu
Be2IrRu
Be2PdRu
Be2TcPd
Be2PdRh
Be2FePd
MnBe2Pd
Be2CoPd
Be2OsPd
Be2RePd
Be2IrPd
MnBeIr2
MnBeOs2
MnBePt2
MnBeRh2
MnBeRu2
MnBePd2
BeCrIr2
BeCrOs2
BeCrPt2
BeCrRh2
BeCrRu2
BeCrPd2
BeFeIr2
BeFeOs2
BeFePt2
BeFeRh2
BeFeRu2
BeFePd2
BeTcIr2
BeTcOs2
BeTcPt2
BeTcRh2
BeTcRu2
BeTcPd2
BeMoIr2
BeMoOs2
BeMoPt2
BeMoRh2
BeMoRu2
BeMoPd2
BeIr2Ru
BeOs2Ru
BeRuPt2
BeRuRh2
BeRu3
BePd2Ru
LiBePt2
LiBeIr2
LiBeAu2
LiBePd2
LiBeRh2
LiBeAg2
BePt
BeIr
BeAu
BePd
BeRh
BeAg
BeHPt2
BeHIr2
BeHAu2
BeHPd2
BeHRh2
BeAg2H
NaBePt2
NaBeIr2
NaBeAu2
NaBePd2
NaBeRh2
NaBeAg2
MgBePt2
MgBeIr2
MgBeAu2
MgBePd2
MgBeRh2
MgBeAg2
Be2RuAu
Be2RuPt
Be2HgRu
Be2AgRu
Be2PdRu
Be2CdRu
Be2TcAu
Be2TcPt
Be2TcHg
Be2TcAg
Be2TcPd
Be2CdTc
Be2RhAu
Be2PtRh
Be2HgRh
Be2AgRh
Be2PdRh
Be2CdRh
Be2FeAu
Be2FePt
Be2FeHg
Be2FeAg
Be2FePd
Be2CdFe
MnBe2Au
MnBe2Pt
MnBe2Hg
MnBe2Ag
MnBe2Pd
MnBe2Cd
Be2CoAu
Be2CoPt
Be2CoHg
Be2CoAg
Be2CoPd
Be2CdCo
Be2OsAu
Be2OsPt
Be2HgOs
Be2AgOs
Be2OsPd
Be2CdOs
Be2ReAu
Be2RePt
Be2ReHg
Be2ReAg
Be2RePd
Be2CdRe
Be2IrAu
Be2IrPt
Be2HgIr
Be2AgIr
Be2IrPd
Be2CdIr
BeVOs2
BeVRe2
BeVIr2
BeVRu2
BeVTc2
BeVRh2
TiBeOs2
TiBeRe2
TiBeIr2
TiBeRu2
TiBeTc2
TiBeRh2
BeCrOs2
BeCrRe2
BeCrIr2
BeCrRu2
BeCrTc2
BeCrRh2
BeNbOs2
BeNbRe2
BeNbIr2
BeNbRu2
BeNbTc2
BeNbRh2
ZrBeOs2
ZrBeRe2
ZrBeIr2
ZrBeRu2
ZrBeTc2
ZrBeRh2
BeMoOs2
BeRe2Mo
BeMoIr2
BeMoRu2
BeTc2Mo
BeMoRh2
Be2CoIr
Be2CoOs
Be2CoPt
Be2CoRh
Be2CoRu
Be2CoPd
Be2FeIr
Be2FeOs
Be2FePt
Be2FeRh
Be2FeRu
Be2FePd
Be2NiIr
Be2NiOs
Be2NiPt
Be2NiRh
Be2NiRu
Be2NiPd
Be2IrRh
Be2OsRh
Be2PtRh
BeRh
Be2RuRh
Be2PdRh
Be2IrRu
Be2OsRu
Be2RuPt
Be2RuRh
BeRu
Be2PdRu
Be2IrPd
Be2OsPd
Be2PdPt
Be2PdRh
Be2PdRu
BePd
Be2CoNi
BeCo
Be2CoCu
Be2CoPd
Be2CoRh
Be2CoAg
Be2FeNi
Be2FeCo
Be2FeCu
Be2FePd
Be2FeRh
Be2FeAg
BeNi
Be2CoNi
Be2CuNi
Be2NiPd
Be2NiRh
Be2NiAg
Be2NiRh
Be2CoRh
Be2CuRh
Be2PdRh
BeRh
Be2AgRh
Be2NiRu
Be2CoRu
Be2CuRu
Be2PdRu
Be2RuRh
Be2AgRu
Be2NiPd
Be2CoPd
Be2CuPd
BePd
Be2PdRh
Be2AgPd
Be2CoPt
Be2CoIr
Be2CoAu
Be2CoPd
Be2CoRh
Be2CoAg
Be2FePt
Be2FeIr
Be2FeAu
Be2FePd
Be2FeRh
Be2FeAg
Be2NiPt
Be2NiIr
Be2NiAu
Be2NiPd
Be2NiRh
Be2NiAg
Be2PtRh
Be2IrRh
Be2RhAu
Be2PdRh
BeRh
Be2AgRh
Be2RuPt
Be2IrRu
Be2RuAu
Be2PdRu
Be2RuRh
Be2AgRu
Be2PdPt
Be2IrPd
Be2PdAu
BePd
Be2PdRh
Be2AgPd
BeGaIr2
BeGaOs2
BeGaPt2
BeGaRh2
BeGaRu2
BeGaPd2
BeZnIr2
BeZnOs2
BeZnPt2
BeZnRh2
BeZnRu2
BeZnPd2
BeGeIr2
BeGeOs2
BeGePt2
BeGeRh2
BeGeRu2
BeGePd2
BeInIr2
BeInOs2
BeInPt2
BeInRh2
BeInRu2
BeInPd2
BeCdIr2
BeCdOs2
BeCdPt2
BeCdRh2
BeCdRu2
BeCdPd2
BeSnIr2
BeSnOs2
BeSnPt2
BeSnRh2
BeSnRu2
BeSnPd2
TaBeRu2
TaBeTc2
TaBeRh2
TaBeFe2
TaMn2Be
TaBeCo2
TaBeOs2
TaBeRe2
TaBeIr2
HfBeRu2
HfBeTc2
HfBeRh2
HfBeFe2
HfMn2Be
HfBeCo2
HfBeOs2
HfBeRe2
HfBeIr2
BeRu2W
BeTc2W
BeRh2W
BeFe2W
Mn2BeW
BeCo2W
BeOs2W
BeRe2W
BeIr2W
BeNbRu2
BeNbTc2
BeNbRh2
BeNbFe2
Mn2BeNb
BeNbCo2
BeNbOs2
BeNbRe2
BeNbIr2
ZrBeRu2
ZrBeTc2
ZrBeRh2
ZrBeFe2
ZrMn2Be
ZrBeCo2
ZrBeOs2
ZrBeRe2
ZrBeIr2
BeMoRu2
BeTc2Mo
BeMoRh2
BeFe2Mo
Mn2BeMo
BeCo2Mo
BeMoOs2
BeRe2Mo
BeMoIr2
BeSiOs2
BeRe2Si
BeSiIr2
BeSiRu2
BeSiTc2
BeSiRh2
BeAlOs2
BeAlRe2
BeAlIr2
BeAlRu2
BeAlTc2
BeAlRh2
TiBeOs2
TiBeRe2
TiBeIr2
TiBeRu2
TiBeTc2
TiBeRh2
ScBeOs2
ScBeRe2
ScBeIr2
ScBeRu2
ScBeTc2
ScBeRh2
BeVOs2
BeVRe2
BeVIr2
BeVRu2
BeVTc2
BeVRh2
BeVCo2
BeVFe2
BeVNi2
BeVRh2
BeVRu2
BeVPd2
TiBeCo2
TiBeFe2
TiBeNi2
TiBeRh2
TiBeRu2
TiBePd2
BeCrCo2
BeCrFe2
BeCrNi2
BeCrRh2
BeCrRu2
BeCrPd2
BeNbCo2
BeNbFe2
BeNbNi2
BeNbRh2
BeNbRu2
BeNbPd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeRh2
ZrBeRu2
ZrBePd2
BeCo2Mo
BeFe2Mo
BeNi2Mo
BeMoRh2
BeMoRu2
BeMoPd2
Be2NiPt
Be2NiIr
Be2NiAu
Be2NiPd
Be2NiRh
Be2NiAg
Be2CoPt
Be2CoIr
Be2CoAu
Be2CoPd
Be2CoRh
Be2CoAg
Be2CuPt
Be2CuIr
Be2CuAu
Be2CuPd
Be2CuRh
Be2CuAg
Be2PdPt
Be2IrPd
Be2PdAu
BePd
Be2PdRh
Be2AgPd
Be2PtRh
Be2IrRh
Be2RhAu
Be2PdRh
BeRh
Be2AgRh
Be2AgPt
Be2AgIr
Be2AgAu
Be2AgPd
Be2AgRh
BeAg
TiBeIr2
TiBeOs2
TiBePt2
TiBeRh2
TiBeRu2
TiBePd2
ScBeIr2
ScBeOs2
ScBePt2
ScBeRh2
ScBeRu2
ScBePd2
BeVIr2
BeVOs2
BeVPt2
BeVRh2
BeVRu2
BeVPd2
BeSiIr2
BeSiOs2
BeSiPt2
BeSiRh2
BeSiRu2
BeSiPd2
BeAlIr2
BeAlOs2
BeAlPt2
BeAlRh2
BeAlRu2
BeAlPd2
ZrBeIr2
ZrBeOs2
ZrBePt2
ZrBeRh2
ZrBeRu2
ZrBePd2
YBeIr2
YBeOs2
YBePt2
YBeRh2
YBeRu2
YBePd2
BeNbIr2
BeNbOs2
BeNbPt2
BeNbRh2
BeNbRu2
BeNbPd2
TiBeCo2
TiBeFe2
TiBeNi2
TiBeRh2
TiBeRu2
TiBePd2
ScBeCo2
ScBeFe2
ScBeNi2
ScBeRh2
ScBeRu2
ScBePd2
BeVCo2
BeVFe2
BeVNi2
BeVRh2
BeVRu2
BeVPd2
BeCo2Si
BeFe2Si
BeSiNi2
BeSiRh2
BeSiRu2
BeSiPd2
BeAlCo2
BeAlFe2
BeAlNi2
BeAlRh2
BeAlRu2
BeAlPd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeRh2
ZrBeRu2
ZrBePd2
YBeCo2
YBeFe2
YBeNi2
YBeRh2
YBeRu2
YBePd2
BeNbCo2
BeNbFe2
BeNbNi2
BeNbRh2
BeNbRu2
BeNbPd2
TiBeRh2
TiBeRu2
TiBePd2
TiBeCo2
TiBeFe2
TiBeNi2
TiBeIr2
TiBeOs2
TiBePt2
ScBeRh2
ScBeRu2
ScBePd2
ScBeCo2
ScBeFe2
ScBeNi2
ScBeIr2
ScBeOs2
ScBePt2
BeVRh2
BeVRu2
BeVPd2
BeVCo2
BeVFe2
BeVNi2
BeVIr2
BeVOs2
BeVPt2
BeSiRh2
BeSiRu2
BeSiPd2
BeCo2Si
BeFe2Si
BeSiNi2
BeSiIr2
BeSiOs2
BeSiPt2
BeAlRh2
BeAlRu2
BeAlPd2
BeAlCo2
BeAlFe2
BeAlNi2
BeAlIr2
BeAlOs2
BeAlPt2
ZrBeRh2
ZrBeRu2
ZrBePd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeIr2
ZrBeOs2
ZrBePt2
YBeRh2
YBeRu2
YBePd2
YBeCo2
YBeFe2
YBeNi2
YBeIr2
YBeOs2
YBePt2
BeNbRh2
BeNbRu2
BeNbPd2
BeNbCo2
BeNbFe2
BeNbNi2
BeNbIr2
BeNbOs2
BeNbPt2
TiBe2Ir
TiBe2Os
TiBe2Pt
TiBe2Rh
TiBe2Ru
TiBe2Pd
ScBe2Ir
ScBe2Os
ScBe2Pt
ScBe2Rh
ScBe2Ru
ScBe2Pd
Be2VIr
Be2VOs
Be2VPt
Be2VRh
Be2VRu
Be2VPd
Be2SiIr
Be2SiOs
Be2SiPt
Be2SiRh
Be2SiRu
Be2SiPd
Be2AlIr
Be2AlOs
Be2AlPt
Be2AlRh
Be2AlRu
Be2AlPd
ZrBe2Ir
ZrBe2Os
ZrBe2Pt
ZrBe2Rh
ZrBe2Ru
ZrBe2Pd
YBe2Ir
YBe2Os
YBe2Pt
YBe2Rh
YBe2Ru
YBe2Pd
Be2NbIr
Be2NbOs
Be2NbPt
Be2NbRh
Be2NbRu
Be2NbPd
BeSiIr2
BeSiOs2
BeSiPt2
BeSiRh2
BeSiRu2
BeSiPd2
BeAlIr2
BeAlOs2
BeAlPt2
BeAlRh2
BeAlRu2
BeAlPd2
TiBeIr2
TiBeOs2
TiBePt2
TiBeRh2
TiBeRu2
TiBePd2
ScBeIr2
ScBeOs2
ScBePt2
ScBeRh2
ScBeRu2
ScBePd2
BeVIr2
BeVOs2
BeVPt2
BeVRh2
BeVRu2
BeVPd2
BeCo2Si
BeAlCo2
TiBeCo2
ScBeCo2
BeVCo2
BeFe2Si
BeAlFe2
TiBeFe2
ScBeFe2
BeVFe2
BeSiNi2
BeAlNi2
TiBeNi2
ScBeNi2
BeVNi2
BeSiRh2
BeAlRh2
TiBeRh2
ScBeRh2
BeVRh2
BeSiRu2
BeAlRu2
TiBeRu2
ScBeRu2
BeVRu2
BeSiPd2
BeAlPd2
TiBePd2
ScBePd2
BeVPd2
Be2CuPt
Be2CuIr
Be2CuAu
Be2CuPd
Be2CuRh
Be2CuAg
Be2NiPt
Be2NiIr
Be2NiAu
Be2NiPd
Be2NiRh
Be2NiAg
Be2ZnPt
Be2ZnIr
Be2ZnAu
Be2ZnPd
Be2ZnRh
Be2ZnAg
Be2AgPt
Be2AgIr
Be2AgAu
Be2AgPd
Be2AgRh
BeAg
Be2PdPt
Be2IrPd
Be2PdAu
BePd
Be2PdRh
Be2AgPd
Be2CdPt
Be2CdIr
Be2CdAu
Be2CdPd
Be2CdRh
Be2CdAg
Be3Ru
Be3Tc
Be3Rh
Be3Fe
MnBe3
Be3Co
Be3Os
Be3Re
Be3Ir
Be2CuRh
Be2CuRu
Be2CuPd
Be2CoCu
Be2FeCu
Be2CuNi
Be2CuIr
Be2CuOs
Be2CuPt
Be2NiRh
Be2NiRu
Be2NiPd
Be2CoNi
Be2FeNi
BeNi
Be2NiIr
Be2NiOs
Be2NiPt
Be2ZnRh
Be2ZnRu
Be2ZnPd
Be2ZnCo
Be2ZnFe
Be2ZnNi
Be2ZnIr
Be2ZnOs
Be2ZnPt
Be2AgRh
Be2AgRu
Be2AgPd
Be2CoAg
Be2FeAg
Be2NiAg
Be2AgIr
Be2AgOs
Be2AgPt
Be2PdRh
Be2PdRu
BePd
Be2CoPd
Be2FePd
Be2NiPd
Be2IrPd
Be2OsPd
Be2PdPt
Be2CdRh
Be2CdRu
Be2CdPd
Be2CdCo
Be2CdFe
Be2CdNi
Be2CdIr
Be2CdOs
Be2CdPt
Be3Ni
Be3Co
Be3Cu
Be3Pd
Be3Rh
Be3Ag
HfBeRh2
HfBeRu2
HfBePd2
HfBeCo2
HfBeFe2
HfBeNi2
HfBeIr2
HfBeOs2
HfBePt2
LaBeRh2
LaBeRu2
LaBePd2
LaBeCo2
LaBeFe2
LaBeNi2
LaBeIr2
LaBeOs2
LaBePt2
TaBeRh2
TaBeRu2
TaBePd2
TaBeCo2
TaBeFe2
TaBeNi2
TaBeIr2
TaBeOs2
TaBePt2
ZrBeRh2
ZrBeRu2
ZrBePd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeIr2
ZrBeOs2
ZrBePt2
YBeRh2
YBeRu2
YBePd2
YBeCo2
YBeFe2
YBeNi2
YBeIr2
YBeOs2
YBePt2
BeNbRh2
BeNbRu2
BeNbPd2
BeNbCo2
BeNbFe2
BeNbNi2
BeNbIr2
BeNbOs2
BeNbPt2
Be2IrPd
Be2IrRh
Be2AgIr
Be2NiIr
Be2CoIr
Be2CuIr
Be2IrPt
BeIr
Be2IrAu
Be2OsPd
Be2OsRh
Be2AgOs
Be2NiOs
Be2CoOs
Be2CuOs
Be2OsPt
Be2IrOs
Be2OsAu
Be2PdPt
Be2PtRh
Be2AgPt
Be2NiPt
Be2CoPt
Be2CuPt
BePt
Be2IrPt
Be2PtAu
Be2PdRh
BeRh
Be2AgRh
Be2NiRh
Be2CoRh
Be2CuRh
Be2PtRh
Be2IrRh
Be2RhAu
Be2PdRu
Be2RuRh
Be2AgRu
Be2NiRu
Be2CoRu
Be2CuRu
Be2RuPt
Be2IrRu
Be2RuAu
BePd
Be2PdRh
Be2AgPd
Be2NiPd
Be2CoPd
Be2CuPd
Be2PdPt
Be2IrPd
Be2PdAu
Be3Tc
Be3Mo
Be3Ru
MnBe3
Be3Cr
Be3Fe
Be3Re
Be3W
Be3Os
BeFe2Si
BeAlFe2
TiBeFe2
ScBeFe2
BeVFe2
Mn2BeSi
Mn2BeAl
TiMn2Be
ScMn2Be
Mn2BeV
BeCo2Si
BeAlCo2
TiBeCo2
ScBeCo2
BeVCo2
BeSiRu2
BeAlRu2
TiBeRu2
ScBeRu2
BeVRu2
BeSiTc2
BeAlTc2
TiBeTc2
ScBeTc2
BeVTc2
BeSiRh2
BeAlRh2
TiBeRh2
ScBeRh2
BeVRh2
BeCo2Ge
BeGaCo2
BeCo2As
BeCo2Sn
BeInCo2
BeCo2Sb
BeFe2Ge
BeGaFe2
BeFe2As
BeFe2Sn
BeInFe2
BeFe2Sb
BeNi2Ge
BeGaNi2
BeNi2As
BeNi2Sn
BeInNi2
BeNi2Sb
BeGeRh2
BeGaRh2
BeAsRh2
BeSnRh2
BeInRh2
BeSbRh2
BeGeRu2
BeGaRu2
BeAsRu2
BeSnRu2
BeInRu2
BeSbRu2
BeGePd2
BeGaPd2
BeAsPd2
BeSnPd2
BeInPd2
BeSbPd2
Be2NiRh
Be2NiRu
Be2NiPd
Be2CoNi
Be2FeNi
BeNi
Be2NiIr
Be2NiOs
Be2NiPt
Be2CoRh
Be2CoRu
Be2CoPd
BeCo
Be2FeCo
Be2CoNi
Be2CoIr
Be2CoOs
Be2CoPt
Be2CuRh
Be2CuRu
Be2CuPd
Be2CoCu
Be2FeCu
Be2CuNi
Be2CuIr
Be2CuOs
Be2CuPt
Be2PdRh
Be2PdRu
BePd
Be2CoPd
Be2FePd
Be2NiPd
Be2IrPd
Be2OsPd
Be2PdPt
BeRh
Be2RuRh
Be2PdRh
Be2CoRh
Be2FeRh
Be2NiRh
Be2IrRh
Be2OsRh
Be2PtRh
Be2AgRh
Be2AgRu
Be2AgPd
Be2CoAg
Be2FeAg
Be2NiAg
Be2AgIr
Be2AgOs
Be2AgPt
MnBe2Ir
MnBe2Os
MnBe2Pt
MnBe2Rh
MnBe2Ru
MnBe2Pd
Be2CrIr
Be2CrOs
Be2CrPt
Be2CrRh
Be2CrRu
Be2CrPd
Be2FeIr
Be2FeOs
Be2FePt
Be2FeRh
Be2FeRu
Be2FePd
Be2TcIr
Be2TcOs
Be2TcPt
Be2TcRh
Be2TcRu
Be2TcPd
Be2MoIr
Be2MoOs
Be2MoPt
Be2MoRh
Be2MoRu
Be2MoPd
Be2IrRu
Be2OsRu
Be2RuPt
Be2RuRh
BeRu
Be2PdRu
MnBe2Pt
MnBe2Ir
MnBe2Au
MnBe2Pd
MnBe2Rh
MnBe2Ag
Be2CrPt
Be2CrIr
Be2CrAu
Be2CrPd
Be2CrRh
Be2CrAg
Be2FePt
Be2FeIr
Be2FeAu
Be2FePd
Be2FeRh
Be2FeAg
Be2TcPt
Be2TcIr
Be2TcAu
Be2TcPd
Be2TcRh
Be2TcAg
Be2MoPt
Be2MoIr
Be2MoAu
Be2MoPd
Be2MoRh
Be2AgMo
Be2RuPt
Be2IrRu
Be2RuAu
Be2PdRu
Be2RuRh
Be2AgRu
Be2RuPt
Be2IrRu
Be2RuAu
Be2PdRu
Be2RuRh
Be2AgRu
Be2TcPt
Be2TcIr
Be2TcAu
Be2TcPd
Be2TcRh
Be2TcAg
Be2PtRh
Be2IrRh
Be2RhAu
Be2PdRh
BeRh
Be2AgRh
Be2FePt
Be2FeIr
Be2FeAu
Be2FePd
Be2FeRh
Be2FeAg
MnBe2Pt
MnBe2Ir
MnBe2Au
MnBe2Pd
MnBe2Rh
MnBe2Ag
Be2CoPt
Be2CoIr
Be2CoAu
Be2CoPd
Be2CoRh
Be2CoAg
Be2OsPt
Be2IrOs
Be2OsAu
Be2OsPd
Be2OsRh
Be2AgOs
Be2RePt
Be2ReIr
Be2ReAu
Be2RePd
Be2ReRh
Be2ReAg
Be2IrPt
BeIr
Be2IrAu
Be2IrPd
Be2IrRh
Be2AgIr
Be2NiIr
Be2NiOs
Be2NiPt
Be2NiRh
Be2NiRu
Be2NiPd
Be2CoIr
Be2CoOs
Be2CoPt
Be2CoRh
Be2CoRu
Be2CoPd
Be2CuIr
Be2CuOs
Be2CuPt
Be2CuRh
Be2CuRu
Be2CuPd
Be2IrPd
Be2OsPd
Be2PdPt
Be2PdRh
Be2PdRu
BePd
Be2IrRh
Be2OsRh
Be2PtRh
BeRh
Be2RuRh
Be2PdRh
Be2AgIr
Be2AgOs
Be2AgPt
Be2AgRh
Be2AgRu
Be2AgPd
BeSiNi2
BeCo2Si
BeCu2Si
BeSiPd2
BeSiRh2
BeSiAg2
BeAlNi2
BeAlCo2
BeAlCu2
BeAlPd2
BeAlRh2
BeAlAg2
TiBeNi2
TiBeCo2
TiBeCu2
TiBePd2
TiBeRh2
TiBeAg2
ScBeNi2
ScBeCo2
ScBeCu2
ScBePd2
ScBeRh2
ScBeAg2
BeVNi2
BeVCo2
BeVCu2
BeVPd2
BeVRh2
BeVAg2
BeAlIr2
BeAlOs2
BeAlPt2
BeAlRh2
BeAlRu2
BeAlPd2
MgBeIr2
MgBeOs2
MgBePt2
MgBeRh2
MgBeRu2
MgBePd2
BeSiIr2
BeSiOs2
BeSiPt2
BeSiRh2
BeSiRu2
BeSiPd2
BeBIr2
BeBOs2
BeBPt2
BeBRh2
BeBRu2
BeBPd2
BeIr
BeOs
BePt
BeRh
BeRu
BePd
ScBeIr2
ScBeOs2
ScBePt2
ScBeRh2
ScBeRu2
ScBePd2
CaBeIr2
CaBeOs2
CaBePt2
CaBeRh2
CaBeRu2
CaBePd2
TiBeIr2
TiBeOs2
TiBePt2
TiBeRh2
TiBeRu2
TiBePd2
Be2RhAu
Be2PtRh
Be2HgRh
Be2AgRh
Be2PdRh
Be2CdRh
Be2RuAu
Be2RuPt
Be2HgRu
Be2AgRu
Be2PdRu
Be2CdRu
Be2PdAu
Be2PdPt
Be2HgPd
Be2AgPd
BePd
Be2CdPd
Be2CoAu
Be2CoPt
Be2CoHg
Be2CoAg
Be2CoPd
Be2CdCo
Be2FeAu
Be2FePt
Be2FeHg
Be2FeAg
Be2FePd
Be2CdFe
Be2NiAu
Be2NiPt
Be2NiHg
Be2NiAg
Be2NiPd
Be2CdNi
Be2IrAu
Be2IrPt
Be2HgIr
Be2AgIr
Be2IrPd
Be2CdIr
Be2OsAu
Be2OsPt
Be2HgOs
Be2AgOs
Be2OsPd
Be2CdOs
Be2PtAu
BePt
Be2HgPt
Be2AgPt
Be2PdPt
Be2CdPt
Be2PdRh
Be2PdRu
BePd
Be2CoPd
Be2FePd
Be2NiPd
Be2IrPd
Be2OsPd
Be2PdPt
BeRh
Be2RuRh
Be2PdRh
Be2CoRh
Be2FeRh
Be2NiRh
Be2IrRh
Be2OsRh
Be2PtRh
Be2AgRh
Be2AgRu
Be2AgPd
Be2CoAg
Be2FeAg
Be2NiAg
Be2AgIr
Be2AgOs
Be2AgPt
Be2NiRh
Be2NiRu
Be2NiPd
Be2CoNi
Be2FeNi
BeNi
Be2NiIr
Be2NiOs
Be2NiPt
Be2CoRh
Be2CoRu
Be2CoPd
BeCo
Be2FeCo
Be2CoNi
Be2CoIr
Be2CoOs
Be2CoPt
Be2CuRh
Be2CuRu
Be2CuPd
Be2CoCu
Be2FeCu
Be2CuNi
Be2CuIr
Be2CuOs
Be2CuPt
Be2PtRh
Be2RuPt
Be2PdPt
Be2CoPt
Be2FePt
Be2NiPt
Be2IrPt
Be2OsPt
BePt
Be2IrRh
Be2IrRu
Be2IrPd
Be2CoIr
Be2FeIr
Be2NiIr
BeIr
Be2IrOs
Be2IrPt
Be2RhAu
Be2RuAu
Be2PdAu
Be2CoAu
Be2FeAu
Be2NiAu
Be2IrAu
Be2OsAu
Be2PtAu
ZrBeSi
ZrBeAl
ZrTiBe
ZrScBe
ZrBeV
YBeSi
YBeAl
YTiBe
YScBe
YBeV
BeNbSi
BeNbAl
TiBeNb
ScBeNb
BeNbV
TiBeSi
TiBeAl
Ti2Be
ScTiBe
TiBeV
ScBeSi
ScBeAl
ScTiBe
Sc2Be
ScBeV
BeVSi
BeAlV
TiBeV
ScBeV
BeV2
HfBeSi
HfBeAl
HfTiBe
HfScBe
HfBeV
LaBeSi
LaBeAl
LaTiBe
LaScBe
LaBeV
TaBeSi
TaBeAl
TaTiBe
ScTaBe
TaBeV
Be3Fe
MnBe3
Be3Co
Be3Ru
Be3Tc
Be3Rh
ZrBe5
YBe5
Be5Nb
TiBe5
ScBe5
Be5V
HfBe5
LaBe5
TaBe5
Be2W
TaBe2
Be2Re
Be2Mo
Be2Nb
Be2Tc
Be2V
TiBe2
Be2Cr
Be2Nb
ZrBe2
Be2Mo
Ta2Be
Hf2Be
BeW2
BeNb2
Zr2Be
BeMo2
ScBe5
CaBe5
TiBe5
Be5Al
MgBe5
Be5Si
YBe5
SrBe5
ZrBe5
BeRh
BeRu
BePd
BeCo
BeFe
BeNi
BeIr
BeOs
BePt
Be2Re
Be2W
Be2Os
Be2Tc
Be2Mo
Be2Ru
BePd
BeRh
BeAg
BeNi
BeCo
BeCu
BePt
BeIr
BeAu
Be2Nb3
Zr2Be2Nb
Be2NbMo2
Be2NbV2
Ti2Be2Nb
Be2NbCr2
Ta2Be2Nb
Hf2Be2Nb
Be2NbW2
Zr(BeNb)2
Zr3Be2
Zr(BeMo)2
Zr(BeV)2
Zr(TiBe)2
Zr(BeCr)2
Zr(TaBe)2
Hf2ZrBe2
Zr(BeW)2
Be2Nb2Mo
Zr2Be2Mo
Be2Mo3
Be2V2Mo
Ti2Be2Mo
Be2Cr2Mo
Ta2Be2Mo
Hf2Be2Mo
Be2MoW2
Be2Nb2V
Zr2Be2V
Be2VMo2
Be2V3
Ti2Be2V
Be2VCr2
Ta2Be2V
Hf2Be2V
Be2VW2
Ti(BeNb)2
Zr2TiBe2
Ti(BeMo)2
Ti(BeV)2
Ti3Be2
Ti(BeCr)2
Ta2TiBe2
Hf2TiBe2
Ti(BeW)2
Be2Nb2Cr
Zr2Be2Cr
Be2CrMo2
Be2V2Cr
Ti2Be2Cr
Be2Cr3
Ta2Be2Cr

NaBeAs
NaBeSn
NaBeIn
NaBeSb
BeAlGe
BeAlGa
BeAlAs
BeAlSn
BeAlIn
BeAlSb
SrBeGe
SrBeGa
SrBeAs
SrBeSn
SrBeIn
SrBeSb
RbBeGe
RbBeGa
RbBeAs
RbBeSn
RbBeIn
RbBeSb
YBeGe
YBeGa
YBeAs
YBeSn
YBeIn
YBeSb
MgBe4Cu
MgBe4Ni
MgBe4Zn
MgBe4Ag
MgBe4Pd
MgBe4Cd
NaBe4Cu
NaBe4Ni
NaBe4Zn
NaBe4Ag
NaBe4Pd
NaBe4Cd
Be4AlCu
Be4AlNi
Be4AlZn
Be4AlAg
Be4AlPd
Be4AlCd
Be5Cu
Be5Ni
Be5Zn
Be5Ag
Be5Pd
Be5Cd
LiBe4Cu
LiBe4Ni
LiBe4Zn
LiBe4Ag
LiBe4Pd
LiBe4Cd
Be4CuB
Be4NiB
Be4ZnB
Be4AgB
Be4BPd
Be4CdB
CaBe4Cu
CaBe4Ni
CaBe4Zn
CaBe4Ag
CaBe4Pd
CaBe4Cd
KBe4Cu
KBe4Ni
KBe4Zn
KBe4Ag
KBe4Pd
KBe4Cd
ScBe4Cu
ScBe4Ni
ScBe4Zn
ScBe4Ag
ScBe4Pd
ScBe4Cd
Be2B
Be
Be2Al
MgBe2
Be2Si
SrBeSi
SrBeAl
SrTiBe
SrScBe
SrBeV
RbBeSi
RbBeAl
RbTiBe
RbScBe
RbBeV
YBeSi
YBeAl
YTiBe
YScBe
YBeV
CaBeSi
CaBeAl
CaTiBe
CaScBe
CaBeV
KBeSi
KBeAl
KTiBe
KScBe
KBeV
ScBeSi
ScBeAl
ScTiBe
Sc2Be
ScBeV
BaBeSi
BaBeAl
BaTiBe
BaScBe
BaBeV
CsBeSi
CsBeAl
CsTiBe
CsScBe
CsBeV
LaBeSi
LaBeAl
LaTiBe
LaScBe
LaBeV
Be3Cu
Be3Ni
Be3Zn
Be3Ag
Be3Pd
Be3Cd
SrBeGe
SrBeGa
SrBeAs
SrBeSn
SrBeIn
SrBeSb
RbBeGe
RbBeGa
RbBeAs
RbBeSn
RbBeIn
RbBeSb
YBeGe
YBeGa
YBeAs
YBeSn
YBeIn
YBeSb
CaBeGe
CaBeGa
CaBeAs
CaBeSn
CaBeIn
CaBeSb
KBeGe
KBeGa
KBeAs
KBeSn
KBeIn
KBeSb
ScBeGe
ScBeGa
ScBeAs
ScBeSn
ScBeIn
ScBeSb
BaBeGe
BaBeGa
BaBeAs
BaBeSn
BaBeIn
BaBeSb
CsBeGe
CsBeGa
CsBeAs
CsBeSn
CsBeIn
CsBeSb
LaBeGe
LaBeGa
LaBeAs
LaBeSn
LaBeIn
LaBeSb
Be3Pd
Be3Rh
Be3Ag
Be3Ni
Be3Co
Be3Cu
Be3Pt
Be3Ir
Be3Au
Ti3Be
ScTi2Be
Ti2BeV
Ti2BeSi
Ti2BeAl
ZrTi2Be
YTi2Be
Ti2BeNb
Sc2TiBe
Sc3Be
Sc2BeV
Sc2BeSi
Sc2BeAl
ZrSc2Be
YSc2Be
Sc2BeNb
TiBeV2
ScBeV2
BeV3
BeV2Si
BeAlV2
ZrBeV2
YBeV2
BeNbV2
TiBeSi2
ScBeSi2
BeVSi2
BeSi3
BeAlSi2
ZrBeSi2
YBeSi2
BeNbSi2
TiBeAl2
ScBeAl2
BeAl2V
BeAl2Si
BeAl3
ZrBeAl2
YBeAl2
BeNbAl2
Zr2TiBe
Zr2ScBe
Zr2BeV
Zr2BeSi
Zr2BeAl
Zr3Be
YZr2Be
Zr2BeNb
Y2TiBe
Y2ScBe
Y2BeV
Y2BeSi
Y2BeAl
Y2ZrBe
Y3Be
Y2BeNb
TiBeNb2
ScBeNb2
BeNb2V
BeNb2Si
BeNb2Al
ZrBeNb2
YBeNb2
BeNb3
Be4SiNi
Be4CoSi
Be4CuSi
Be4SiPd
Be4SiRh
Be4SiAg
Be4AlNi
Be4AlCo
Be4AlCu
Be4AlPd
Be4AlRh
Be4AlAg
TiBe4Ni
TiBe4Co
TiBe4Cu
TiBe4Pd
TiBe4Rh
TiBe4Ag
ScBe4Ni
ScBe4Co
ScBe4Cu
ScBe4Pd
ScBe4Rh
ScBe4Ag
Be4VNi
Be4VCo
Be4VCu
Be4VPd
Be4VRh
Be4VAg
Ti3Be
Sc3Be
BeV3
BeSi3
BeAl3
Zr3Be
Y3Be
BeNb3
BeNi3
BeCoNi2
BeCuNi2
BeNi2Pd
BeNi2Rh
BeNi2Ag
BeCo2Ni
BeCo3
BeCo2Cu
BeCo2Pd
BeCo2Rh
BeCo2Ag
BeCu2Ni
BeCoCu2
BeCu3
BeCu2Pd
BeCu2Rh
BeCu2Ag
BeNiPd2
BeCoPd2
BeCuPd2
BePd3
BePd2Rh
BeAgPd2
BeNiRh2
BeCoRh2
BeCuRh2
BePdRh2
BeRh3
BeAgRh2
BeNiAg2
BeCoAg2
BeCuAg2
BeAg2Pd
BeAg2Rh
BeAg3
Be5Al6
Mg6Be5
Be5Si6
Be5B6
Be
Sc6Be5
Ca6Be5
Ti6Be5
BeNi3
BeCo3
BeCu3
BePd3
BeRh3
BeAg3
BeCo2Si
BeAlCo2
TiBeCo2
ScBeCo2
BeVCo2
BeFe2Si
BeAlFe2
TiBeFe2
ScBeFe2
BeVFe2
BeSiNi2
BeAlNi2
TiBeNi2
ScBeNi2
BeVNi2
BeSiRh2
BeAlRh2
TiBeRh2
ScBeRh2
BeVRh2
BeSiRu2
BeAlRu2
TiBeRu2
ScBeRu2
BeVRu2
BeSiPd2
BeAlPd2
TiBePd2
ScBePd2
BeVPd2
Be12Pd
Be12Rh
Be12Ag
Be12Ni
Be12Co
Be12Cu
Be12Pt
Be12Ir
Be12Au
TiBe12
ScBe12
Be12V
Be12Si
Be12Al
ZrBe12
YBe12
Be12Nb
Mn3Be
BeCr3
BeFe3
BeTc3
BeMo3
BeRu3
BeSiNi2
BeCo2Si
BeCu2Si
BeSiPd2
BeSiRh2
BeSiAg2
BeAlNi2
BeAlCo2
BeAlCu2
BeAlPd2
BeAlRh2
BeAlAg2
TiBeNi2
TiBeCo2
TiBeCu2
TiBePd2
TiBeRh2
TiBeAg2
ScBeNi2
ScBeCo2
ScBeCu2
ScBePd2
ScBeRh2
ScBeAg2
BeVNi2
BeVCo2
BeVCu2
BeVPd2
BeVRh2
BeVAg2
BeCo2Ge
BeGaCo2
BeCo2As
BeCo2Sn
BeInCo2
BeCo2Sb
BeFe2Ge
BeGaFe2
BeFe2As
BeFe2Sn
BeInFe2
BeFe2Sb
BeNi2Ge
BeGaNi2
BeNi2As
BeNi2Sn
BeInNi2
BeNi2Sb
BeGeRh2
BeGaRh2
BeAsRh2
BeSnRh2
BeInRh2
BeSbRh2
BeGeRu2
BeGaRu2
BeAsRu2
BeSnRu2
BeInRu2
BeSbRu2
BeGePd2
BeGaPd2
BeAsPd2
BeSnPd2
BeInPd2
BeSbPd2
Be4CoGe
Be4GaCo
Be4CoAs
Be4CoSn
Be4InCo
Be4CoSb
Be4FeGe
Be4GaFe
Be4FeAs
Be4FeSn
Be4InFe
Be4FeSb
Be4NiGe
Be4GaNi
Be4NiAs
Be4NiSn
Be4InNi
Be4NiSb
Be4GeRh
Be4GaRh
Be4AsRh
Be4SnRh
Be4InRh
Be4SbRh
Be4GeRu
Be4GaRu
Be4AsRu
Be4SnRu
Be4InRu
Be4SbRu
Be4GePd
Be4GaPd
Be4AsPd
Be4SnPd
Be4InPd
Be4SbPd
Be12Ag
Be12Pd
Be12Cd
Be12Cu
Be12Ni
Be12Zn
Be12Au
Be12Pt
Be12Hg
Be2CoSi
Be2AlCo
TiBe2Co
ScBe2Co
Be2VCo
Be2FeSi
Be2AlFe
TiBe2Fe
ScBe2Fe
Be2VFe
Be2SiNi
Be2AlNi
TiBe2Ni
ScBe2Ni
Be2VNi
Be2SiRh
Be2AlRh
TiBe2Rh
ScBe2Rh
Be2VRh
Be2SiRu
Be2AlRu
TiBe2Ru
ScBe2Ru
Be2VRu
Be2SiPd
Be2AlPd
TiBe2Pd
ScBe2Pd
Be2VPd
Be12Au
Be12Pt
Be12Hg
Be12Ag
Be12Pd
Be12Cd
Be12Pt
Be12Ir
Be12Au
Be12Pd
Be12Rh
Be12Ag
BeB2
Be
BeAl2
Mg2Be
BeSi2
BaBeSi
BaBeAl
BaTiBe
BaScBe
BaBeV
CsBeSi
CsBeAl
CsTiBe
CsScBe
CsBeV
LaBeSi
LaBeAl
LaTiBe
LaScBe
LaBeV
SrBeSi
SrBeAl
SrTiBe
SrScBe
SrBeV
RbBeSi
RbBeAl
RbTiBe
RbScBe
RbBeV
YBeSi
YBeAl
YTiBe
YScBe
YBeV
BeMo3
BeNb3
BeTc3
BeCr3
BeV3
Mn3Be
BeW3
Ta3Be
BeRe3
Zr3Be
YZr2Be
Zr2BeNb
Zr2TiBe
Zr2ScBe
Zr2BeV
HfZr2Be
LaZr2Be
Zr2TaBe
Y2ZrBe
Y3Be
Y2BeNb
Y2TiBe
Y2ScBe
Y2BeV
Y2HfBe
LaY2Be
Y2TaBe
ZrBeNb2
YBeNb2
BeNb3
TiBeNb2
ScBeNb2
BeNb2V
HfBeNb2
LaBeNb2
TaBeNb2
ZrTi2Be
YTi2Be
Ti2BeNb
Ti3Be
ScTi2Be
Ti2BeV
HfTi2Be
LaTi2Be
TaTi2Be
ZrSc2Be
YSc2Be
Sc2BeNb
Sc2TiBe
Sc3Be
Sc2BeV
HfSc2Be
LaSc2Be
Sc2TaBe
ZrBeV2
YBeV2
BeNbV2
TiBeV2
ScBeV2
BeV3
HfBeV2
LaBeV2
TaBeV2
Hf2ZrBe
YHf2Be
Hf2BeNb
Hf2TiBe
Hf2ScBe
Hf2BeV
Hf3Be
LaHf2Be
Hf2TaBe
La2ZrBe
La2YBe
La2BeNb
La2TiBe
La2ScBe
La2BeV
La2HfBe
La3Be
La2TaBe
ZrTa2Be
YTa2Be
Ta2BeNb
Ta2TiBe
ScTa2Be
Ta2BeV
HfTa2Be
LaTa2Be
Ta3Be
BeAl3
MgBeAl2
BeAl2Si
BeAl2B
BeAl
ScBeAl2
CaBeAl2
TiBeAl2
Mg2BeAl
Mg3Be
Mg2BeSi
Mg2BeB
MgBe
Mg2ScBe
CaMg2Be
Mg2TiBe
BeAlSi2
MgBeSi2
BeSi3
BeSi2B
BeSi
ScBeSi2
CaBeSi2
TiBeSi2
BeAlB2
MgBeB2
BeSiB2
BeB3
BeB
ScBeB2
CaBeB2
TiBeB2
Be3Al
MgBe3
Be3Si
Be3B
Be
ScBe3
CaBe3
TiBe3
Sc2BeAl
MgSc2Be
Sc2BeSi
Sc2BeB
ScBe
Sc3Be
CaSc2Be
Sc2TiBe
Ca2BeAl
Ca2MgBe
Ca2BeSi
Ca2BeB
CaBe
Ca2ScBe
Ca3Be
Ca2TiBe
Ti2BeAl
MgTi2Be
Ti2BeSi
Ti2BeB
TiBe
ScTi2Be
CaTi2Be
Ti3Be
Be4NiGe
Be4GaNi
Be4NiAs
Be4NiSn
Be4InNi
Be4NiSb
Be4CoGe
Be4GaCo
Be4CoAs
Be4CoSn
Be4InCo
Be4CoSb
Be4CuGe
Be4GaCu
Be4CuAs
Be4CuSn
Be4InCu
Be4CuSb
Be4GePd
Be4GaPd
Be4AsPd
Be4SnPd
Be4InPd
Be4SbPd
Be4GeRh
Be4GaRh
Be4AsRh
Be4SnRh
Be4InRh
Be4SbRh
Be4AgGe
Be4GaAg
Be4AgAs
Be4AgSn
Be4InAg
Be4AgSb
Hf3Be
LaHf2Be
Hf2TaBe
Hf2ZrBe
YHf2Be
Hf2BeNb
La2HfBe
La3Be
La2TaBe
La2ZrBe
La2YBe
La2BeNb
HfTa2Be
LaTa2Be
Ta3Be
ZrTa2Be
YTa2Be
Ta2BeNb
HfZr2Be
LaZr2Be
Zr2TaBe
Zr3Be
YZr2Be
Zr2BeNb
Y2HfBe
LaY2Be
Y2TaBe
Y2ZrBe
Y3Be
Y2BeNb
HfBeNb2
LaBeNb2
TaBeNb2
ZrBeNb2
YBeNb2
BeNb3
BeAu3
BePt3
BeHg3
BeAg3
BePd3
BeCd3
Be4CuSi
Be4AlCu
TiBe4Cu
ScBe4Cu
Be4VCu
Be4SiNi
Be4AlNi
TiBe4Ni
ScBe4Ni
Be4VNi
Be4ZnSi
Be4AlZn
TiBe4Zn
ScBe4Zn
Be4VZn
Be4SiAg
Be4AlAg
TiBe4Ag
ScBe4Ag
Be4VAg
Be4SiPd
Be4AlPd
TiBe4Pd
ScBe4Pd
Be4VPd
Be4CdSi
Be4AlCd
TiBe4Cd
ScBe4Cd
Be4VCd
MnBe2Co
MnBe2Fe
MnBe2Ni
MnBe2Rh
MnBe2Ru
MnBe2Pd
Be2CrCo
Be2CrFe
Be2CrNi
Be2CrRh
Be2CrRu
Be2CrPd
Be2FeCo
BeFe
Be2FeNi
Be2FeRh
Be2FeRu
Be2FePd
Be2CoTc
Be2FeTc
Be2TcNi
Be2TcRh
Be2TcRu
Be2TcPd
Be2CoMo
Be2FeMo
Be2NiMo
Be2MoRh
Be2MoRu
Be2MoPd
Be2CoRu
Be2FeRu
Be2NiRu
Be2RuRh
BeRu
Be2PdRu
BeCr3
BeV3
Mn3Be
BeMo3
BeNb3
BeTc3
BeRu3
BeTcRu2
BeRu2Rh
BeFeRu2
MnBeRu2
BeCoRu2
BeOsRu2
BeReRu2
BeIrRu2
BeTc2Ru
BeTc3
BeTc2Rh
BeFeTc2
MnBeTc2
BeCoTc2
BeTc2Os
BeReTc2
BeTc2Ir
BeRuRh2
BeTcRh2
BeRh3
BeFeRh2
MnBeRh2
BeCoRh2
BeOsRh2
BeReRh2
BeIrRh2
BeFe2Ru
BeFe2Tc
BeFe2Rh
BeFe3
MnBeFe2
BeFe2Co
BeFe2Os
BeFe2Re
BeFe2Ir
Mn2BeRu
Mn2BeTc
Mn2BeRh
Mn2BeFe
Mn3Be
Mn2BeCo
Mn2BeOs
Mn2BeRe
Mn2BeIr
BeCo2Ru
BeCo2Tc
BeCo2Rh
BeFeCo2
MnBeCo2
BeCo3
BeCo2Os
BeCo2Re
BeCo2Ir
BeOs2Ru
BeTcOs2
BeOs2Rh
BeFeOs2
MnBeOs2
BeCoOs2
BeOs3
BeReOs2
BeIrOs2
BeRe2Ru
BeRe2Tc
BeRe2Rh
BeFeRe2
MnBeRe2
BeCoRe2
BeRe2Os
BeRe3
BeRe2Ir
BeIr2Ru
BeTcIr2
BeIr2Rh
BeFeIr2
MnBeIr2
BeCoIr2
BeIr2Os
BeReIr2
BeIr3
BeAg3
BePd3
BeCd3
BeCu3
BeNi3
BeZn3
BeAu3
BePt3
BeHg3
Be2Si
Be2Al
TiBe2
ScBe2
Be2V
Be4CuGe
Be4GaCu
Be4CuAs
Be4CuSn
Be4InCu
Be4CuSb
Be4NiGe
Be4GaNi
Be4NiAs
Be4NiSn
Be4InNi
Be4NiSb
Be4ZnGe
Be4ZnGa
Be4ZnAs
Be4ZnSn
Be4ZnIn
Be4ZnSb
Be4AgGe
Be4GaAg
Be4AgAs
Be4AgSn
Be4InAg
Be4AgSb
Be4GePd
Be4GaPd
Be4AsPd
Be4SnPd
Be4InPd
Be4SbPd
Be4CdGe
Be4CdGa
Be4CdAs
Be4CdSn
Be4CdIn
Be4CdSb
Be4InCu
Be4InNi
Be4ZnIn
Be4InAg
Be4InPd
Be4CdIn
Be4CdCu
Be4CdNi
Be4ZnCd
Be4CdAg
Be4CdPd
Be2Cd
Be4CuSn
Be4NiSn
Be4ZnSn
Be4AgSn
Be4SnPd
Be4CdSn
Be4GaCu
Be4GaNi
Be4ZnGa
Be4GaAg
Be4GaPd
Be4CdGa
Be4ZnCu
Be4ZnNi
Be2Zn
Be4ZnAg
Be4ZnPd
Be4ZnCd
Be4CuGe
Be4NiGe
Be4ZnGe
Be4AgGe
Be4GePd
Be4CdGe
Be4TlCu
Be4TlNi
Be4TlZn
Be4TlAg
Be4TlPd
Be4TlCd
Be4CuHg
Be4NiHg
Be4ZnHg
Be4AgHg
Be4HgPd
Be4CdHg
Be4CuPb
Be4NiPb
Be4ZnPb
Be4AgPb
Be4PdPb
Be4CdPb
Li3Be
LiBe
Li2BeH
NaLi2Be
Li2MgBe
LiBe3
Be
Be3H
NaBe3
MgBe3
LiBeH2
BeH
BeH3
NaBeH2
MgBeH2
Na2LiBe
NaBe
Na2BeH
Na3Be
Na2MgBe
LiMg2Be
MgBe
Mg2BeH
NaMg2Be
Mg3Be
MgBe3
NaBe3
Be3Al
Be
LiBe3
Be3B
CaBe3
KBe3
ScBe3
Li3Be
Be
BeH3
Na3Be
Mg3Be
Be2Co
Be2Fe
Be2Ni
Be2Rh
Be2Ru
Be2Pd
Be3Si
Be3Al
TiBe3
ScBe3
Be3V
BeGa3
BeZnGa2
BeGa2Ge
BeInGa2
BeCdGa2
BeGa2Sn
BeZn2Ga
BeZn3
BeZn2Ge
BeZn2In
BeZn2Cd
BeZn2Sn
BeGaGe2
BeZnGe2
BeGe3
BeInGe2
BeCdGe2
BeSnGe2
BeIn2Ga
BeZnIn2
BeIn2Ge
BeIn3
BeCdIn2
BeIn2Sn
BeCd2Ga
BeZnCd2
BeCd2Ge
BeCd2In
BeCd3
BeCd2Sn
BeGaSn2
BeZnSn2
BeSn2Ge
BeInSn2
BeCdSn2
BeSn3
Be2Zn
Be2Cu
Be2Ga
Be2Cd
Be2Ag
Be2In
LiBe
Be
BeH
NaBe
MgBe
BeFe3
MnBeFe2
BeFe2Co
BeFe2Ru
BeFe2Tc
BeFe2Rh
Mn2BeFe
Mn3Be
Mn2BeCo
Mn2BeRu
Mn2BeTc
Mn2BeRh
BeFeCo2
MnBeCo2
BeCo3
BeCo2Ru
BeCo2Tc
BeCo2Rh
BeFeRu2
MnBeRu2
BeCoRu2
BeRu3
BeTcRu2
BeRu2Rh
BeFeTc2
MnBeTc2
BeCoTc2
BeTc2Ru
BeTc3
BeTc2Rh
BeFeRh2
MnBeRh2
BeCoRh2
BeRuRh2
BeTcRh2
BeRh3
Be3Ge
Be3Ga
Be3As
Be3Sn
Be3In
Be3Sb
BeIn3
BeCdIn2
BeIn2Sn
BeIn2Ga
BeZnIn2
BeIn2Ge
BeTlIn2
BeIn2Hg
BeIn2Pb
BeCd2In
BeCd3
BeCd2Sn
BeCd2Ga
BeZnCd2
BeCd2Ge
BeTlCd2
BeCd2Hg
BeCd2Pb
BeInSn2
BeCdSn2
BeSn3
BeGaSn2
BeZnSn2
BeSn2Ge
BeTlSn2
BeSn2Hg
BeSn2Pb
BeInGa2
BeCdGa2
BeGa2Sn
BeGa3
BeZnGa2
BeGa2Ge
BeTlGa2
BeGa2Hg
BeGa2Pb
BeZn2In
BeZn2Cd
BeZn2Sn
BeZn2Ga
BeZn3
BeZn2Ge
BeTlZn2
BeZn2Hg
BeZn2Pb
BeInGe2
BeCdGe2
BeSnGe2
BeGaGe2
BeZnGe2
BeGe3
BeTlGe2
BeHgGe2
BeGe2Pb
BeTl2In
BeTl2Cd
BeTl2Sn
BeTl2Ga
BeTl2Zn
BeTl2Ge
BeTl3
BeTl2Hg
BeTl2Pb
BeInHg2
BeCdHg2
BeSnHg2
BeGaHg2
BeZnHg2
BeHg2Ge
BeTlHg2
BeHg3
BeHg2Pb
BeInPb2
BeCdPb2
BeSnPb2
BeGaPb2
BeZnPb2
BeGePb2
BeTlPb2
BeHgPb2
BePb3
MgBeB
MgBe2
MgBeAl
Mg2Be
MgBeSi
NaBeB
NaBe2
NaBeAl
NaMgBe
NaBeSi
BeAlB
Be2Al
BeAl2
MgBeAl
BeAlSi
Be2B
Be
Be2Al
MgBe2
Be2Si
LiBeB
LiBe2
LiBeAl
LiMgBe
LiBeSi
BeB2
Be2B
BeAlB
MgBeB
BeSiB
CaBeB
CaBe2
CaBeAl
CaMgBe
CaBeSi
KBeB
KBe2
KBeAl
KMgBe
KBeSi
ScBeB
ScBe2
ScBeAl
MgScBe
ScBeSi
Na3Be
Na2MgBe
Na2LiBe
NaBe
KNa2Be
Na2CaBe
NaMg2Be
Mg3Be
LiMg2Be
MgBe
KMg2Be
CaMg2Be
NaLi2Be
Li2MgBe
Li3Be
LiBe
KLi2Be
Li2CaBe
NaBe3
MgBe3
LiBe3
Be
KBe3
CaBe3
K2NaBe
K2MgBe
K2LiBe
KBe
K3Be
K2CaBe
NaCa2Be
Ca2MgBe
LiCa2Be
CaBe
KCa2Be
Ca3Be
BeGe3
BeGaGe2
BeGe2As
BeSnGe2
BeInGe2
BeGe2Sb
BeGa2Ge
BeGa3
BeGa2As
BeGa2Sn
BeInGa2
BeGa2Sb
BeGeAs2
BeGaAs2
BeAs3
BeSnAs2
BeInAs2
BeSbAs2
BeSn2Ge
BeGaSn2
BeSn2As
BeSn3
BeInSn2
BeSn2Sb
BeIn2Ge
BeIn2Ga
BeIn2As
BeIn2Sn
BeIn3
BeIn2Sb
BeGeSb2
BeGaSb2
BeSb2As
BeSnSb2
BeInSb2
BeSb3
BePb3
BeTlPb2
BeBiPb2
BeSnPb2
BeInPb2
BeSbPb2
BeTl2Pb
BeTl3
BeTl2Bi
BeTl2Sn
BeTl2In
BeTl2Sb
BeBi2Pb
BeTlBi2
BeBi3
BeSnBi2
BeInBi2
BeBi2Sb
BeSn2Pb
BeTlSn2
BeSn2Bi
BeSn3
BeInSn2
BeSn2Sb
BeIn2Pb
BeTlIn2
BeIn2Bi
BeIn2Sn
BeIn3
BeIn2Sb
BeSb2Pb
BeTlSb2
BeBiSb2
BeSnSb2
BeInSb2
BeSb3
BeGe3
BeGa3
BeAs3
BeSn3
BeIn3
BeSb3
BeSbAs2
BeGe2Sb
BeSb3
BeSn2Sb
BeSbTe2
BeSnAs2
BeSnGe2
BeSnSb2
BeSn3
BeSnTe2
BeTeAs2
BeGe2Te
BeSb2Te
BeSn2Te
BeTe3
BeAs3
BeGe2As
BeSb2As
BeSn2As
BeTe2As
BeGeAs2
BeGe3
BeGeSb2
BeSn2Ge
BeGeTe2
BeBiAs2
BeGe2Bi
BeBiSb2
BeSn2Bi
BeBiTe2
BeAs2Pb
BeGe2Pb
BeSb2Pb
BeSn2Pb
BeTe2Pb
BePoAs2
BePoGe2
BePoSb2
BeSn2Po
BePoTe2
K3Be
K2CaBe
K2NaBe
K2MgBe
K2RbBe
K2SrBe
KCa2Be
Ca3Be
NaCa2Be
Ca2MgBe
RbCa2Be
SrCa2Be
KNa2Be
Na2CaBe
Na3Be
Na2MgBe
RbNa2Be
Na2SrBe
KMg2Be
CaMg2Be
NaMg2Be
Mg3Be
RbMg2Be
SrMg2Be
KRb2Be
Rb2CaBe
Rb2NaBe
Rb2MgBe
Rb3Be
Rb2SrBe
KSr2Be
Sr2CaBe
NaSr2Be
Sr2MgBe
RbSr2Be
Sr3Be
BeInBi
BeInPb
BeInPo
BeInSb
BeInSn
BeInTe
BeCdBi
BeCdPb
BeCdPo
BeCdSb
BeCdSn
BeCdTe
BeSnBi
BeSnPb
BeSnPo
BeSnSb
BeSn2
BeSnTe
BeGaBi
BeGaPb
BeGaPo
BeGaSb
BeGaSn
BeGaTe
BeZnBi
BeZnPb
BeZnPo
BeZnSb
BeZnSn
BeZnTe
BeGeBi
BeGePb
BePoGe
BeGeSb
BeSnGe
BeGeTe
BeTlBi
BeTlPb
BeTlPo
BeTlSb
BeTlSn
BeTlTe
BeHgBi
BeHgPb
BeHgPo
BeHgSb
BeSnHg
BeHgTe
BeBiPb
BePb2
BePoPb
BeSbPb
BeSnPb
BeTePb
MgBe2B
MgBe3
MgBe2Al
MgBe
MgBe2Si
NaBe2B
NaBe3
NaBe2Al
NaMgBe2
NaBe2Si
Be2AlB
Be3Al
BeAl
MgBe2Al
Be2AlSi
Be3B
Be
Be3Al
MgBe3
Be3Si
LiBe2B
LiBe3
LiBe2Al
LiMgBe2
LiBe2Si
BeB
Be3B
Be2AlB
MgBe2B
Be2SiB
CaBe2B
CaBe3
CaBe2Al
CaMgBe2
CaBe2Si
KBe2B
KBe3
KBe2Al
KMgBe2
KBe2Si
ScBe2B
ScBe3
ScBe2Al
MgScBe2
ScBe2Si
BeGeB
Be2Ge
BeAlGe
MgBeGe
BeSiGe
BeGaB
Be2Ga
BeAlGa
MgBeGa
BeGaSi
BeBAs
Be2As
BeAlAs
MgBeAs
BeSiAs
BeSnB
Be2Sn
BeAlSn
MgBeSn
BeSiSn
BeInB
Be2In
BeAlIn
MgBeIn
BeInSi
BeBSb
Be2Sb
BeAlSb
MgBeSb
BeSiSb
CaHfBe
CaLaBe
CaTaBe
CaZrBe
CaYBe
CaBeNb
KHfBe
KLaBe
KTaBe
KZrBe
KYBe
KBeNb
HfScBe
LaScBe
ScTaBe
ZrScBe
YScBe
ScBeNb
HfMgBe
LaMgBe
MgTaBe
MgZrBe
YMgBe
MgBeNb
NaHfBe
NaLaBe
NaTaBe
NaZrBe
NaYBe
NaBeNb
HfBeAl
LaBeAl
TaBeAl
ZrBeAl
YBeAl
BeNbAl
SrHfBe
SrLaBe
SrTaBe
SrZrBe
SrYBe
SrBeNb
RbHfBe
RbLaBe
RbTaBe
RbZrBe
RbYBe
RbBeNb
YHfBe
LaYBe
YTaBe
YZrBe
Y2Be
YBeNb
KBePt
KBeIr
KBeAu
KBePd
KBeRh
KBeAg
CaBePt
CaBeIr
CaBeAu
CaBePd
CaBeRh
CaBeAg
NaBePt
NaBeIr
NaBeAu
NaBePd
NaBeRh
NaBeAg
MgBePt
MgBeIr
MgBeAu
MgBePd
MgBeRh
MgBeAg
RbBePt
RbBeIr
RbBeAu
RbBePd
RbBeRh
RbBeAg
SrBePt
SrBeIr
SrBeAu
SrBePd
SrBeRh
SrBeAg
ZrBeCd
ZrBeAg
ZrBeIn
ZrBeZn
ZrBeCu
ZrBeGa
ZrBeHg
ZrBeAu
ZrBeTl
YBeCd
YBeAg
YBeIn
YBeZn
YBeCu
YBeGa
YBeHg
YBeAu
YBeTl
BeNbCd
BeNbAg
BeNbIn
BeNbZn
BeNbCu
BeNbGa
BeNbHg
BeNbAu
BeNbTl
TiBeCd
TiBeAg
TiBeIn
TiBeZn
TiBeCu
TiBeGa
TiBeHg
TiBeAu
TiBeTl
ScBeCd
ScBeAg
ScBeIn
ScBeZn
ScBeCu
ScBeGa
ScBeHg
ScBeAu
ScBeTl
BeVCd
BeVAg
BeVIn
BeVZn
BeVCu
BeVGa
BeVHg
BeVAu
BeTlV
HfBeCd
HfBeAg
HfBeIn
HfBeZn
HfBeCu
HfBeGa
HfBeHg
HfBeAu
HfBeTl
LaBeCd
LaBeAg
LaBeIn
LaBeZn
LaBeCu
LaBeGa
LaBeHg
LaBeAu
LaBeTl
TaBeCd
TaBeAg
TaBeIn
TaBeZn
TaBeCu
TaBeGa
TaBeHg
TaBeAu
TaBeTl
YScBe
CaYBe
YTiBe
YBeAl
YMgBe
YBeSi
Y2Be
SrYBe
YZrBe
SrScBe
SrCaBe
SrTiBe
SrBeAl
SrMgBe
SrBeSi
SrYBe
Sr2Be
SrZrBe
ZrScBe
CaZrBe
ZrTiBe
ZrBeAl
MgZrBe
ZrBeSi
YZrBe
SrZrBe
Zr2Be
Sc2Be
CaScBe
ScTiBe
ScBeAl
MgScBe
ScBeSi
YScBe
SrScBe
ZrScBe
CaScBe
Ca2Be
CaTiBe
CaBeAl
CaMgBe
CaBeSi
CaYBe
SrCaBe
CaZrBe
ScTiBe
CaTiBe
Ti2Be
TiBeAl
MgTiBe
TiBeSi
YTiBe
SrTiBe
ZrTiBe
LaScBe
CaLaBe
LaTiBe
LaBeAl
LaMgBe
LaBeSi
LaYBe
SrLaBe
LaZrBe
BaScBe
BaCaBe
BaTiBe
BaBeAl
BaMgBe
BaBeSi
BaYBe
BaSrBe
BaZrBe
HfScBe
CaHfBe
HfTiBe
HfBeAl
HfMgBe
HfBeSi
YHfBe
SrHfBe
HfZrBe
Be2HgTe
Be2HgSb
Be2HgPo
Be2HgBi
Be2TeAu
Be2SbAu
Be2PoAu
Be2BiAu
Be2TlTe
Be2TlSb
Be2TlPo
Be2TlBi
Be2CdTe
Be2CdSb
Be2CdPo
Be2CdBi
Be2AgTe
Be2AgSb
Be2AgPo
Be2AgBi
Be2InTe
Be2InSb
Be2InPo
Be2InBi
HfBe2Bi
HfBe2Pb
HfBe2Po
HfBe2Sb
HfBe2Sn
HfBe2Te
LaBe2Bi
LaBe2Pb
LaBe2Po
LaBe2Sb
LaBe2Sn
LaBe2Te
TaBe2Bi
TaBe2Pb
TaBe2Po
TaBe2Sb
TaBe2Sn
TaBe2Te
ZrBe2Bi
ZrBe2Pb
ZrBe2Po
ZrBe2Sb
ZrBe2Sn
ZrBe2Te
YBe2Bi
YBe2Pb
YBe2Po
YBe2Sb
YBe2Sn
YBe2Te
Be2NbBi
Be2NbPb
Be2NbPo
Be2NbSb
Be2NbSn
Be2NbTe
BaBeGa
BaBeZn
BaBeGe
BaBeIn
BaBeCd
BaBeSn
CsBeGa
CsBeZn
CsBeGe
CsBeIn
CsBeCd
CsBeSn
LaBeGa
LaBeZn
LaBeGe
LaBeIn
LaBeCd
LaBeSn
SrBeGa
SrBeZn
SrBeGe
SrBeIn
SrBeCd
SrBeSn
RbBeGa
RbBeZn
RbBeGe
RbBeIn
RbBeCd
RbBeSn
YBeGa
YBeZn
YBeGe
YBeIn
YBeCd
YBeSn
BeReB
Be2Re
BeAlRe
MgBeRe
BeReSi
BeBW
Be2W
BeAlW
MgBeW
BeSiW
BeBOs
Be2Os
BeAlOs
MgBeOs
BeSiOs
BeTcB
Be2Tc
BeAlTc
MgBeTc
BeSiTc
BeBMo
Be2Mo
BeAlMo
MgBeMo
BeSiMo
BeBRu
Be2Ru
BeAlRu
MgBeRu
BeSiRu
SrScBe
SrCaBe
SrTiBe
SrBeAl
SrMgBe
SrBeSi
SrYBe
Sr2Be
SrZrBe
RbScBe
RbCaBe
RbTiBe
RbBeAl
RbMgBe
RbBeSi
RbYBe
RbSrBe
RbZrBe
YScBe
CaYBe
YTiBe
YBeAl
YMgBe
YBeSi
Y2Be
SrYBe
YZrBe
CaScBe
Ca2Be
CaTiBe
CaBeAl
CaMgBe
CaBeSi
CaYBe
SrCaBe
CaZrBe
KScBe
KCaBe
KTiBe
KBeAl
KMgBe
KBeSi
KYBe
KSrBe
KZrBe
Sc2Be
CaScBe
ScTiBe
ScBeAl
MgScBe
ScBeSi
YScBe
SrScBe
ZrScBe
BaScBe
BaCaBe
BaTiBe
BaBeAl
BaMgBe
BaBeSi
BaYBe
BaSrBe
BaZrBe
CsScBe
CsCaBe
CsTiBe
CsBeAl
CsMgBe
CsBeSi
CsYBe
CsSrBe
CsZrBe
LaScBe
CaLaBe
LaTiBe
LaBeAl
LaMgBe
LaBeSi
LaYBe
SrLaBe
LaZrBe
BaBe2Te
BaBe2Sb
BaBe2Po
BaBe2Bi
CsBe2Te
CsBe2Sb
CsBe2Po
CsBe2Bi
LaBe2Te
LaBe2Sb
LaBe2Po
LaBe2Bi
SrBe2Te
SrBe2Sb
SrBe2Po
SrBe2Bi
RbBe2Te
RbBe2Sb
RbBe2Po
RbBe2Bi
YBe2Te
YBe2Sb
YBe2Po
YBe2Bi
LiTaBe
LiHfBe
LiBeW
LiBeNb
LiZrBe
LiBeMo
TaBe2
HfBe2
Be2W
Be2Nb
ZrBe2
Be2Mo
TaBeH
HfBeH
BeHW
BeNbH
ZrBeH
BeMoH
NaTaBe
NaHfBe
NaBeW
NaBeNb
NaZrBe
NaBeMo
MgTaBe
HfMgBe
MgBeW
MgBeNb
MgZrBe
MgBeMo
Be2PtAu
BePt
Be2HgPt
Be2AgPt
Be2PdPt
Be2CdPt
Be2IrAu
Be2IrPt
Be2HgIr
Be2AgIr
Be2IrPd
Be2CdIr
BeAu
Be2PtAu
Be2HgAu
Be2AgAu
Be2PdAu
Be2CdAu
Be2PdAu
Be2PdPt
Be2HgPd
Be2AgPd
BePd
Be2CdPd
Be2RhAu
Be2PtRh
Be2HgRh
Be2AgRh
Be2PdRh
Be2CdRh
Be2AgAu
Be2AgPt
Be2AgHg
BeAg
Be2AgPd
Be2CdAg
Be2PdAu
Be2PdPt
Be2HgPd
Be2AgPd
BePd
Be2CdPd
Be2RhAu
Be2PtRh
Be2HgRh
Be2AgRh
Be2PdRh
Be2CdRh
Be2AgAu
Be2AgPt
Be2AgHg
BeAg
Be2AgPd
Be2CdAg
Be2NiAu
Be2NiPt
Be2NiHg
Be2NiAg
Be2NiPd
Be2CdNi
Be2CoAu
Be2CoPt
Be2CoHg
Be2CoAg
Be2CoPd
Be2CdCo
Be2CuAu
Be2CuPt
Be2CuHg
Be2CuAg
Be2CuPd
Be2CdCu
Be2PtAu
BePt
Be2HgPt
Be2AgPt
Be2PdPt
Be2CdPt
Be2IrAu
Be2IrPt
Be2HgIr
Be2AgIr
Be2IrPd
Be2CdIr
BeAu
Be2PtAu
Be2HgAu
Be2AgAu
Be2PdAu
Be2CdAu
BeCdPt2
BeCdIr2
BeCdAu2
BeCdPd2
BeCdRh2
BeCdAg2
BeAgPt2
BeAgIr2
BeAgAu2
BeAgPd2
BeAgRh2
BeAg3
BeInPt2
BeInIr2
BeInAu2
BeInPd2
BeInRh2
BeInAg2
BeZnPt2
BeZnIr2
BeZnAu2
BeZnPd2
BeZnRh2
BeZnAg2
BeCuPt2
BeCuIr2
BeCuAu2
BeCuPd2
BeCuRh2
BeCuAg2
BeGaPt2
BeGaIr2
BeGaAu2
BeGaPd2
BeGaRh2
BeGaAg2
BeHgPt2
BeHgIr2
BeHgAu2
BeHgPd2
BeHgRh2
BeAg2Hg
BePt2Au
BeIr2Au
BeAu3
BePd2Au
BeRh2Au
BeAg2Au
BeTlPt2
BeTlIr2
BeTlAu2
BeTlPd2
BeTlRh2
BeTlAg2
BeInPt2
BeInIr2
BeInAu2
BeInPd2
BeInRh2
BeInAg2
BeCdPt2
BeCdIr2
BeCdAu2
BeCdPd2
BeCdRh2
BeCdAg2
BeSnPt2
BeSnIr2
BeSnAu2
BeSnPd2
BeSnRh2
BeAg2Sn
BeGaPt2
BeGaIr2
BeGaAu2
BeGaPd2
BeGaRh2
BeGaAg2
BeZnPt2
BeZnIr2
BeZnAu2
BeZnPd2
BeZnRh2
BeZnAg2
BeGePt2
BeGeIr2
BeGeAu2
BeGePd2
BeGeRh2
BeAg2Ge
BeTlPt2
BeTlIr2
BeTlAu2
BeTlPd2
BeTlRh2
BeTlAg2
BeHgPt2
BeHgIr2
BeHgAu2
BeHgPd2
BeHgRh2
BeAg2Hg
BePt2Pb
BeIr2Pb
BePbAu2
BePd2Pb
BeRh2Pb
BeAg2Pb
BeGaPd2
BeGaRh2
BeGaAg2
BeGaNi2
BeGaCo2
BeGaCu2
BeGaPt2
BeGaIr2
BeGaAu2
BeZnPd2
BeZnRh2
BeZnAg2
BeZnNi2
BeZnCo2
BeZnCu2
BeZnPt2
BeZnIr2
BeZnAu2
BeGePd2
BeGeRh2
BeAg2Ge
BeNi2Ge
BeCo2Ge
BeCu2Ge
BeGePt2
BeGeIr2
BeGeAu2
BeInPd2
BeInRh2
BeInAg2
BeInNi2
BeInCo2
BeInCu2
BeInPt2
BeInIr2
BeInAu2
BeCdPd2
BeCdRh2
BeCdAg2
BeCdNi2
BeCdCo2
BeCdCu2
BeCdPt2
BeCdIr2
BeCdAu2
BeSnPd2
BeSnRh2
BeAg2Sn
BeNi2Sn
BeCo2Sn
BeCu2Sn
BeSnPt2
BeSnIr2
BeSnAu2
Be2AgPt
Be2AgIr
Be2AgAu
Be2AgPd
Be2AgRh
BeAg
Be2PdPt
Be2IrPd
Be2PdAu
BePd
Be2PdRh
Be2AgPd
Be2CdPt
Be2CdIr
Be2CdAu
Be2CdPd
Be2CdRh
Be2CdAg
Be2CuPt
Be2CuIr
Be2CuAu
Be2CuPd
Be2CuRh
Be2CuAg
Be2NiPt
Be2NiIr
Be2NiAu
Be2NiPd
Be2NiRh
Be2NiAg
Be2ZnPt
Be2ZnIr
Be2ZnAu
Be2ZnPd
Be2ZnRh
Be2ZnAg
Be2PtAu
Be2IrAu
BeAu
Be2PdAu
Be2RhAu
Be2AgAu
BePt
Be2IrPt
Be2PtAu
Be2PdPt
Be2PtRh
Be2AgPt
Be2HgPt
Be2HgIr
Be2HgAu
Be2HgPd
Be2HgRh
Be2AgHg
BeGaPt2
BeGaIr2
BeGaAu2
BeGaPd2
BeGaRh2
BeGaAg2
BeZnPt2
BeZnIr2
BeZnAu2
BeZnPd2
BeZnRh2
BeZnAg2
BeGePt2
BeGeIr2
BeGeAu2
BeGePd2
BeGeRh2
BeAg2Ge
BeInPt2
BeInIr2
BeInAu2
BeInPd2
BeInRh2
BeInAg2
BeCdPt2
BeCdIr2
BeCdAu2
BeCdPd2
BeCdRh2
BeCdAg2
BeSnPt2
BeSnIr2
BeSnAu2
BeSnPd2
BeSnRh2
BeAg2Sn
TiBeAu2
TiBePt2
TiBeHg2
TiBeAg2
TiBePd2
TiBeCd2
ScBeAu2
ScBePt2
ScBeHg2
ScBeAg2
ScBePd2
ScBeCd2
BeVAu2
BeVPt2
BeVHg2
BeVAg2
BeVPd2
BeVCd2
BeSiAu2
BeSiPt2
BeSiHg2
BeSiAg2
BeSiPd2
BeCd2Si
BeAlAu2
BeAlPt2
BeAlHg2
BeAlAg2
BeAlPd2
BeAlCd2
ZrBeAu2
ZrBePt2
ZrBeHg2
ZrBeAg2
ZrBePd2
ZrBeCd2
YBeAu2
YBePt2
YBeHg2
YBeAg2
YBePd2
YBeCd2
BeNbAu2
BeNbPt2
BeNbHg2
BeNbAg2
BeNbPd2
BeNbCd2
BeZnPt2
BeZnIr2
BeZnAu2
BeZnPd2
BeZnRh2
BeZnAg2
BeCuPt2
BeCuIr2
BeCuAu2
BeCuPd2
BeCuRh2
BeCuAg2
BeGaPt2
BeGaIr2
BeGaAu2
BeGaPd2
BeGaRh2
BeGaAg2
BeCdPt2
BeCdIr2
BeCdAu2
BeCdPd2
BeCdRh2
BeCdAg2
BeAgPt2
BeAgIr2
BeAgAu2
BeAgPd2
BeAgRh2
BeAg3
BeInPt2
BeInIr2
BeInAu2
BeInPd2
BeInRh2
BeInAg2
MgBePt2
MgBeIr2
MgBeAu2
MgBePd2
MgBeRh2
MgBeAg2
NaBePt2
NaBeIr2
NaBeAu2
NaBePd2
NaBeRh2
NaBeAg2
BeAlPt2
BeAlIr2
BeAlAu2
BeAlPd2
BeAlRh2
BeAlAg2
BePt
BeIr
BeAu
BePd
BeRh
BeAg
LiBePt2
LiBeIr2
LiBeAu2
LiBePd2
LiBeRh2
LiBeAg2
BeBPt2
BeBIr2
BeBAu2
BeBPd2
BeBRh2
BeAg2B
CaBePt2
CaBeIr2
CaBeAu2
CaBePd2
CaBeRh2
CaBeAg2
KBePt2
KBeIr2
KBeAu2
KBePd2
KBeRh2
KBeAg2
ScBePt2
ScBeIr2
ScBeAu2
ScBePd2
ScBeRh2
ScBeAg2
BePt2Au
BePt3
BeHgPt2
BeAgPt2
BePdPt2
BeCdPt2
BeIr2Au
BeIr2Pt
BeHgIr2
BeAgIr2
BeIr2Pd
BeCdIr2
BeAu3
BePtAu2
BeHgAu2
BeAgAu2
BePdAu2
BeCdAu2
BePd2Au
BePd2Pt
BeHgPd2
BeAgPd2
BePd3
BeCdPd2
BeRh2Au
BePtRh2
BeHgRh2
BeAgRh2
BePdRh2
BeCdRh2
BeAg2Au
BeAg2Pt
BeAg2Hg
BeAg3
BeAg2Pd
BeCdAg2
BeAlPd2
BeAlRh2
BeAlAg2
BeAlNi2
BeAlCo2
BeAlCu2
BeAlPt2
BeAlIr2
BeAlAu2
MgBePd2
MgBeRh2
MgBeAg2
MgBeNi2
MgBeCo2
MgBeCu2
MgBePt2
MgBeIr2
MgBeAu2
BeSiPd2
BeSiRh2
BeSiAg2
BeSiNi2
BeCo2Si
BeCu2Si
BeSiPt2
BeSiIr2
BeSiAu2
BeBPd2
BeBRh2
BeAg2B
BeNi2B
BeCo2B
BeCu2B
BeBPt2
BeBIr2
BeBAu2
BePd
BeRh
BeAg
BeNi
BeCo
BeCu
BePt
BeIr
BeAu
ScBePd2
ScBeRh2
ScBeAg2
ScBeNi2

MnBe2Rh
MnBe2Fe
MnBe
MnBe2Co
MnBe2Os
MnBe2Re
MnBe2Ir
Be2CrRu
Be2CrTc
Be2CrRh
Be2CrFe
MnBe2Cr
Be2CrCo
Be2CrOs
Be2CrRe
Be2CrIr
Be2FeRu
Be2FeTc
Be2FeRh
BeFe
MnBe2Fe
Be2FeCo
Be2FeOs
Be2FeRe
Be2FeIr
Be2TcRu
BeTc
Be2TcRh
Be2FeTc
MnBe2Tc
Be2CoTc
Be2TcOs
Be2ReTc
Be2TcIr
Be2MoRu
Be2TcMo
Be2MoRh
Be2FeMo
MnBe2Mo
Be2CoMo
Be2MoOs
Be2ReMo
Be2MoIr
BeRu
Be2TcRu
Be2RuRh
Be2FeRu
MnBe2Ru
Be2CoRu
Be2OsRu
Be2ReRu
Be2IrRu
BeFeCo2
BeFe3
BeFeNi2
BeFeRh2
BeFeRu2
BeFePd2
MnBeCo2
MnBeFe2
MnBeNi2
MnBeRh2
MnBeRu2
MnBePd2
BeCo3
BeFe2Co
BeCoNi2
BeCoRh2
BeCoRu2
BeCoPd2
BeCo2Ru
BeFe2Ru
BeNi2Ru
BeRuRh2
BeRu3
BePd2Ru
BeCo2Tc
BeFe2Tc
BeTcNi2
BeTcRh2
BeTcRu2
BeTcPd2
BeCo2Rh
BeFe2Rh
BeNi2Rh
BeRh3
BeRu2Rh
BePd2Rh
TaBeRh2
TaBeRu2
TaBePd2
TaBeCo2
TaBeFe2
TaBeNi2
TaBeIr2
TaBeOs2
TaBePt2
HfBeRh2
HfBeRu2
HfBePd2
HfBeCo2
HfBeFe2
HfBeNi2
HfBeIr2
HfBeOs2
HfBePt2
BeRh2W
BeRu2W
BePd2W
BeCo2W
BeFe2W
BeNi2W
BeIr2W
BeOs2W
BePt2W
BeNbRh2
BeNbRu2
BeNbPd2
BeNbCo2
BeNbFe2
BeNbNi2
BeNbIr2
BeNbOs2
BeNbPt2
ZrBeRh2
ZrBeRu2
ZrBePd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeIr2
ZrBeOs2
ZrBePt2
BeMoRh2
BeMoRu2
BeMoPd2
BeCo2Mo
BeFe2Mo
BeNi2Mo
BeMoIr2
BeMoOs2
BeMoPt2
BeBIr2
BeBOs2
BeBPt2
BeBRh2
BeBRu2
BeBPd2
BeIr
BeOs
BePt
BeRh
BeRu
BePd
BeAlIr2
BeAlOs2
BeAlPt2
BeAlRh2
BeAlRu2
BeAlPd2
MgBeIr2
MgBeOs2
MgBePt2
MgBeRh2
MgBeRu2
MgBePd2
BeSiIr2
BeSiOs2
BeSiPt2
BeSiRh2
BeSiRu2
BeSiPd2
Be2NiRu
Be2TcNi
Be2NiRh
Be2FeNi
MnBe2Ni
Be2CoNi
Be2NiOs
Be2ReNi
Be2NiIr
Be2CoRu
Be2CoTc
Be2CoRh
Be2FeCo
MnBe2Co
BeCo
Be2CoOs
Be2CoRe
Be2CoIr
Be2CuRu
Be2CuTc
Be2CuRh
Be2FeCu
MnBe2Cu
Be2CoCu
Be2CuOs
Be2CuRe
Be2CuIr
Be2PdRu
Be2TcPd
Be2PdRh
Be2FePd
MnBe2Pd
Be2CoPd
Be2OsPd
Be2RePd
Be2IrPd
Be2RuRh
Be2TcRh
BeRh
Be2FeRh
MnBe2Rh
Be2CoRh
Be2OsRh
Be2ReRh
Be2IrRh
Be2AgRu
Be2TcAg
Be2AgRh
Be2FeAg
MnBe2Ag
Be2CoAg
Be2AgOs
Be2ReAg
Be2AgIr
BeCrFe2
Mn2BeCr
BeCrCo2
BeCrRu2
BeCrTc2
BeCrRh2
BeVFe2
Mn2BeV
BeVCo2
BeVRu2
BeVTc2
BeVRh2
MnBeFe2
Mn3Be
MnBeCo2
MnBeRu2
MnBeTc2
MnBeRh2
BeFe2Mo
Mn2BeMo
BeCo2Mo
BeMoRu2
BeTc2Mo
BeMoRh2
BeNbFe2
Mn2BeNb
BeNbCo2
BeNbRu2
BeNbTc2
BeNbRh2
BeFe2Tc
Mn2BeTc
BeCo2Tc
BeTcRu2
BeTc3
BeTcRh2
Be2IrRh
Be2IrRu
Be2IrPd
Be2CoIr
Be2FeIr
Be2NiIr
BeIr
Be2IrOs
Be2IrPt
Be2OsRh
Be2OsRu
Be2OsPd
Be2CoOs
Be2FeOs
Be2NiOs
Be2IrOs
BeOs
Be2OsPt
Be2PtRh
Be2RuPt
Be2PdPt
Be2CoPt
Be2FePt
Be2NiPt
Be2IrPt
Be2OsPt
BePt
BeRh
Be2RuRh
Be2PdRh
Be2CoRh
Be2FeRh
Be2NiRh
Be2IrRh
Be2OsRh
Be2PtRh
Be2RuRh
BeRu
Be2PdRu
Be2CoRu
Be2FeRu
Be2NiRu
Be2IrRu
Be2OsRu
Be2RuPt
Be2PdRh
Be2PdRu
BePd
Be2CoPd
Be2FePd
Be2NiPd
Be2IrPd
Be2OsPd
Be2PdPt
BeNbCo2
BeNbFe2
BeNbNi2
BeNbRh2
BeNbRu2
BeNbPd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeRh2
ZrBeRu2
ZrBePd2
BeCo2Mo
BeFe2Mo
BeNi2Mo
BeMoRh2
BeMoRu2
BeMoPd2
BeVCo2
BeVFe2
BeVNi2
BeVRh2
BeVRu2
BeVPd2
TiBeCo2
TiBeFe2
TiBeNi2
TiBeRh2
TiBeRu2
TiBePd2
BeCrCo2
BeCrFe2
BeCrNi2
BeCrRh2
BeCrRu2
BeCrPd2
TaBeCo2
TaBeFe2
TaBeNi2
TaBeRh2
TaBeRu2
TaBePd2
HfBeCo2
HfBeFe2
HfBeNi2
HfBeRh2
HfBeRu2
HfBePd2
BeCo2W
BeFe2W
BeNi2W
BeRh2W
BeRu2W
BePd2W
Be2FeRu
Be2FeTc
Be2FeRh
BeFe
MnBe2Fe
Be2FeCo
Be2FeOs
Be2FeRe
Be2FeIr
MnBe2Ru
MnBe2Tc
MnBe2Rh
MnBe2Fe
MnBe
MnBe2Co
MnBe2Os
MnBe2Re
MnBe2Ir
Be2CoRu
Be2CoTc
Be2CoRh
Be2FeCo
MnBe2Co
BeCo
Be2CoOs
Be2CoRe
Be2CoIr
BeRu
Be2TcRu
Be2RuRh
Be2FeRu
MnBe2Ru
Be2CoRu
Be2OsRu
Be2ReRu
Be2IrRu
Be2TcRu
BeTc
Be2TcRh
Be2FeTc
MnBe2Tc
Be2CoTc
Be2TcOs
Be2ReTc
Be2TcIr
Be2RuRh
Be2TcRh
BeRh
Be2FeRh
MnBe2Rh
Be2CoRh
Be2OsRh
Be2ReRh
Be2IrRh
BeVIr2
BeVOs2
BeVPt2
BeVRh2
BeVRu2
BeVPd2
TiBeIr2
TiBeOs2
TiBePt2
TiBeRh2
TiBeRu2
TiBePd2
BeCrIr2
BeCrOs2
BeCrPt2
BeCrRh2
BeCrRu2
BeCrPd2
BeNbIr2
BeNbOs2
BeNbPt2
BeNbRh2
BeNbRu2
BeNbPd2
ZrBeIr2
ZrBeOs2
ZrBePt2
ZrBeRh2
ZrBeRu2
ZrBePd2
BeMoIr2
BeMoOs2
BeMoPt2
BeMoRh2
BeMoRu2
BeMoPd2
TaBeCo2
TaBeFe2
TaBeNi2
TaBeRh2
TaBeRu2
TaBePd2
HfBeCo2
HfBeFe2
HfBeNi2
HfBeRh2
HfBeRu2
HfBePd2
BeCo2W
BeFe2W
BeNi2W
BeRh2W
BeRu2W
BePd2W
BeNbCo2
BeNbFe2
BeNbNi2
BeNbRh2
BeNbRu2
BeNbPd2
ZrBeCo2
ZrBeFe2
ZrBeNi2
ZrBeRh2
ZrBeRu2
ZrBePd2
BeCo2Mo
BeFe2Mo
BeNi2Mo
BeMoRh2
BeMoRu2
BeMoPd2
ZrBe2Pt
ZrBe2Ir
ZrBe2Au
ZrBe2Pd
ZrBe2Rh
ZrBe2Ag
YBe2Pt
YBe2Ir
YBe2Au
YBe2Pd
YBe2Rh
YBe2Ag
Be2NbPt
Be2NbIr
Be2NbAu
Be2NbPd
Be2NbRh
Be2NbAg
TiBe2Pt
TiBe2Ir
TiBe2Au
TiBe2Pd
TiBe2Rh
TiBe2Ag
ScBe2Pt
ScBe2Ir
ScBe2Au
ScBe2Pd
ScBe2Rh
ScBe2Ag
Be2VPt
Be2VIr
Be2VAu
Be2VPd
Be2VRh
Be2VAg
HfBe2Pt
HfBe2Ir
HfBe2Au
HfBe2Pd
HfBe2Rh
HfBe2Ag
LaBe2Pt
LaBe2Ir
LaBe2Au
LaBe2Pd
LaBe2Rh
LaBe2Ag
TaBe2Pt
TaBe2Ir
TaBe2Au
TaBe2Pd
TaBe2Rh
TaBe2Ag
BeCrIr2
BeCrOs2
BeCrPt2
BeCrRh2
BeCrRu2
BeCrPd2
BeVIr2
BeVOs2
BeVPt2
BeVRh2
BeVRu2
BeVPd2
MnBeIr2
MnBeOs2
MnBePt2
MnBeRh2
MnBeRu2
MnBePd2
BeMoIr2
BeMoOs2
BeMoPt2
BeMoRh2
BeMoRu2
BeMoPd2
BeNbIr2
BeNbOs2
BeNbPt2
BeNbRh2
BeNbRu2
BeNbPd2
BeTcIr2
BeTcOs2
BeTcPt2
BeTcRh2
BeTcRu2
BeTcPd2
MnBeIr2
MnBeOs2
MnBePt2
MnBeRh2
MnBeRu2
MnBePd2
BeCrIr2
BeCrOs2
BeCrPt2
BeCrRh2
BeCrRu2
BeCrPd2
BeFeIr2
BeFeOs2
BeFePt2
BeFeRh2
BeFeRu2
BeFePd2
BeTcIr2
BeTcOs2
BeTcPt2
BeTcRh2
BeTcRu2
BeTcPd2
BeMoIr2
BeMoOs2
BeMoPt2
BeMoRh2
BeMoRu2
BeMoPd2
BeIr2Ru
BeOs2Ru
BeRuPt2
BeRuRh2
BeRu3
BePd2Ru
Ti2BeTc
Ti2BeMo
Ti2BeRu
Ti2MnBe
Ti2BeCr
Ti2BeFe
Ti2BeRe
Ti2BeW
Ti2BeOs
Sc2BeTc
Sc2BeMo
Sc2BeRu
Sc2MnBe
Sc2BeCr
Sc2BeFe
Sc2BeRe
Sc2BeW
Sc2BeOs
BeV2Tc
BeV2Mo
BeV2Ru
MnBeV2
BeV2Cr
BeV2Fe
BeV2Re
BeV2W
BeV2Os
BeSi2Tc
BeSi2Mo
BeSi2Ru
MnBeSi2
BeCrSi2
BeFeSi2
BeReSi2
BeSi2W
BeSi2Os
BeAl2Tc
BeAl2Mo
BeAl2Ru
MnBeAl2
BeAl2Cr
BeAl2Fe
BeAl2Re
BeAl2W
BeAl2Os
Zr2BeTc
Zr2BeMo
Zr2BeRu
Zr2MnBe
Zr2BeCr
Zr2BeFe
Zr2BeRe
Zr2BeW
Zr2BeOs
Y2BeTc
Y2BeMo
Y2BeRu
Y2MnBe
Y2BeCr
Y2BeFe
Y2BeRe
Y2BeW
Y2BeOs
BeNb2Tc
BeNb2Mo
BeNb2Ru
MnBeNb2
BeNb2Cr
BeNb2Fe
BeNb2Re
BeNb2W
BeNb2Os
Be2CoOs
Be2CoRe
Be2CoIr
Be2CoRu
Be2CoTc
Be2CoRh
Be2FeOs
Be2FeRe
Be2FeIr
Be2FeRu
Be2FeTc
Be2FeRh
Be2NiOs
Be2ReNi
Be2NiIr
Be2NiRu
Be2TcNi
Be2NiRh
Be2OsRh
Be2ReRh
Be2IrRh
Be2RuRh
Be2TcRh
BeRh
Be2OsRu
Be2ReRu
Be2IrRu
BeRu
Be2TcRu
Be2RuRh
Be2OsPd
Be2RePd
Be2IrPd
Be2PdRu
Be2TcPd
Be2PdRh
HfBe2Pt
HfBe2Ir
HfBe2Au
HfBe2Pd
HfBe2Rh
HfBe2Ag
LaBe2Pt
LaBe2Ir
LaBe2Au
LaBe2Pd
LaBe2Rh
LaBe2Ag
TaBe2Pt
TaBe2Ir
TaBe2Au
TaBe2Pd
TaBe2Rh
TaBe2Ag
ZrBe2Pt
ZrBe2Ir
ZrBe2Au
ZrBe2Pd
ZrBe2Rh
ZrBe2Ag
YBe2Pt
YBe2Ir
YBe2Au
YBe2Pd
YBe2Rh
YBe2Ag
Be2NbPt
Be2NbIr
Be2NbAu
Be2NbPd
Be2NbRh
Be2NbAg
Be2IrRu
Be2TcIr
Be2IrRh
Be2FeIr
MnBe2Ir
Be2CoIr
Be2IrOs
Be2ReIr
BeIr
Be2OsRu
Be2TcOs
Be2OsRh
Be2FeOs
MnBe2Os
Be2CoOs
BeOs
Be2ReOs
Be2IrOs
Be2RuPt
Be2TcPt
Be2PtRh
Be2FePt
MnBe2Pt
Be2CoPt
Be2OsPt
Be2RePt
Be2IrPt
Be2RuRh
Be2TcRh
BeRh
Be2FeRh
MnBe2Rh
Be2CoRh
Be2OsRh
Be2ReRh
Be2IrRh
BeRu
Be2TcRu
Be2RuRh
Be2FeRu
MnBe2Ru
Be2CoRu
Be2OsRu
Be2ReRu
Be2IrRu
Be2PdRu
Be2TcPd
Be2PdRh
Be2FePd
MnBe2Pd
Be2CoPd
Be2OsPd
Be2RePd
Be2IrPd
Zr2BeTc
Zr2BeMo
Zr2BeRu
Zr2MnBe
Zr2BeCr
Zr2BeFe
Zr2BeRe
Zr2BeW
Zr2BeOs
Y2BeTc
Y2BeMo
Y2BeRu
Y2MnBe
Y2BeCr
Y2BeFe
Y2BeRe
Y2BeW
Y2BeOs
BeNb2Tc
BeNb2Mo
BeNb2Ru
MnBeNb2
BeNb2Cr
BeNb2Fe
BeNb2Re
BeNb2W
BeNb2Os
Ti2BeTc
Ti2BeMo
Ti2BeRu
Ti2MnBe
Ti2BeCr
Ti2BeFe
Ti2BeRe
Ti2BeW
Ti2BeOs
Sc2BeTc
Sc2BeMo
Sc2BeRu
Sc2MnBe
Sc2BeCr
Sc2BeFe
Sc2BeRe
Sc2BeW
Sc2BeOs
BeV2Tc
BeV2Mo
BeV2Ru
MnBeV2
BeV2Cr
BeV2Fe
BeV2Re
BeV2W
BeV2Os
Hf2BeTc
Hf2BeMo
Hf2BeRu
Hf2MnBe
Hf2BeCr
Hf2BeFe
Hf2BeRe
Hf2BeW
Hf2BeOs
La2BeTc
La2BeMo
La2BeRu
La2MnBe
La2BeCr
La2BeFe
La2BeRe
La2BeW
La2BeOs
Ta2BeTc
Ta2BeMo
Ta2BeRu
Ta2MnBe
Ta2BeCr
Ta2BeFe
Ta2BeRe
Ta2BeW
Ta2BeOs
BeFeRu2
BeFeTc2
BeFeRh2
BeFe3
Mn2BeFe
BeFeCo2
BeFeOs2
BeFeRe2
BeFeIr2
MnBeRu2
MnBeTc2
MnBeRh2
MnBeFe2
Mn3Be
MnBeCo2
MnBeOs2
MnBeRe2
MnBeIr2
BeCoRu2
BeCoTc2
BeCoRh2
BeFe2Co
Mn2BeCo
BeCo3
BeCoOs2
BeCoRe2
BeCoIr2
BeRu3
BeTc2Ru
BeRuRh2
BeFe2Ru
Mn2BeRu
BeCo2Ru
BeOs2Ru
BeRe2Ru
BeIr2Ru
BeTcRu2
BeTc3
BeTcRh2
BeFe2Tc
Mn2BeTc
BeCo2Tc
BeTcOs2
BeRe2Tc
BeTcIr2
BeRu2Rh
BeTc2Rh
BeRh3
BeFe2Rh
Mn2BeRh
BeCo2Rh
BeOs2Rh
BeRe2Rh
BeIr2Rh
Ti2BeMo
Ti2BeNb
Ti2BeTc
Ti2BeCr
Ti2BeV
Ti2MnBe
Ti2BeW
TaTi2Be
Ti2BeRe
Sc2BeMo
Sc2BeNb
Sc2BeTc
Sc2BeCr
Sc2BeV
Sc2MnBe
Sc2BeW
Sc2TaBe
Sc2BeRe
BeV2Mo
BeNbV2
BeV2Tc
BeV2Cr
BeV3
MnBeV2
BeV2W
TaBeV2
BeV2Re
BeSi2Mo
BeNbSi2
BeSi2Tc
BeCrSi2
BeVSi2
MnBeSi2
BeSi2W
TaBeSi2
BeReSi2
BeAl2Mo
BeNbAl2
BeAl2Tc
BeAl2Cr
BeAl2V
MnBeAl2
BeAl2W
TaBeAl2
BeAl2Re
Zr2BeMo
Zr2BeNb
Zr2BeTc
Zr2BeCr
Zr2BeV
Zr2MnBe
Zr2BeW
Zr2TaBe
Zr2BeRe
Y2BeMo
Y2BeNb
Y2BeTc
Y2BeCr
Y2BeV
Y2MnBe
Y2BeW
Y2TaBe
Y2BeRe
BeNb2Mo
BeNb3
BeNb2Tc
BeNb2Cr
BeNb2V
MnBeNb2
BeNb2W
TaBeNb2
BeNb2Re
Ti2BeRe
Ti2BeW
Ti2BeOs
Ti2BeTc
Ti2BeMo
Ti2BeRu
Sc2BeRe
Sc2BeW
Sc2BeOs
Sc2BeTc
Sc2BeMo
Sc2BeRu
BeV2Re
BeV2W
BeV2Os
BeV2Tc
BeV2Mo
BeV2Ru
BeReSi2
BeSi2W
BeSi2Os
BeSi2Tc
BeSi2Mo
BeSi2Ru
BeAl2Re
BeAl2W
BeAl2Os
BeAl2Tc
BeAl2Mo
BeAl2Ru
Zr2BeRe
Zr2BeW
Zr2BeOs
Zr2BeTc
Zr2BeMo
Zr2BeRu
Y2BeRe
Y2BeW
Y2BeOs
Y2BeTc
Y2BeMo
Y2BeRu
BeNb2Re
BeNb2W
BeNb2Os
BeNb2Tc
BeNb2Mo
BeNb2Ru
BeFe2W
TaBeFe2
BeFe2Re
BeFe2Mo
BeNbFe2
BeFe2Tc
Mn2BeW
TaMn2Be
Mn2BeRe
Mn2BeMo
Mn2BeNb
Mn2BeTc
BeCo2W
TaBeCo2
BeCo2Re
BeCo2Mo
BeNbCo2
BeCo2Tc
BeRu2W
TaBeRu2
BeReRu2
BeMoRu2
BeNbRu2
BeTcRu2
BeTc2W
TaBeTc2
BeReTc2
BeTc2Mo
BeNbTc2
BeTc3
BeRh2W
TaBeRh2
BeReRh2
BeMoRh2
BeNbRh2
BeTcRh2
BeNbOs2
BeNbRe2
BeNbIr2
BeNbRu2
BeNbTc2
BeNbRh2
ZrBeOs2
ZrBeRe2
ZrBeIr2
ZrBeRu2
ZrBeTc2
ZrBeRh2
BeMoOs2
BeRe2Mo
BeMoIr2
BeMoRu2
BeTc2Mo
BeMoRh2
BeVOs2
BeVRe2
BeVIr2
BeVRu2
BeVTc2
BeVRh2
TiBeOs2
TiBeRe2
TiBeIr2
TiBeRu2
TiBeTc2
TiBeRh2
BeCrOs2
BeCrRe2
BeCrIr2
BeCrRu2
BeCrTc2
BeCrRh2
TaBeOs2
TaBeRe2
TaBeIr2
TaBeRu2
TaBeTc2
TaBeRh2
HfBeOs2
HfBeRe2
HfBeIr2
HfBeRu2
HfBeTc2
HfBeRh2
BeOs2W
BeRe2W
BeIr2W
BeRu2W
BeTc2W
BeRh2W
TaBeOs2
TaBeRe2
TaBeIr2
TaBeRu2
TaBeTc2
TaBeRh2
HfBeOs2
HfBeRe2
HfBeIr2
HfBeRu2
HfBeTc2
HfBeRh2
BeOs2W
BeRe2W
BeIr2W
BeRu2W
BeTc2W
BeRh2W
BeNbOs2
BeNbRe2
BeNbIr2
BeNbRu2
BeNbTc2
BeNbRh2
ZrBeOs2
ZrBeRe2
ZrBeIr2
ZrBeRu2
ZrBeTc2
ZrBeRh2
BeMoOs2
BeRe2Mo
BeMoIr2
BeMoRu2
BeTc2Mo
BeMoRh2
Hf2BeRe
Hf2BeW
Hf2BeOs
Hf2BeTc
Hf2BeMo
Hf2BeRu
La2BeRe
La2BeW
La2BeOs
La2BeTc
La2BeMo
La2BeRu
Ta2BeRe
Ta2BeW
Ta2BeOs
Ta2BeTc
Ta2BeMo
Ta2BeRu
Zr2BeRe
Zr2BeW
Zr2BeOs
Zr2BeTc
Zr2BeMo
Zr2BeRu
Y2BeRe
Y2BeW
Y2BeOs
Y2BeTc
Y2BeMo
Y2BeRu
BeNb2Re
BeNb2W
BeNb2Os
BeNb2Tc
BeNb2Mo
BeNb2Ru

In [105]:
from pymatgen.analysis.structure_prediction.substitution_probability import SubstitutionPredictor
from pymatgen.core import Composition

In [106]:
sub = SubstitutionPredictor()

In [108]:
c = Composition('Si3N4')

In [114]:
from pymatgen.analysis.structure_prediction import OxidationStateGuess

ImportError: cannot import name 'OxidationStateGuess' from 'pymatgen.analysis.structure_prediction' (/home/jasongibson/.conda/envs/e3nn/lib/python3.9/site-packages/pymatgen/analysis/structure_prediction/__init__.py)

In [107]:
sub.composition_prediction(Composition('Si3N4'))

ValueError: the species Si is not allowed for the probability model you are using

In [100]:
i

79448526

In [95]:
i

96762060

In [92]:
i

200402220

In [89]:
i

209163500

In [59]:
from collections import defaultdict

wyckoff_species = defaultdict(list)
for site, wyckoff in zip(structure, wyckoff_sites):
    wyckoff_species[wyckoff].append(site.species_string)
    
sub_sites = []
for wyckoff, species_list in wyckoff_species.items():
    if 'Be' not in species_list:
        sub_sites.append(wyckoff)
        print(f"Wyckoff site {wyckoff}: {species_list}")

Wyckoff site a: ['Nd', 'Nd']

In [75]:
elements = [
    'H', 'Li', 'Be', 'B', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 
    'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As','Rb', 'Sr', 'Y', 'Zr', 
    'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'Cs', 
    'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 
    'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At']
len(elements)

70

In [61]:
from pymatgen.core.sites import PeriodicSite
from pymatgen.core import Element

# Create a copy of the structure to modify
new_structure = structure.copy()

# Iterate over the sites and substitute based on Wyckoff sites
for i, site in enumerate(structure):
    if wyckoff_sites[i] == "g":  # Replace "a" with the specific Wyckoff position
        new_element = Element("Cl")  # Replace "Ge" with the desired element
        new_site = PeriodicSite(new_element, site.frac_coords, site.lattice)
        new_structure[i] = new_site

# Print the modified structure
print(new_structure)

# Save the modified structure to a CIF file

Full Formula (Nd2 Be26)
Reduced Formula: NdBe13
abc   :   7.284912   7.284912   7.284912
angles:  60.000000  60.000000  60.000000
pbc   :       True       True       True
Sites (28)
  #  SP           a         b         c    magmom
---  ----  --------  --------  --------  --------
  0  Nd    0.75      0.75      0.75            -0
  1  Nd    0.25      0.25      0.25             0
  2  Be    0.788495  0.563061  0.436939        -0
  3  Be    0.563061  0.788495  0.211505         0
  4  Be    0.211505  0.436939  0.563061         0
  5  Be    0.436939  0.211505  0.788495         0
  6  Be    0.436939  0.788495  0.563061        -0
  7  Be    0.563061  0.436939  0.788495        -0
  8  Be    0.788495  0.436939  0.211505        -0
  9  Be    0.788495  0.211505  0.563061        -0
 10  Be    0.211505  0.563061  0.788495         0
 11  Be    0.436939  0.563061  0.211505        -0
 12  Be    0.563061  0.211505  0.436939         0
 13  Be    0.211505  0.788495  0.436939         0
 14  Be    0.936939  0.711505  0.063061         0
 15  Be    0.711505  0.936939  0.288495        -0
 16  Be    0.063061  0.288495  0.936939        -0
 17  Be    0.288495  0.063061  0.711505         0
 18  Be    0.711505  0.063061  0.936939        -0
 19  Be    0.063061  0.936939  0.711505         0
 20  Be    0.063061  0.711505  0.288495         0
 21  Be    0.288495  0.711505  0.936939        -0
 22  Be    0.936939  0.288495  0.711505         0
 23  Be    0.936939  0.063061  0.288495         0
 24  Be    0.288495  0.936939  0.063061         0
 25  Be    0.711505  0.288495  0.063061        -0
 26  Be    0.5       0.5       0.5             -0
 27  Be    0         0         0                0

In [217]:
from tqdm.notebook import tqdm
import matgl
from matgl.ext.ase import PESCalculator, MolecularDynamics, Relaxer

pot = matgl.load_model("M3GNet-MP-2021.2.8-PES")
model_form = matgl.load_model("MEGNet-MP-2018.6.1-Eform")
model_bg = matgl.load_model("MEGNet-MP-2019.4.1-BandGap-mfi")

relaxer = Relaxer(potential=pot)
relax_results = relaxer.relax(new_structures[1], fmax=0.001)
# extract results
final_structure = relax_results["final_structure"]
final_energy = relax_results["trajectory"].energies[-1]
# print out the final relaxed structure and energy
print(final_structure)
print(f"The final energy is {float(final_energy):.3f} eV.")

# For multi-fidelity models, we need to define graph label ("0": PBE, "1": GLLB-SC, "2": HSE, "3": SCAN)
for i, method in ((0, "PBE"), (1, "GLLB-SC"), (2, "HSE"), (3, "SCAN")):
    graph_attrs = torch.tensor([i])
    bandgap = model_bg.predict_structure(structure=final_structure, state_attr=graph_attrs)
    print(f"The predicted {method} band gap for {final_structure.composition.reduced_formula} is {float(bandgap):.3f} eV.")

eform = model_form.predict_structure(final_structure)
print(f"The predicted formation energy for {final_structure.composition.reduced_formula} is {float(eform):.3f} eV/atom.")

In [215]:
relaxer = Relaxer(potential=pot)
relax_results = relaxer.relax(new_structures[1], fmax=0.001)
# extract results
final_structure = relax_results["final_structure"]
final_energy = relax_results["trajectory"].energies[-1]
# print out the final relaxed structure and energy
print(final_structure)
print(f"The final energy is {float(final_energy):.3f} eV.")

# For multi-fidelity models, we need to define graph label ("0": PBE, "1": GLLB-SC, "2": HSE, "3": SCAN)
for i, method in ((0, "PBE"), (1, "GLLB-SC"), (2, "HSE"), (3, "SCAN")):
    graph_attrs = torch.tensor([i])
    bandgap = model_bg.predict_structure(structure=final_structure, state_attr=graph_attrs)
    print(f"The predicted {method} band gap for {final_structure.composition.reduced_formula} is {float(bandgap):.3f} eV.")

eform = model_form.predict_structure(final_structure)
print(f"The predicted formation energy for {final_structure.composition.reduced_formula} is {float(eform):.3f} eV/atom.")

Full Formula (Be1 Nb1 Tc2)
Reduced Formula: BeNbTc2
abc   :   4.317669   4.317670   4.317670
angles:  60.000003  60.000006  59.999996
pbc   :       True       True       True
Sites (4)
  #  SP        a     b      c    magmom
---  ----  -----  ----  -----  --------
  0  Be     0.5   0.5    0.5         -0
  1  Nb    -0     0     -0          nan
  2  Tc     0.25  0.25   0.25       nan
  3  Tc     0.75  0.75   0.75       nan
The final energy is -35.227 eV.

In [219]:
# For multi-fidelity models, we need to define graph label ("0": PBE, "1": GLLB-SC, "2": HSE, "3": SCAN)
for i, method in ((0, "PBE"), (1, "GLLB-SC"), (2, "HSE"), (3, "SCAN")):
    graph_attrs = torch.tensor([i])
    bandgap = model_bg.predict_structure(structure=final_structure, state_attr=graph_attrs)
    print(f"The predicted {method} band gap for {final_structure.composition.reduced_formula} is {float(bandgap):.3f} eV.")

eform = model_form.predict_structure(final_structure)
print(f"The predicted formation energy for {final_structure.composition.reduced_formula} is {float(eform):.3f} eV/atom.")

The predicted PBE band gap for BeNbTc2 is -0.008 eV.
The predicted GLLB-SC band gap for BeNbTc2 is 0.980 eV.
The predicted HSE band gap for BeNbTc2 is -0.008 eV.
The predicted SCAN band gap for BeNbTc2 is 0.497 eV.
The predicted formation energy for BeNbTc2 is -0.167 eV/atom.

/home/jasongibson/.conda/envs/e3nn/lib/python3.9/site-packages/dgl/readout.py:443: DGLWarning:

For a single graph, use a tensor of shape (1, *) for graph_feat. The support of shape (*) will be deprecated.

In [63]:
len(final_structure)

144

In [64]:
new_structure =new_structure.make_supercell([2,2,2])

In [211]:
new_structures[1]

Structure Summary
Lattice
    abc : 4.280593936492692 4.280593936492692 4.280593936492692
 angles : 60.00000000000001 60.00000000000001 60.00000000000001
 volume : 55.46220069957552
      A : 0.0 3.026837 3.026837
      B : 3.026837 0.0 3.026837
      C : 3.026837 3.026837 0.0
    pbc : True True True
PeriodicSite: Be (3.027, 3.027, 3.027) [0.5, 0.5, 0.5]
PeriodicSite: Nb (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Tc (1.513, 1.513, 1.513) [0.25, 0.25, 0.25]
PeriodicSite: Tc (4.54, 4.54, 4.54) [0.75, 0.75, 0.75]

In [210]:
relaxer = Relaxer(potential=pot)
relax_results = relaxer.relax(new_structures[1], fmax=0.001)
# extract results
final_structure = relax_results["final_structure"]
final_energy = relax_results["trajectory"].energies[-1]
# print out the final relaxed structure and energy

print(final_structure)
print(f"The final energy is {float(final_energy):.3f} eV.")

/home/jasongibson/.conda/envs/e3nn/lib/python3.9/site-packages/matgl/layers/_basis.py:121: UserWarning:

To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).

Full Formula (Be1 Nb1 Tc2)
Reduced Formula: BeNbTc2
abc   :   4.317669   4.317670   4.317670
angles:  60.000003  60.000006  59.999996
pbc   :       True       True       True
Sites (4)
  #  SP        a     b      c    magmom
---  ----  -----  ----  -----  --------
  0  Be     0.5   0.5    0.5         -0
  1  Nb    -0     0     -0          nan
  2  Tc     0.25  0.25   0.25       nan
  3  Tc     0.75  0.75   0.75       nan
The final energy is -35.227 eV.

In [66]:
analyzer = SpacegroupAnalyzer(final_structure)
sym_data = analyzer.get_symmetry_dataset()

In [67]:
final_structure = relax_results['final_structure']
final_energy_per_atom = float(relax_results['trajectory'].energies[-1] / len(final_structure))

print(f"Relaxed lattice parameter is {final_structure.lattice.abc[0]:.3f} Å")
print(f"Final energy is {final_energy_per_atom:.3f} eV/atom")

Relaxed lattice parameter is 14.585 Å
Final energy is -3.970 eV/atom

In [68]:
from pymatgen.analysis.phase_diagram import *
from pymatgen.ext.matproj import MPRester

In [70]:
entries = mpr.get_entries_in_chemsys(['Be', 'Nd'])
    
phasediagram = PhaseDiagram(entries)

plotter = PDPlotter(phasediagram)

p = plotter.get_plot(label_unstable=False)
p.show()

In [71]:
pde = PDEntry(final_structure.composition,final_energy)
phasediagram.get_form_energy_per_atom(pde)

-0.15670271390764562

In [72]:
phasediagram.get_e_above_hull(pde)

0.005415243235212142

In [73]:
len(final_structure)

224

In [55]:
import torch

In [74]:
model = matgl.load_model("MEGNet-MP-2019.4.1-BandGap-mfi")

# For multi-fidelity models, we need to define graph label ("0": PBE, "1": GLLB-SC, "2": HSE, "3": SCAN)
for i, method in ((0, "PBE"), (1, "GLLB-SC"), (2, "HSE"), (3, "SCAN")):
    graph_attrs = torch.tensor([i])
    bandgap = model.predict_structure(structure=final_structure, state_attr=graph_attrs)
    print(f"The predicted {method} band gap for CsCl is {float(bandgap):.3f} eV.")

/home/jasongibson/.conda/envs/e3nn/lib/python3.9/site-packages/matgl/utils/io.py:126: UserWarning:

Incompatible model version detected! The code will continue to load the model but it is recommended that you provide a path to an updated model, increment your @model_version in model.json if you are confident that the changes are not problematic, or clear your ~/.matgl cache using `python -c "import matgl; matgl.clear_cache()"`

The predicted PBE band gap for CsCl is -0.010 eV.
The predicted GLLB-SC band gap for CsCl is 0.114 eV.
The predicted HSE band gap for CsCl is -0.008 eV.
The predicted SCAN band gap for CsCl is 0.019 eV.